### ISSUE TITLE
telegraf 1.21.2 crashing, unable to use snmp

### ISSUE THREAD

**Issue by jostrasser** [influxdata/telegraf#10387]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "192.168.5.10:161" ]
#   ## Timeout for each SNMP query.
  timeout = "30s"
#   ## Interval for each SNMP query.
  interval = "15s"
#   ## Number of retries to attempt within timeout.
  retries = 3
#   ## SNMP version, values can be 1, 2, or 3
  version = 2
#
#   ## SNMP community string.
  community = "public"
#
#   ## The GETBULK max-repetitions parameter
  max_repetitions = 10
#
#   ## SNMPv3 auth parameters
#   #sec_name = "myuser"
#   #auth_protocol = "md5"      # Values: "MD5", "SHA", ""
#   #auth_password = "pass"
#   #sec_level = "authNoPriv"   # Values: "noAuthNoPriv", "authNoPriv", "authPriv"
#   #context_name = ""
#   #priv_protocol = ""         # Values: "DES", "AES", ""
#   #priv_password = ""
#
#   ## measurement name
#   name = "QNAP"
#[[inputs.snmp.table]]
#name = "remote_servers"

# QNAP System
[[inputs.snmp.field]]
  name = "CPU_Load"
  oid = "1.3.6.1.4.1.24681.1.3.1.0"
#
[[inputs.snmp.field]]
  name = "CPU1"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196608"
#
[[inputs.snmp.field]]
  name = "CPU2"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196609"
#
[[inputs.snmp.field]]
  name = "CPU3"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196610"
#
[[inputs.snmp.field]]
  name = "CPU4"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196611"
#
[[inputs.snmp.field]]
  name = "CPU5"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196612"
#
[[inputs.snmp.field]]
  name = "CPU6"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196613"
#
[[inputs.snmp.field]]
  name = "CPU7"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196614"
#
[[inputs.snmp.field]]
  name = "CPU8"
  oid = "1.3.6.1.2.1.25.3.3.1.2.196615"
#
[[inputs.snmp.field]]
  name = "Total_RAM"
  oid = "1.3.6.1.4.1.24681.1.3.2.0"
#
[[inputs.snmp.field]]
  name = "Free_RAM"
  oid = "1.3.6.1.4.1.24681.1.3.3.0"
#
[[inputs.snmp.field]]
  name = "Fan1_Speed"
  oid = "1.3.6.1.4.1.24681.1.3.15.1.3.1"
#
[[inputs.snmp.field]]
  name = "Fan2_Speed"
  oid = "1.3.6.1.4.1.24681.1.3.15.1.3.2"
#
[[inputs.snmp.field]]
  name = "System_Temp"
  oid = "1.3.6.1.4.1.24681.1.3.6.0"

# Input Hostnames
[[inputs.snmp.field]]
    name = "hostname"
    oid = "1.3.6.1.2.1.1.5.0"
    is_tag = true


# Networking All Interfaces QNAP + SWITCHES
[[inputs.snmp.table]]
        #ifTable,1.3.6.1.2.1.2.2,IF-MIB,OBJECT
    name = "ifTable"
    inherit_tags = [ "hostname" ]
#
#
    [[inputs.snmp.table.field]]
        #ifDescr,1.3.6.1.2.1.2.2.1.2,IF-MIB,OBJECT
      name = "Interface"
      oid = "1.3.6.1.2.1.2.2.1.2"
      is_tag = true
#
    [[inputs.snmp.table.field]]
        #ifInOctets,1.3.6.1.2.1.2.2.1.10,IF-MIB,OBJECT
      name = "RXBytes"
      oid = "1.3.6.1.2.1.2.2.1.10"
#
    [[inputs.snmp.table.field]]
        #ifOutOctets,1.3.6.1.2.1.2.2.1.16,IF-MIB,OBJECT
#
      name = "TXBytes"
      oid = "1.3.6.1.2.1.2.2.1.16"
#
# End Networking Interfaces

# QNAP DISK Section
[[inputs.snmp]]
  agents = [ "192.168.5.10:161"]
#   ## Timeout for each SNMP query.
  timeout = "30s"
  interval = "10m"
#   ## Number of retries to attempt within timeout.
  retries = 3
#   ## SNMP version, values can be 1, 2, or 3
  version = 2
#
#   ## SNMP community string.
  community = "public"
#
#   ## The GETBULK max-repetitions parameter
  max_repetitions = 10


# QNAP HDD Table
  [[inputs.snmp.table]]
        #systemHdTableEX,1.3.6.1.4.1.24681.1.3.11,NAS-MIB,OBJECT-TYPE
    name = "HDDTable"
    inherit_tags = [ "hostname" ]
#
    [[inputs.snmp.table.field]]
        #hdDescrEX,1.3.6.1.4.1.24681.1.3.11.1.2,NAS-MIB,OBJECT-TYPE
#
      name = "HDDDescription"
      oid = "1.3.6.1.4.1.24681.1.3.11.1.2"
      is_tag = true
#
    [[inputs.snmp.table.field]]
        #hdTemperatureEX,1.3.6.1.4.1.24681.1.3.11.1.3,NAS-MIB,OBJECT-TYPE
      name = "Temperature"
      oid = "1.3.6.1.4.1.24681.1.3.11.1.3"
#
    [[inputs.snmp.table.field]]
        #hdStatusEX,1.3.6.1.4.1.24681.1.3.11.1.4,NAS-MIB,OBJECT-TYPE
      name = "Status"
      oid = "1.3.6.1.4.1.24681.1.3.11.1.4"
#
    [[inputs.snmp.table.field]]
        #hdSmartInfoEX,1.3.6.1.4.1.24681.1.3.11.1.7,NAS-MIB,OBJECT-TYPE
      name = "S.M.A.R.T."
      oid = "1.3.6.1.4.1.24681.1.3.11.1.7"

# QNAP DISKPOOL Table
[[inputs.snmp.table]]
        #poolTable,1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2,NAS-MIB,OBJECT-TYPE
    name = "poolTable"
    inherit_tags = [ "hostname" ]
#
    [[inputs.snmp.table.field]]
        #poolID,1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.2,NAS-MIB,OBJECT-TYPE
      name = "poolID"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.2"
      is_tag = true
#
    [[inputs.snmp.table.field]]
        #poolCapacity,1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.3,NAS-MIB,OBJECT-TYPE
      name = "poolCapacity"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.3"
#
    [[inputs.snmp.table.field]]
        #poolFreeSize,1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.4,NAS-MIB,OBJECT-TYPE
      name = "poolFreeSize"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.4"

    [[inputs.snmp.table.field]]
        #poolStatus,1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.5,NAS-MIB,OBJECT-TYPE
      name = "poolStatus"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.2.2.1.5"

# QNAP VOLUME Table       
[[inputs.snmp.table]]
        #volumeTable,1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2,NAS-MIB,OBJECT-TYPE
    name = "volumeTable"
    inherit_tags = [ "hostname" ]
#
    [[inputs.snmp.table.field]]
        #volumeName,1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.8,NAS-MIB,OBJECT-TYPE
      name = "volumeName"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.8"
      is_tag = true
#
    [[inputs.snmp.table.field]]
        #volumeCapacity,1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.3,NAS-MIB,OBJECT-TYPE
      name = "volumeCapacity"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.3"
#
    [[inputs.snmp.table.field]]
        #volumeFreeSize,1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.4,NAS-MIB,OBJECT-TYPE
      name = "volumeFreeSize"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.4"
#
    [[inputs.snmp.table.field]]
        #volumeStatus,1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.5,NAS-MIB,OBJECT-TYPE
      name = "volumeStatus"
      oid = "1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2.1.5"
```

### Logs from Telegraf

Errors after upgrading to 1.21.1:

```
Dec 24 16:59:03 snmpdb telegraf[173]: 2021-12-24T15:59:03Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"snmpdb", Flush Interval:10s
Dec 24 16:59:03 snmpdb telegraf[173]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 24 16:59:03 snmpdb telegraf[173]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2c0a113]
Dec 24 16:59:03 snmpdb telegraf[173]: goroutine 1 [running]:
Dec 24 16:59:03 snmpdb telegraf[173]: github.com/influxdata/telegraf/internal/snmp.LoadMibsFromPath.func1({0x4deff4e, 0x14}, {0x0, 0x0}, {0x0, 0x2c09920})
Dec 24 16:59:03 snmpdb telegraf[173]: #011/go/src/github.com/influxdata/telegraf/internal/snmp/translate.go:60 +0x53
Dec 24 16:59:03 snmpdb telegraf[173]: path/filepath.Walk({0x4deff4e, 0x14}, 0xc000bed640)
Dec 24 16:59:03 snmpdb telegraf[173]: #011/usr/local/go/src/path/filepath/path.go:503 +0x50
Dec 24 16:59:03 snmpdb telegraf[173]: github.com/influxdata/telegraf/internal/snmp.LoadMibsFromPath({0xc000d34260, 0x1, 0xc000bed6c8}, {0x584e030, 0xc000d416e0})
Dec 24 16:59:03 snmpdb telegraf[173]: #011/go/src/github.com/influxdata/telegraf/internal/snmp/translate.go:57 +0x29a
Dec 24 16:59:03 snmpdb telegraf[173]: github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Init(0xc00033edc0)
Dec 24 16:59:03 snmpdb telegraf[173]: #011/go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:102 +0x50
Dec 24 16:59:03 snmpdb telegraf[173]: github.com/influxdata/telegraf/models.(*RunningInput).Init(0xc000bed758)
Dec 24 16:59:03 snmpdb telegraf[173]: #011/go/src/github.com/influxdata/telegraf/models/running_input.go:82 +0x35
Dec 24 16:59:03 snmpdb telegraf[173]: github.com/influxdata/telegraf/agent.(*Agent).initPlugins(0xc0001113a0)
Dec 24 16:59:03 snmpdb telegraf[173]: #011/go/src/github.com/influxdata/telegraf/agent/agent.go:189 +0x96
Dec 24 16:59:03 snmpdb telegraf[173]: github.com/influxdata/telegraf/agent.(*Agent).Run(0xc0001113a0, {0x57e5688, 0xc0002ca680})
Dec 24 16:59:03 snmpdb telegraf[173]: #011/go/src/github.com/influxdata/telegraf/agent/agent.go:105 +0x185
Dec 24 16:59:03 snmpdb systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 24 16:59:03 snmpdb systemd[1]: telegraf.service: Failed to kill control group /system.slice/telegraf.service, ignoring: Input/output error
Dec 24 16:59:03 snmpdb systemd[1]: message repeated 3 times: [ telegraf.service: Failed to kill control group /system.slice/telegraf.service, ignoring: Input/output error]
Dec 24 16:59:03 snmpdb systemd[1]: telegraf.service: Failed with result 'exit-code'.
Dec 24 16:59:03 snmpdb systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 4.
Dec 24 16:59:03 snmpdb systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Dec 24 16:59:03 snmpdb systemd[1]: Failed to attach 184 to compat systemd cgroup /system.slice/telegraf.service: No such file or directory
Dec 24 16:59:03 snmpdb systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Dec 24 16:59:03 snmpdb systemd[184]: Failed to attach 184 to compat systemd cgroup /system.slice/telegraf.service: No such file or directory
Dec 24 16:59:03 snmpdb influxd-systemd-start.sh[80]: InfluxDB API unavailable after 2 attempts...
```

Errors after upgrading to 1.21.2:

`2022-01-05T21:02:06Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: Filepath could not be walked: no mibs found`

### System info

Ubuntu 20.04LTS (LXD), Telegraf 1.21.2 and 1.21.1 affected, 1.20.4 is the last working release

### Steps to reproduce

1. upgrade to latest telegraf release

2. Workaround is downgrading to 1.20.4, works immediately.

### Expected behavior

Collect snmp metrics

### Actual behavior

telegraf stops working with the latest release, unable to collect data via snmp

**Comment by powersj** [comment]
@MyaLongmire could you take a look at this please?

**Comment by MyaLongmire** [comment]
Looking at the seg fault it seems there is no file path to walk. [This pr](https://github.com/influxdata/telegraf/pull/10354) is in the work of fixing this issue.

**Comment by jostrasser** [comment]
> Looking at the seg fault it seems there is no file path to walk. [This pr](https://github.com/influxdata/telegraf/pull/10354) is in the work of fixing this issue. 

Thanks @MyaLongmire 
Is there a planned version which brings the fix?

**Comment by MyaLongmire** [comment]
It will depend on when the pr gets finished up. But when it gets merged you can grab a nightly build or the next bug release will be around the first week of February.

**Comment by jostrasser** [comment]
> It will depend on when the pr gets finished up. But when it gets merged you can grab a nightly build or the next bug release will be around the first week of February. 

Great, thank you!

**Comment by MyaLongmire** [comment]
The pr was merged into master. You can grab a nightly or clone master. The fix should also be in the next bug release.

**Comment by jostrasser** [comment]
Thanks for your support @MyaLongmire !!

**Comment by jostrasser** [comment]
Hi @MyaLongmire 
I think the issue is not solved. 
I am getting a new error after upgrading to version Telegraf 1.21.3 (git: HEAD 8610b5e7)

`2022-01-29T05:58:45Z E! [inputs.snmp] Error in plugin: agent 192.168.5.10:161: gathering table ifTable: performing bulk walk for field Interface: &GoSNMP.Conn is missing. Provide a connection or use Connect()`

Looks strange for me because the snmp connection is correctly set and works again after downgrading to Telegraf 1.20.4 (git: HEAD 34ad5aa1)

Thanks!

**Comment by jostrasser** [comment]
Hi @MyaLongmire @powersj  
Should I open a new issue?

**Comment by powersj** [comment]
> Hi @MyaLongmire @powersj Should I open a new issue?

Please do

**Comment by MyaLongmire** [comment]
I believe this is because the gosnmp library got updated. I will look into a work around :)
