### ISSUE TITLE
invalid memory address or nil pointer dereference with Docker plugin

### ISSUE THREAD

**Issue by jwmarshall** [influxdata/telegraf#1081]
This seems to have coincided with a container redeploy.

Ubuntu 14.04
Telegraf version: 0.12.1

```
2016/04/22 10:44:50 Error decoding: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x583e6c]

goroutine 175910 [running]:
panic(0x10241a0, 0xc8200100f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/docker.gatherContainerStats(0x0, 0x7f05a21db800, 0xc82037be00, 0xc8205
a2fc0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:238 +0x352c
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainer(0xc820184c80, 0xc820849f80, 0x40, 0xc
820849fc0, 0x1, 0x4, 0xc820609730, 0xc, 0xc820668690, 0x47, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:228 +0x963
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather.func1(0xc8206099c0, 0xc820184c80, 0x7f05a21db8
00, 0xc82037be00, 0xc820849f80, 0x40, 0xc820849fc0, 0x1, 0x4, 0xc820609730, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:112 +0x9e
created by github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:116 +0x58d
2016/04/22 10:44:58 Starting Telegraf (version 0.12.1)
2016/04/22 10:44:58 Loaded outputs: influxdb
2016/04/22 10:44:58 Loaded inputs: diskio mem net swap system cpu disk docker
```

**Comment by sparrc** [comment]
thanks for the report @jwmarshall, this has been fixed already and will be available in the next release (see https://github.com/influxdata/telegraf/issues/1052)

**Comment by jwmarshall** [comment]
Thanks! Great work!
