### ISSUE TITLE
FATAL: Input [cassandra] panicked: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alekiv** [influxdata/telegraf#1102]
Telegraf (Version 0.12.1) panicked when I try to read DownEndpointCount metric from Cassandra with cassandra plugin.

telegraf configuration:
```
[[inputs.cassandra]]
  context = "/jolokia/read"
  servers = [":8778"]
  metrics  = [
    "/org.apache.cassandra.net:type=FailureDetector/DownEndpointCount"
  ]
```

Log:
```
Apr 27 11:39:20 vm1 telegraf[49680]: host  url http://:8778/jolokia/read/org.apache.cassandra.net:type=FailureDetector/DownEndpointCount
Apr 27 11:39:20 vm1 telegraf[49680]: 2016/04/27 11:39:20 FATAL: Input [cassandra] panicked: runtime error: invalid memory address or nil pointer dereference, Stack:
Apr 27 11:39:20 vm1 telegraf[49680]: goroutine 179 [running]:
Apr 27 11:39:20 vm1 telegraf[49680]: github.com/influxdata/telegraf/agent.panicRecover(0xc8201751d0)
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:96 +0xa9
Apr 27 11:39:20 vm1 telegraf[49680]: panic(0x10241a0, 0xc820010090)
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/runtime/panic.go:426 +0x4e9
Apr 27 11:39:20 vm1 telegraf[49680]: github.com/influxdata/telegraf/plugins/inputs/cassandra.(*Cassandra).Gather(0xc82000d180, 0x7f2bdeea6928, 0xc820166c80, 0x0, 0x0)
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/cassandra/cassandra.go:308 +0xb22
Apr 27 11:39:20 vm1 telegraf[49680]: github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc82063c560, 0xc820048a20, 0xc82017a020, 0x0, 0xc8201751d0)
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:139 +0x42e
Apr 27 11:39:20 vm1 telegraf[49680]: created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:143 +0x442
Apr 27 11:39:20 vm1 telegraf[49680]: goroutine 1 [semacquire]:
Apr 27 11:39:20 vm1 telegraf[49680]: sync.runtime_Semacquire(0xc82063c56c)
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/runtime/sema.go:47 +0x26
Apr 27 11:39:20 vm1 telegraf[49680]: sync.(*WaitGroup).Wait(0xc82063c560)
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/sync/waitgroup.go:127 +0xb4
Apr 27 11:39:20 vm1 telegraf[49680]: github.com/influxdata/telegraf/agent.(*Agent).gatherParallel(0xc82017a020, 0xc820048a20, 0x0, 0x0)
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:150 +0x145
Apr 27 11:39:20 vm1 telegraf[49680]: github.com/influxdata/telegraf/agent.(*Agent).Run(0xc82017a020, 0xc82074c000, 0x0, 0x0)
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:378 +0xa7e
Apr 27 11:39:20 vm1 telegraf[49680]: main.main()
Apr 27 11:39:20 vm1 telegraf[49680]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:269 +0x261c
Apr 27 11:39:20 vm1 telegraf[49680]: goroutine 17 [syscall, locked to thread]:
Apr 27 11:39:20 vm1 telegraf[49680]: runtime.goexit()
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
Apr 27 11:39:20 vm1 telegraf[49680]: goroutine 5 [syscall]:
Apr 27 11:39:20 vm1 telegraf[49680]: os/signal.signal_recv(0x0)
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/runtime/sigqueue.go:116 +0x132
Apr 27 11:39:20 vm1 telegraf[49680]: os/signal.loop()
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
Apr 27 11:39:20 vm1 telegraf[49680]: created by os/signal.init.1
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
Apr 27 11:39:20 vm1 telegraf[49680]: goroutine 87 [syscall]:
Apr 27 11:39:20 vm1 telegraf[49680]: syscall.Syscall(0x0, 0x13, 0xc82092e200, 0x200, 0x7f2bdeff32c0, 0x0, 0x415189)
Apr 27 11:39:20 vm1 telegraf[49680]: /usr/local/go/src/syscall/asm_l
```

curl http://127.0.0.1:8778/jolokia/read/org.apache.cassandra.net:type=FailureDetector/DownEndpointCount
`{"request":{"mbean":"org.apache.cassandra.net:type=FailureDetector","attribute":"DownEndpointCount","type":"read"},"value":0,"timestamp":1461757758,"status":200}`

**Comment by sparrc** [comment]
I can see the issue here, thanks for the report @alekiv, I'll have a fix up soon

**Comment by sparrc** [comment]
PS: does your endpoint work if you specify it as `.metrics` rather than `.net`? If it does then this would workaround the panic.

ie:

```
[[inputs.cassandra]]
  context = "/jolokia/read"
  servers = [":8778"]
  metrics  = [
    "/org.apache.cassandra.metrics:type=FailureDetector/DownEndpointCount"
  ]
```

**Comment by alekiv** [comment]
> PS: does your endpoint work if you specify it as .metrics rather than .net? If it does then this would workaround the panic

Nope, no such attribute under org.apache.cassandra.metrics. It exists under org.apache.cassandra.net  only.

**Comment by subhachandrachandra** [comment]
@alekiv Do have more URLs that query the "org.apache.cassandra.net" hierarchy? I am looking at adding support for those in the cassandra plugin and want to get more examples to verify the code and the format of time series/measurements that will be generated.

**Comment by alekiv** [comment]
@subhachandrachandra 
attaching dump with hierarchy

[cassandra_jmx.zip](https://github.com/influxdata/telegraf/files/255420/cassandra_jmx.zip)
