### ISSUE TITLE
Stackdriver plugin gives SIGSEGV when trying to download metric GAUGE/DISTRIBUTION 

### ISSUE THREAD

**Issue by lpankaz** [influxdata/telegraf#11545]
### Relevant telegraf.conf

```toml
[global_tags]
  plaas_test_id = "$PLAAS_INTERNAL_TEST_ID"
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["$INFLUX_URL"]
  database = "$INFLUX_DB"
  insecure_skip_verify = true
```

### Logs from Telegraf

```text
[root@ania-telegraf-test-3-7vsxz app]# telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ --debug --test
2022-07-22T06:36:46Z I! Starting Telegraf 1.23.2
2022-07-22T06:36:46Z I! Loaded inputs: stackdriver
2022-07-22T06:36:46Z I! Loaded aggregators:
2022-07-22T06:36:46Z I! Loaded processors:
2022-07-22T06:36:46Z W! Outputs are not used in testing mode!
2022-07-22T06:36:46Z I! Tags enabled: host=ania-telegraf-test-3-7vsxz plaas_test_id=$PLAAS_INTERNAL_TEST_ID
2022-07-22T06:36:46Z D! [agent] Initializing plugins
2022-07-22T06:36:46Z D! [agent] Starting service inputs
2022-07-22T06:36:46Z D! [inputs.stackdriver] List metric descriptor request filter: metric.type = starts_with("custom.googleapis.com/avt/oa/avsgen/receiver/handler")
2022-07-22T06:36:46Z D! [inputs.stackdriver] List time series request filter: metric.type = "custom.googleapis.com/avt/oa/avsgen/receiver/handler/count" AND resource.labels.namespace_name = "avs-generator-plab"
2022-07-22T06:36:46Z D! [inputs.stackdriver] List time series request filter: metric.type = "custom.googleapis.com/avt/oa/avsgen/receiver/handler/max" AND resource.labels.namespace_name = "avs-generator-plab"
2022-07-22T06:36:46Z D! [inputs.stackdriver] List time series request filter: metric.type = "custom.googleapis.com/avt/oa/avsgen/receiver/handler" AND resource.labels.namespace_name = "avs-generator-plab"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2dd7b5e]

goroutine 159 [running]:
github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*Stackdriver).addDistribution(0xc000551de0?, 0xc001631b80, 0xc0003a4586?, {0x6?, 0x0?, 0x8d86c20?}, 0x0?, 0x0?)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/stackdriver/stackdriver.go:603 +0x45e
github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*Stackdriver).gatherTimeSeries(0xc000351930, {0x61969c0?, 0xc000088068?}, 0x0?, 0xc00195a030)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/stackdriver/stackdriver.go:538 +0x445
github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*Stackdriver).Gather.func1(0x0?)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/stackdriver/stackdriver.go:232 +0x85
created by github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*Stackdriver).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/stackdriver/stackdriver.go:230 +0x2a5
```

### System info

telegraf-1.23.2-1.x86_64.rpm, Red Hat Enterprise Linux Server release 7.9 (Maipo) x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

1. Try to download data which is currently not available
2.
3.
...

### Expected behavior

When trying to download metrics that are not present - just skip it, same as with different kinds of metrics, do not cause above errors... 

### Actual behavior

My pods ends with OOM when trying to download metrics that are not present.

**Comment by MyaLongmire** [comment]
The config you posted only has agent and output section. Can you please post the input section of your config so we can look into this?

**Comment by sspaink** [comment]
Looks like the offending section is: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/stackdriver/stackdriver.go#L593-L604 

The returned bucket can be `nil` and the code isn't checking for that. Thanks for finding this and reporting it, I can looking into getting a PR up to fix this.

**Comment by lpankaz** [comment]
Input: 
 [[inputs.stackdriver]]
   interval = "1m"
   window = "3m"
   delay = "2m"
   project = "sab-dev-gkeops-93902281"
   metric_type_prefix_include = [
     "custom.googleapis.com/avt/oa/avsgen/receiver"
   ]

[[inputs.stackdriver.filter.resource_labels]]
key = "namespace_name"
value = 'avs-generator-plab'

**Comment by sspaink** [comment]
@lpankaz I've got a potential fix: https://github.com/influxdata/telegraf/pull/11556 
Would it be possible for you to try the artifacts posted by the Tiger Bot to verify if this fixes the issue? Thank you!

**Comment by lpankaz** [comment]
@sspaink I've tried your fixes, and now it is working the way I expected. Thanks!
