### ISSUE TITLE
SNMP plugin w/ multiple hosts: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by Infiniverse** [influxdata/telegraf#1171]
After running telegraf for a very short time, it blows up with a concurrent map write. I don't know how to investigate or fix the problem.

This is with telegraph compiled from git today.

Cheers,
Joe 

```
root@nmgmt-collector:~ # telegraf -config telegraf.conf
2016/05/09 18:57:00 Starting Telegraf (version 0.12.1-100-g36b9e2e)
2016/05/09 18:57:00 Loaded outputs: influxdb
2016/05/09 18:57:00 Loaded inputs: snmp snmp snmp
2016/05/09 18:57:00 Tags enabled: host=nmgmt-collector
2016/05/09 18:57:00 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"nmgmt-collector", Flush Interval:10s 
2016/05/09 18:57:11 Output [influxdb] wrote batch of 1000 metrics in 13.82777ms
2016/05/09 18:57:11 Output [influxdb] wrote batch of 1000 metrics in 12.517915ms
2016/05/09 18:57:12 Output [influxdb] wrote batch of 1000 metrics in 13.233466ms
2016/05/09 18:57:13 Output [influxdb] wrote batch of 1000 metrics in 13.80319ms
2016/05/09 18:57:13 Output [influxdb] wrote batch of 1000 metrics in 15.951499ms
2016/05/09 18:57:14 Output [influxdb] wrote batch of 1000 metrics in 15.834892ms
2016/05/09 18:57:14 Output [influxdb] wrote batch of 1000 metrics in 14.166383ms
2016/05/09 18:57:15 Output [influxdb] wrote batch of 1000 metrics in 13.456209ms
2016/05/09 18:57:15 Gathered metrics, (10s interval), from 3 inputs in 5.665641616s
2016/05/09 18:57:20 Output [influxdb] buffer fullness: 228 / 10000 metrics. Total gathered metrics: 8228. Total dropped metrics: 0.
2016/05/09 18:57:20 Output [influxdb] wrote batch of 228 metrics in 7.614723ms
2016/05/09 18:57:21 Output [influxdb] wrote batch of 1000 metrics in 12.300485ms
2016/05/09 18:57:21 Output [influxdb] wrote batch of 1000 metrics in 13.133648ms
2016/05/09 18:57:22 Output [influxdb] wrote batch of 1000 metrics in 13.782696ms
2016/05/09 18:57:23 Output [influxdb] wrote batch of 1000 metrics in 22.757059ms
2016/05/09 18:57:23 Output [influxdb] wrote batch of 1000 metrics in 19.144338ms
2016/05/09 18:57:24 Output [influxdb] wrote batch of 1000 metrics in 16.538483ms
2016/05/09 18:57:24 Output [influxdb] wrote batch of 1000 metrics in 16.906731ms
2016/05/09 18:57:25 Output [influxdb] wrote batch of 1000 metrics in 13.989847ms
2016/05/09 18:57:25 Gathered metrics, (10s interval), from 3 inputs in 5.674280312s
2016/05/09 18:57:30 Output [influxdb] buffer fullness: 228 / 10000 metrics. Total gathered metrics: 16456. Total dropped metrics: 0.
2016/05/09 18:57:30 Output [influxdb] wrote batch of 228 metrics in 4.416699ms
2016/05/09 18:57:31 Output [influxdb] wrote batch of 1000 metrics in 20.191627ms
2016/05/09 18:57:32 Output [influxdb] wrote batch of 1000 metrics in 13.177843ms
2016/05/09 18:57:32 Output [influxdb] wrote batch of 1000 metrics in 14.379512ms
2016/05/09 18:57:33 Output [influxdb] wrote batch of 1000 metrics in 13.669438ms
2016/05/09 18:57:33 Output [influxdb] wrote batch of 1000 metrics in 13.278676ms
2016/05/09 18:57:34 Output [influxdb] wrote batch of 1000 metrics in 14.78516ms
2016/05/09 18:57:34 Output [influxdb] wrote batch of 1000 metrics in 13.292321ms
2016/05/09 18:57:35 Output [influxdb] wrote batch of 1000 metrics in 12.388117ms
2016/05/09 18:57:35 Gathered metrics, (10s interval), from 3 inputs in 5.617471544s
2016/05/09 18:57:40 Output [influxdb] buffer fullness: 228 / 10000 metrics. Total gathered metrics: 24684. Total dropped metrics: 0.
2016/05/09 18:57:40 Output [influxdb] wrote batch of 228 metrics in 5.015781ms
2016/05/09 18:57:41 Output [influxdb] wrote batch of 1000 metrics in 13.658842ms
2016/05/09 18:57:41 Output [influxdb] wrote batch of 1000 metrics in 14.042139ms
2016/05/09 18:57:42 Output [influxdb] wrote batch of 1000 metrics in 16.217949ms
2016/05/09 18:57:43 Output [influxdb] wrote batch of 1000 metrics in 17.82591ms
2016/05/09 18:57:43 Output [influxdb] wrote batch of 1000 metrics in 14.19146ms
2016/05/09 18:57:44 Output [influxdb] wrote batch of 1000 metrics in 15.540631ms
2016/05/09 18:57:44 Output [influxdb] wrote batch of 1000 metrics in 13.999496ms
2016/05/09 18:57:45 Output [influxdb] wrote batch of 1000 metrics in 15.203205ms
2016/05/09 18:57:45 Gathered metrics, (10s interval), from 3 inputs in 5.678982665s
2016/05/09 18:57:50 Output [influxdb] buffer fullness: 228 / 10000 metrics. Total gathered metrics: 32912. Total dropped metrics: 0.
2016/05/09 18:57:50 Output [influxdb] wrote batch of 228 metrics in 4.493913ms
2016/05/09 18:57:51 Output [influxdb] wrote batch of 1000 metrics in 12.86221ms
2016/05/09 18:57:51 Output [influxdb] wrote batch of 1000 metrics in 14.112632ms
2016/05/09 18:57:52 Output [influxdb] wrote batch of 1000 metrics in 17.385815ms
2016/05/09 18:57:53 Output [influxdb] wrote batch of 1000 metrics in 16.17814ms
2016/05/09 18:57:53 Output [influxdb] wrote batch of 1000 metrics in 14.596582ms
2016/05/09 18:57:54 Output [influxdb] wrote batch of 1000 metrics in 13.680308ms
2016/05/09 18:57:54 Output [influxdb] wrote batch of 1000 metrics in 14.071324ms
2016/05/09 18:57:55 Output [influxdb] wrote batch of 1000 metrics in 19.825736ms
2016/05/09 18:57:55 Gathered metrics, (10s interval), from 3 inputs in 5.687414411s
fatal error: concurrent map writes

goroutine 151 [running]:
runtime.throw(0x12fa790, 0x15)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc820b06e88 sp=0xc820b06e70
runtime.mapassign1(0xe6af60, 0xc8208ee720, 0xc820b07110, 0xc820b07120)
	/usr/local/go/src/runtime/hashmap.go:540 +0x54b fp=0xc820b06f30 sp=0xc820b06e88
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Host).SNMPMap(0xc820b07c78, 0x801cb6110, 0xc820364900, 0xc820150d50, 0xc820b63890, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:528 +0x11d8 fp=0xc820b074c8 sp=0xc820b06f30
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Gather(0xc8201800c0, 0x801cb6110, 0xc820364900, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:400 +0x13f7 fp=0xc820b07e40 sp=0xc820b074c8
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc820d8ed20, 0xc820174fc0, 0xc8204ac030, 0x0, 0xc8201507b0)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:139 +0x42e fp=0xc820b07f68 sp=0xc820b07e40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820b07f70 sp=0xc820b07f68
created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:143 +0x442

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc820d8ed2c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820d8ed20)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel(0xc8204ac030, 0xc820174fc0, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:150 +0x145
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc8204ac030, 0xc820174d80, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:379 +0xa7e
main.main()
	/usr/local/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:270 +0x2632

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 35 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher(0xc8204ac030, 0xc820174d80, 0xc820174fc0, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:278 +0x341
github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0xc8204aa460, 0xc8204ac030, 0xc820174d80, 0xc820174fc0)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:356 +0x7b
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:360 +0x932

goroutine 152 [runnable]:
strings.TrimFunc(0xc820b82e24, 0x4, 0xc820a2d780, 0xc820144ea0, 0xf)
	/usr/local/go/src/strings/strings.go:534
strings.Trim(0xc820b82e24, 0x4, 0x1211360, 0x1, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:593 +0x6e
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Host).SNMPMap(0xc820c79c78, 0x801cb6110, 0xc82021e380, 0xc8205fe030, 0xc8208f3b90, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:528 +0x10e7
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Gather(0xc820180180, 0x801cb6110, 0xc82021e380, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:400 +0x13f7
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc820d8ed20, 0xc820174fc0, 0xc8204ac030, 0x0, 0xc820150810)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:139 +0x42e
created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:143 +0x442

goroutine 31 [select, locked to thread]:
runtime.gopark(0x1478ac8, 0xc82046b728, 0x121e480, 0x6, 0x801c41818, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82046b728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82046b728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x340
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 32 [chan receive]:
main.main.func2(0xc820174de0, 0xc820174d80, 0xc8200f3ea0)
	/usr/local/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:242 +0x47
created by main.main
	/usr/local/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:252 +0x1eff

goroutine 33 [IO wait]:
net.runtime_pollWait(0x801c415c8, 0x72, 0xc82084f000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820a341b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820a341b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820a34150, 0xc82084f000, 0x1000, 0x1000, 0x0, 0x801bf4050, 0xc82000e1e0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8204aca20, 0xc82084f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x801bfc740, 0xc8204aca20, 0xc820144068, 0xc82084f000, 0x1000, 0x1000, 0xc820231020, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8204a8060, 0xc82084f000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8202300c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202300c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820144000)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 50 [select]:
net/http.(*persistConn).writeLoop(0xc820144000)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 153 [IO wait]:
net.runtime_pollWait(0x801c41748, 0x72, 0xc820ae6000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820b324c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820b324c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820b32460, 0xc820ae6000, 0x8000, 0x8000, 0x0, 0x801bf4050, 0xc82000e1e0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200294a0, 0xc820ae6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/soniah/gosnmp.(*GoSNMP).dispatch(0xc820b34300, 0x801c4a5e0, 0xc8200294a0, 0xc8204a79f4, 0x2f, 0x40, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/src/github.com/soniah/gosnmp/marshal.go:1298 +0x2ef
github.com/soniah/gosnmp.(*GoSNMP).sendOneRequest(0xc820b34300, 0xc820ac6c90, 0x1, 0x1, 0xc8204a7650, 0x70, 0x0, 0x0)
	/usr/local/src/github.com/soniah/gosnmp/marshal.go:268 +0xc48
github.com/soniah/gosnmp.(*GoSNMP).send(0xc820b34300, 0xc820ac6c90, 0x1, 0x1, 0xc8204a7650, 0x0, 0x0, 0x0)
	/usr/local/src/github.com/soniah/gosnmp/marshal.go:372 +0x456
github.com/soniah/gosnmp.(*GoSNMP).GetBulk(0xc820b34300, 0xc820b0b140, 0x1, 0x1, 0x1c42000, 0x0, 0x0, 0x0)
	/usr/local/src/github.com/soniah/gosnmp/gosnmp.go:289 +0x3ce
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Host).SNMPMap(0xc820b0bc78, 0x801cb6110, 0xc8203689c0, 0xc8200dc750, 0xc820b29b00, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:479 +0x809
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Gather(0xc820180240, 0x801cb6110, 0xc8203689c0, 0x0, 0x0)
	/usr/local/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:400 +0x13f7
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc820d8ed20, 0xc820174fc0, 0xc8204ac030, 0x0, 0xc820150870)
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:139 +0x42e
created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
	/usr/local/src/github.com/influxdata/telegraf/agent/agent.go:143 +0x442
```

**Comment by SkyRocknRoll** [comment]
@Infiniverse Can you please share your telegraf.conf config file

**Comment by Infiniverse** [comment]
Sure: http://www.josef-k.net/misc/t.conf <http://www.josef-k.net/misc/t.conf>

**Comment by Infiniverse** [comment]
I've cut the number of metrics down (removing the 'ifStdTable' calls) but it still blows up:

```
2016/05/09 19:20:03 Starting Telegraf (version 0.12.1-100-g36b9e2e)
2016/05/09 19:20:03 Loaded outputs: influxdb
2016/05/09 19:20:03 Loaded inputs: snmp snmp snmp
2016/05/09 19:20:03 Tags enabled: host=nmgmt-collector
2016/05/09 19:20:03 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"nmgmt-collector", Flush Interval:10s 
2016/05/09 19:20:10 Output [influxdb] wrote batch of 1000 metrics in 10.490909ms
2016/05/09 19:20:11 Output [influxdb] wrote batch of 1000 metrics in 11.17927ms
2016/05/09 19:20:11 Output [influxdb] wrote batch of 1000 metrics in 11.960284ms
2016/05/09 19:20:12 Gathered metrics, (10s interval), from 3 inputs in 2.257514597s
2016/05/09 19:20:20 Output [influxdb] buffer fullness: 763 / 10000 metrics. Total gathered metrics: 3763. Total dropped metrics: 0.
2016/05/09 19:20:20 Output [influxdb] wrote batch of 763 metrics in 7.356038ms
2016/05/09 19:20:21 Output [influxdb] wrote batch of 1000 metrics in 8.957711ms
2016/05/09 19:20:21 Output [influxdb] wrote batch of 1000 metrics in 9.071583ms
2016/05/09 19:20:22 Output [influxdb] wrote batch of 1000 metrics in 9.164537ms
2016/05/09 19:20:22 Gathered metrics, (10s interval), from 3 inputs in 2.235149488s
fatal error: concurrent map writes
```

**Comment by Infiniverse** [comment]
It's apparently fine if I run it against a single host.

**Comment by sparrc** [comment]
Looks like it's a bug in the snmp code, thanks for the report.

**Comment by Infiniverse** [comment]
Is it that the `OidInstanceMapping` isn't a concurrent map?

**Comment by sparrc** [comment]
that certainly looks to be the issue, I'll be sure to get a fix in for that before the 0.13 release.

**Comment by Infiniverse** [comment]
Is there a quick hack I can try? (Hoping to get something running tomorrow :).

**Comment by sparrc** [comment]
could you give this a try? https://github.com/influxdata/telegraf/pull/1174

**Comment by sparrc** [comment]
Once I get the build passing ;)

**Comment by Infiniverse** [comment]
:). 

It appear to work. I've got 150,000 metrics through it so far, from three devices.

Thanks! :)
