### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by farcaller** [influxdata/telegraf#1182]
```
$ telegraf -version
Telegraf - Version 0.12.1
```

```
2016/05/10 20:57:00 Wrote 50 metrics to output influxdb in 7.171342ms
2016/05/10 20:57:01 Error decoding: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x583e6c]

goroutine 15180 [running]:
panic(0x10241a0, 0xc82000c0d0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/docker.gatherContainerStats(0x0, 0x7f2f938ef700, 0xc820621a80, 0xc8206056e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:238 +0x352c
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainer(0xc8201b78c0, 0xc8206942c0, 0x40, 0xc820694300, 0x1, 0x4, 0xc8206962f8, 0x6, 0xc820059450, 0x47, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:228 +0x963
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather.func1(0xc8206970b0, 0xc8201b78c0, 0x7f2f938ef700, 0xc820621a80, 0xc8206942c0, 0x40, 0xc820694300, 0x1, 0x4, 0xc8206962f8, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:112 +0x9e
created by github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:116 +0x58d
```

Docker was running fine all the time.

**Comment by sparrc** [comment]
will be fixed in 0.13 https://github.com/influxdata/telegraf/issues/1052
