### ISSUE TITLE
[outputs.postgresql] panic: unaligned 64-bit atomic operation on 32-bit ARM

### ISSUE THREAD

**Issue by LeLocTai** [influxdata/telegraf#11853]
### Relevant telegraf.conf

```toml
[[outputs.postgresql]]
```

### Logs from Telegraf

```text
panic: unaligned 64-bit atomic operation
goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0xa600194)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/jackc/pgx/v4/pgxpool.(*Pool).Stat(0xa600150)
        /go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:577 +0x38
github.com/jackc/pgx/v4/pgxpool.(*Pool).checkMinConns(0xa600150)
        /go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:490 +0x1c
github.com/jackc/pgx/v4/pgxpool.ConnectConfig({0x59fdd40, 0xa1000c0}, 0xa080b00)
        /go/pkg/mod/github.com/jackc/pgx/v4@v4.17.0/pgxpool/pool.go:266 +0x34c
github.com/influxdata/telegraf/plugins/outputs/postgresql.(*Postgresql).Connect(0xa566000)
        /go/src/github.com/influxdata/telegraf/plugins/outputs/postgresql/postgresql.go:140 +0x98
github.com/influxdata/telegraf/agent.(*Agent).connectOutput(0xa6fed90, {0x59fdd40, 0xa101a40}, 0xa61e000)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:712 +0x130
github.com/influxdata/telegraf/agent.(*Agent).startOutputs(0xa6fed90, {0x59fdd40, 0xa101a40}, {0xa739f50, 0x3, 0x4})
        /go/src/github.com/influxdata/telegraf/agent/agent.go:695 +0xd0
github.com/influxdata/telegraf/agent.(*Agent).Run(0xa6fed90, {0x59fdd40, 0xa101a40})
        /go/src/github.com/influxdata/telegraf/agent/agent.go:117 +0x1b0
main.(*Telegraf).runAgent(0x9f21500, {0x59fdd40, 0xa101a40})
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:292 +0x14fc
main.(*Telegraf).reloadLoop(0x9f21500)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:113 +0x1fc
main.(*Telegraf).Run(0x9f21500)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf_posix.go:10 +0x58
main.runApp.func1(0xa1cce00)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:213 +0x9f8
github.com/urfave/cli/v2.(*App).RunContext(0xa18b260, {0x59fdd60, 0x9c56070}, {0x9c52060, 0x5, 0x6})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:391 +0xe44
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.runApp({0x9c52060, 0x5, 0x6}, {0x59d52f0, 0x9c0e108}, {0x59ef120, 0x9e65470}, {0x59e80d0, 0x9f21580}, {0x59ef138, ...})
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:344 +0xd90
main.main()
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:351 +0xe8
```

### System info

Telegraf 1.24.1, Raspbian GNU/Linux 10 (buster) 32-bit

### Steps to reproduce

Start telegraf with outputs.postgresql enabled.

### Expected behavior

does not crash

### Actual behavior

crash

**Comment by LeLocTai** [comment]
may relevant https://github.com/jackc/pgx/issues/1288

**Comment by powersj** [comment]
Thanks for the link! I've put up https://github.com/influxdata/telegraf/pull/11858 with an update to the pgx module. In 20-30 minutes there should be comment added by the Tiger Bot with artifacts you can test. If you could grab one and try it out I would greatly appreciate it.

Thanks!

**Comment by LeLocTai** [comment]
It worked! Thanks!
