### ISSUE TITLE
Panic when stopping telegraf ifname processor

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#12145]
### Relevant telegraf.conf

```toml
[[inputs.mock]]

[[processors.ifname]]

[[aggregators.merge]]
```

### Logs from Telegraf

```text
# telegraf --test --config ifname_panic.toml 
2022-11-02T08:54:58Z I! Starting Telegraf 1.24.2
2022-11-02T08:54:58Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-11-02T08:54:58Z I! Loaded inputs: mock
2022-11-02T08:54:58Z I! Loaded aggregators: merge
2022-11-02T08:54:58Z I! Loaded processors: ifname
2022-11-02T08:54:58Z W! Outputs are not used in testing mode!
2022-11-02T08:54:58Z I! Tags enabled: host=dama
panic: close of closed channel

goroutine 66 [running]:
github.com/influxdata/telegraf/plugins/common/parallel.(*Unordered).Stop(0xc001099ce0)
        /go/src/github.com/influxdata/telegraf/plugins/common/parallel/unordered.go:54 +0x25
github.com/influxdata/telegraf/plugins/processors/ifname.(*IfName).Stop(0x0?)
        /go/src/github.com/influxdata/telegraf/plugins/processors/ifname/ifname.go:176 +0x28
github.com/influxdata/telegraf/models.(*RunningProcessor).Stop(...)
        /go/src/github.com/influxdata/telegraf/models/running_processor.go:99
github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1(0xc000f462e8)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:563 +0x186
created by github.com/influxdata/telegraf/agent.(*Agent).runProcessors
        /go/src/github.com/influxdata/telegraf/agent/agent.go:553 +0x3c
```

### System info

Telegraf 1.24.2

### Steps to reproduce

1. Make minimal config with `processors.ifname` and `aggregators.merge`
2. Run test `telegraf --test --config ifname_panic.toml`

### Expected behavior

Telegraf panics "close of closed channel".

### Actual behavior

Normal shutdown of telegraf.

**Comment by powersj** [comment]
I think this has already been fixed:

```
telegraf on  master via 🐹 v1.19.3 
❯ ../telegraf-builds/telegraf-v1.24.2 --config config.toml --test
2022-11-02T12:39:21Z I! Starting Telegraf 1.24.2
2022-11-02T12:39:21Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-11-02T12:39:21Z I! Loaded inputs: mock
2022-11-02T12:39:21Z I! Loaded aggregators: merge
2022-11-02T12:39:21Z I! Loaded processors: ifname
2022-11-02T12:39:21Z W! Outputs are not used in testing mode!
2022-11-02T12:39:21Z I! Tags enabled: host=ryzen
panic: close of closed channel

goroutine 68 [running]:
github.com/influxdata/telegraf/plugins/common/parallel.(*Unordered).Stop(0xc000974000)
	/tmp/build.sh.L47mqn/plugins/common/parallel/unordered.go:54 +0x25
github.com/influxdata/telegraf/plugins/processors/ifname.(*IfName).Stop(0x0?)
	/tmp/build.sh.L47mqn/plugins/processors/ifname/ifname.go:176 +0x28
github.com/influxdata/telegraf/models.(*RunningProcessor).Stop(...)
	/tmp/build.sh.L47mqn/models/running_processor.go:99
github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1(0xc000672738)
	/tmp/build.sh.L47mqn/agent/agent.go:563 +0x186
created by github.com/influxdata/telegraf/agent.(*Agent).runProcessors
	/tmp/build.sh.L47mqn/agent/agent.go:553 +0x3c
telegraf on  master via 🐹 v1.19.3 
❯ ./telegraf --config config.toml --test
2022-11-02T12:39:24Z I! Starting Telegraf 1.25.0-78bbef4d
2022-11-02T12:39:24Z I! Available plugins: 226 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs
2022-11-02T12:39:24Z I! Loaded inputs: mock
2022-11-02T12:39:24Z I! Loaded aggregators: merge
2022-11-02T12:39:24Z I! Loaded processors: ifname
2022-11-02T12:39:24Z W! Outputs are not used in testing mode!
2022-11-02T12:39:24Z I! Tags enabled: host=ryzen
```

**Comment by Hipska** [comment]
Hmm, do you know which PR would have fixed it? And will it be part of 1.24.3?

**Comment by Hipska** [comment]
I could only find #12072 but that mentioned the given bug wasn't released and only seems to be relevant for inputs.

**Comment by powersj** [comment]
Fixed by https://github.com/influxdata/telegraf/pull/12081
