### ISSUE TITLE
panic: interface conversion: interface {} is int64, not float64

### ISSUE THREAD

**Issue by mczimm** [influxdata/telegraf#12155]
### Relevant telegraf.conf

```toml
[agent]
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"

[[outputs.yandex_cloud_monitoring]]
  timeout = "20s"
  endpoint_url = "https://monitoring.some.yandex.net/monitoring/v2/data/write"
  service = "custom"

[[inputs.postgresql]]
  address = "host=localhost port=5432..."
  prepared_statements = true
```

### Logs from Telegraf

```text
./telegraf --config telegraf.conf --debug
2022-11-03T11:31:33Z I! Starting Telegraf 1.25.0-453f36e8
2022-11-03T11:31:33Z I! Available plugins: 5 inputs, 9 aggregators, 26 processors, 21 parsers, 1 outputs
2022-11-03T11:31:33Z I! Loaded inputs: postgresql
2022-11-03T11:31:33Z I! Loaded aggregators:
2022-11-03T11:31:33Z I! Loaded processors:
2022-11-03T11:31:33Z I! Loaded outputs: yandex_cloud_monitoring
2022-11-03T11:31:33Z I! Tags enabled: host=some.yandex.net
2022-11-03T11:31:33Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"some.yandex.net", Flush Interval:10s
2022-11-03T11:31:33Z D! [agent] Initializing plugins
2022-11-03T11:31:33Z D! [agent] Connecting outputs
2022-11-03T11:31:33Z D! [agent] Attempting connection to [outputs.yandex_cloud_monitoring]
2022-11-03T11:31:33Z I! [outputs.yandex_cloud_monitoring] getting folder ID in http://169.254.169.254/computeMetadata/v1/yandex/folder-id
2022-11-03T11:31:33Z I! [outputs.yandex_cloud_monitoring] Writing to Yandex.Cloud Monitoring URL: https://monitoring.some.yandex.net/monitoring/v2/data/write
2022-11-03T11:31:33Z D! [agent] Successfully connected to outputs.yandex_cloud_monitoring
2022-11-03T11:31:33Z D! [agent] Starting service inputs
panic: interface conversion: interface {} is int64, not float64

goroutine 13 [running]:
github.com/influxdata/telegraf/plugins/outputs/yandex_cloud_monitoring.(*YandexCloudMonitoring).Write(0x40c401?, {0xc000316cc0?, 0x6, 0x7cf8e6?})
	/home/mczim/src/telegraf/plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go:131 +0x425
github.com/influxdata/telegraf/models.(*RunningOutput).writeMetrics(0xc000497600, {0xc000316cc0, 0x6, 0x6})
	/home/mczim/src/telegraf/models/running_output.go:244 +0x118
github.com/influxdata/telegraf/models.(*RunningOutput).Write(0xc000497600)
	/home/mczim/src/telegraf/models/running_output.go:201 +0x1aa
github.com/influxdata/telegraf/agent.(*Agent).flushOnce.func1()
	/home/mczim/src/telegraf/agent/agent.go:841 +0x29
created by github.com/influxdata/telegraf/agent.(*Agent).flushOnce
	/home/mczim/src/telegraf/agent/agent.go:840 +0xb3
```

### System info

Telegraf 1.25.0-453f36e8, Ubuntu 18.04

### Steps to reproduce

1. Enable postgresql input
2. Enable yandex_cloud_monitoring output
3. Run telegraf

### Expected behavior

metrics are being written successfully

### Actual behavior

the telegraf has fault

**Comment by powersj** [comment]
Hi,

It looks like we attempt to take the received metrics and generate a [yandexCloudMonitoringMetric](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go#L127-L132). We attempt to take the value and cast to float64 in all cases.

I have put up https://github.com/influxdata/telegraf/pull/12156 with a possible fix. In 20-30mins test artifacts will be attached to that PR. Would you please download and try this again to see if a) the panic still occurs and b) that the values you expect to show up in yandex are there? This attempts to cast the int64 to float64 to try to keep them, but I want to see if they do in fact show up.

Thanks!

**Comment by mczimm** [comment]
Hi, all good now thanks!
