### ISSUE TITLE
test: statsd.TestCachesExpireAfterMaxTTL timed out

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#12341]
### Relevant telegraf.conf

```toml
na
```

### Logs from Telegraf

```text
=== FAIL: plugins/inputs/google_cloud_storage TestRunGatherIterationWithPages (unknown)
2022/12/05 19:02:27 D! [] Fetching key: prefix/1604148850991
2022/12/05 19:02:27 D! [] Fetching key: prefix/1604148850992
2022/12/05 19:02:27 D! [] Fetching key: prefix/1604148850993
2022/12/05 19:02:27 D! [] Fetching key: prefix/1604148850994
2022/12/05 19:02:27 I! [] Iterated all the keys
2022/12/05 19:02:27 I! [] Iterated all the keys
--- PASS: TestRunGatherIterationWithPages (0.06s)

=== FAIL: plugins/inputs/statsd TestCachesExpireAfterMaxTTL (unknown)
coverage: 79.6% of statements
panic: test timed out after 10m0s

goroutine 115 [running]:
testing.(*M).startAlarm.func1()
	C:/Program Files/Go/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	C:/Program Files/Go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000085860, {0xcae176, 0x1b}, 0xce0a58)
	C:/Program Files/Go/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	C:/Program Files/Go/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc000085860, 0xc00026fb68)
	C:/Program Files/Go/src/testing/testing.go:1446 +0x217
testing.runTests(0xc000364be0?, {0x118f7e0, 0x2e, 0x2e}, {0x40?, 0xc00026fc30?, 0x1199680?})
	C:/Program Files/Go/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc000364be0)
	C:/Program Files/Go/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:203 +0x3bd

goroutine 92 [sync.Cond.Wait, 9 minutes]:
sync.runtime_notifyListWait(0xc0000cfa50, 0x0)
	C:/Program Files/Go/src/runtime/sema.go:517 +0x152
sync.(*Cond).Wait(0xc0000cfa40)
	C:/Program Files/Go/src/sync/cond.go:70 +0xa5
github.com/influxdata/telegraf/testutil.(*Accumulator).Wait(0xc00010c070, 0x3)
	C:/Users/circleci.PACKER-633B1A5A/project/testutil/accumulator.go:332 +0x1be
github.com/influxdata/telegraf/plugins/inputs/statsd.TestCachesExpireAfterMaxTTL(0xc000065d40?)
	C:/Users/circleci.PACKER-633B1A5A/project/plugins/inputs/statsd/statsd_test.go:1051 +0x67a
testing.tRunner(0xc000065d40, 0xce0a58)
	C:/Program Files/Go/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1493 +0x75e
```

### System info

master

### Steps to reproduce

1. Run windows tests on CircleCI

### Expected behavior

This test to pass 

### Actual behavior

Test fails inconsistently

**Comment by powersj** [comment]
next steps: re-run PR on CI to see if error no longer reproduces
