### ISSUE TITLE
Docker panic with docker timeout.

### ISSUE THREAD

**Issue by goller** [influxdata/telegraf#1255]
I'm having occasional panics with the docker plugin for telegraf version 0.13.0

```sh
2016/05/24 11:11:30 Error getting docker stats: An error occurred trying to connect: context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x580e8c]

goroutine 270642 [running]:
panic(0xfec120, 0xc820012070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainer(0xc820107800, 0xc8207acf80, 0x40, 0xc8207acfc0, 0x1, 0x4, 0xc8205c18e0, 0x1a, 0xc8207ad000, 0x40, ...)
	/root/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:226 +0xa8c
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather.func1(0xc8205d55c0, 0xc820107800, 0x7f14fd383370, 0xc82083d400, 0xc8207acf80, 0x40, 0xc8207acfc0, 0x1, 0x4, 0xc8205c18e0, ...)
	/root/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:117 +0xa6
created by github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather
	/root/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:122 +0x5fb
```

**Comment by sparrc** [comment]
thx for the report @goller! fixed in 0.13.1 https://github.com/influxdata/telegraf/pull/1195
