### ISSUE TITLE
1.25.1 broke "telegraf --version"

### ISSUE THREAD

**Issue by Hr0bar** [influxdata/telegraf#12573]
Hi, we are doing a custom telegraf build, its pretty much static changes from long time ago, no changes for a looong time, so we simply fetch and merge latest upstream from telegraf. Up until 1.25.1 zero issues, but 1.25.1 it broke due to this Makefile change:

https://github.com/influxdata/telegraf/commit/770a3e994065c80d308eedf3d3fee9adac1e96e8
from
https://github.com/influxdata/telegraf/pull/12375

OLD:
next_version := $(shell cat build_version.txt)

NEW:
next_version := $(file < build_version.txt)

OLD works, the NEW doesnt:

```
[CENSORED]$ ./telegraf --version
panic:  is not in dotted-tri format

goroutine 1 [running]:
github.com/coreos/go-semver/semver.Must(...)
        /go/pkg/mod/github.com/coreos/go-semver@v0.3.0/semver/semver.go:65
github.com/coreos/go-semver/semver.New({0x6bfbfa8?, 0x7fd799f4e958?})
        /go/pkg/mod/github.com/coreos/go-semver@v0.3.0/semver/semver.go:49 +0x45
github.com/influxdata/telegraf/config.NewConfig()
        /config/config.go:135 +0x419
main.main()
        /cmd/telegraf/main.go:390 +0x85
```

when we revert to "shell cat build_version" it works ok:

```
[CENSORED]$ ./telegraf --version
Telegraf 1.25.1-3dc814ae (git: upstream_synced@3dc814ae)
```

**Comment by Hr0bar** [comment]
Some more info about the system and tests showing that make with file function ignores the version string.

```
[CENSORED@CENSORED ~]$ cat build_version.txt
2.2.2
[CENSORED@CENSORED ~]$ cat Makefile

next_version := $(file < build_version.txt)
$(info $$next_version is [${next_version}])
next_version := 1.1.1
$(info $$next_version is [${next_version}])
next_version := $(shell cat build_version.txt)
$(info $$next_version is [${next_version}])

[CENSORED@CENSORED ~]$ make
$next_version is []
$next_version is [1.1.1]
$next_version is [2.2.2]
make: *** No targets.  Stop.
[CENSORED@CENSORED ~]$ make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[CENSORED@CENSORED ~]$ uname -a
Linux CENSORED 3.10.0-1160.81.1.el7.x86_64 #1 SMP Thu Nov 24 12:21:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[CENSORED@CENSORED ~]$

```

On newer system with GNU Make 4.3, the exact same test works as expected.

So this seems like an issue in GNU Make in some prior versions.

**Comment by srebhan** [comment]
@Hr0bar thanks for reporting this issue and for debugging the case. Much appreciated!

We are in a dilemma here as with `$(shell cat build_version.txt)` trying to build on Windows will fail as the command is unknown... However, as you outline we probably should not rely on `file` to support older versions of GNU make. Any idea on how to achieve both, be able to build on Windows and avoid `file`?

@powersj what do you think?

**Comment by powersj** [comment]
@srebhan and I chatted a bit about this today and agree we would like both windows and rhel7 to continue to work. The plan is to look into a windows only build target and revert the change above.

> we are doing a custom telegraf build, its pretty much static changes from long time ago

out of curiosity, are these changes that should be added to telegraf because they are useful? For now, I'd suggest adding a makefile change to your patch set.

**Comment by Hr0bar** [comment]
Thanks for looking into this! Yea we keep the "cat" in our local downstream repo for now.

> out of curiosity, are these changes that should be added to telegraf because they are useful? For now, I'd suggest adding a makefile change to your patch set.

We monitor a globally distributed tacacs/radius authentication service which connects to many downstream AD servers and other factors that can go wrong and make it slow, so we monitor the response time to those requests.
It mostly boils down to importing in go.mod:
	layeh.com/radius
	github.com/nwaples/tacplus

And having custom plugins based on that:
plugins/inputs/radius/radius.go
plugins/inputs/tacacs/tacacs.go

That do the following, Tacacs returns exactly the same:
# Radius Input Plugin

The Radius plugin collects radius response times.

### Configuration:

```toml
[[inputs.radius]]
  ## An array of Server IPs and ports to gather from
  servers = ["127.0.0.1:1812"]

  ## Credentials for radius authentication.
  # username = "myuser"
  # password = "mypassword"
  # secret = "mysecret"

  ## Maximum time to receive response.
  # response_timeout = "5s"
```

### Measurements & Fields:

- radius
  - responsetime (float)

### Tags:

- All measurements have the following tags:
    - port
    - server

### Example Output:

```
radius,port=1812,server=debian-stretch-radius responsetime=0.011 1502489900000000000
```


Thats the reason for custom build, other than that its just convenience stuff that we could live without/do differently, like adding swap percent directly to memory.go input plugin:
![image](https://user-images.githubusercontent.com/6738790/216238801-7bd105f1-9463-4614-a99a-a041c8817862.png)

**Comment by powersj** [comment]
Thanks for the details. Always interesting to see and here what folks are doing with telegarf.

> layeh.com/radius

Hmm, this is MPL 2.0 licensed, which I do not believe is considered permissive. This would probably not work for us upstream.

I appreciate you taking the time to show us! We can leave this open and let Sven or I work on a change to the Makefile to restore rhel 7 usage.

Thanks again!

**Comment by srebhan** [comment]
@powersj we do have a couple of MPL-2.0 dependencies according to `LICENSE_OF_DEPENDENCIES.md` so I think the lib should work!? So @Hr0bar I really would appreciate if you can put up a PR for your code. :-)

**Comment by powersj** [comment]
> we do have a couple of MPL-2.0 dependencies according to LICENSE_OF_DEPENDENCIES.md

Ah when I originally responded I thought I checked that document. Seems I searched for "MPL" and not "mozilla". 

> so I think the lib should work!?

Yep, my bad, would love a PR!

**Comment by Hr0bar** [comment]
Ill try to prepare the PR soonish, have it almost ready, just need to add mandatory tests for it to be accepted & test it after I generalized it a bit (some hardcoded IPs went to config). And triple check if it passes everything from Contributing requirements.

**Comment by srebhan** [comment]
@Hr0bar any news on the PR? Did I miss it somehow?

**Comment by Hr0bar** [comment]
@srebhan No PR yet, prepared at https://github.com/Hr0bar/telegraf 

- need to add tests as they are required by telegraf PRs, but proper test would require temporary running tacacs&radius servers, which may not be trivial. The plugins produce simple fields["responsetime"] which is calculated by telegraf itselft by simple timenow minus timebefore if there is no error response from server (then its equal to timeout), so there is not much point in testing without having test tacacs&radius servers available :/ 

Some additional options would be good to be added, as this is very single purpose, but perhaps that can be left to future feature requests.
Tested that build in our env, works OK. So just the tests are needed.

**Comment by srebhan** [comment]
@Hr0bar you can submit a draft PR and we can discuss the best way forward there!?!?
