### ISSUE TITLE
File descriptor leak in ethtool plugin causing FD exhaustion, system instability

### ISSUE THREAD

**Issue by dokterbob** [influxdata/telegraf#12813]
### Relevant telegraf.conf

```toml
[[inputs.ethtool]]
  interface_include = ["enp7s0"]
```

### Logs from Telegraf

```text
(After ~90 days of gradually increasing open files.)

2023-03-07T11:51:00Z E! [inputs.system] Error in plugin: open /proc/stat: too many open files in system
2023-03-07T11:51:00Z E! [inputs.net] Error in plugin: error getting net io info: open /proc/net/dev: too many open files in system
2023-03-07T11:51:00Z E! [inputs.sensors] Error in plugin: failed to run command /usr/bin/sensors -A -u: open /dev/null: too many open files in system -
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.ethtool] Could not get initial namespace: too many open files in system
2023-03-07T11:51:00Z E! [inputs.ethtool] Error in plugin: too many open files in system
2023-03-07T11:51:00Z E! [inputs.disk] Error in plugin: error getting disk usage info: open /proc/self/mounts: too many open files in system
2023-03-07T11:51:00Z E! [inputs.mdstat] Error in plugin: open /proc/mdstat: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.diskio] Error in plugin: error getting disk io info: open /proc/diskstats: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.kernel] Error in plugin: open /proc/stat: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.netstat] Error in plugin: error getting net connections info: cound not get pid(s), 0: open /proc: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T11:51:00Z E! [inputs.procstat] Error in plugin: open /dev/null: too many open files in system
2023-03-07T15:34:00Z E! [inputs.elasticsearch] Error in plugin: Get "http://localhost:9200/_nodes/_local/name": dial tcp [::1]:9200: connect: connection refused
2023-03-07T15:34:00Z E! [inputs.elasticsearch] Error in plugin: Get "http://localhost:9200/_nodes/stats": dial tcp [::1]:9200: connect: connection refused
2023-03-07T16:53:00Z E! [inputs.procstat] Error in plugin: pipe2: too many open files in system
2023-03-07T16:53:00Z E! [inputs.procstat] Error in plugin: pipe2: too many open files in system
2023-03-07T16:53:00Z E! [inputs.mdstat] Error in plugin: open /proc/mdstat: too many open files in system
2023-03-07T16:53:00Z E! [inputs.procstat] Error in plugin: pipe2: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-networkd-wait-online.service/memory.usage_in_bytes: too many open files>
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-networkd.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-random-seed.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-remount-fs.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-resolved.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-sysctl.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-sysusers.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-timesyncd.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-tmpfiles-setup-dev.service/memory.limit_in_bytes: too many open files i>
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-tmpfiles-setup.service/memory.limit_in_bytes: too many open files in sy>
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-udev-trigger.service/memory.limit_in_bytes: too many open files in syst>
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-udevd.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-update-utmp.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/systemd-user-sessions.service/memory.limit_in_bytes: too many open files in sys>
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/telegraf.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/unattended-upgrades.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.cgroup] Error in plugin: open /sys/fs/cgroup/memory/system.slice/uuidd.service/memory.limit_in_bytes: too many open files in system
2023-03-07T16:53:00Z E! [inputs.procstat] Error in plugin: pipe2: too many open files in system
2023-03-07T16:53:00Z E! [inputs.disk] Error in plugin: error getting disk usage info: open /proc/self/mounts: too many open files in system
2023-03-07T16:53:00Z E! [inputs.procstat] Error in plugin: pipe2: too many open files in system
2023-03-07T16:53:00Z E! [inputs.ethtool] Could not get interfaces in namespace "": route ip+net: netlinkrib: too many open files in system
panic: interface conversion: interface {} is nil, not []ethtool.NamespacedInterface
goroutine 9395631 [running]:
github.com/influxdata/telegraf/plugins/inputs/ethtool.(*NamespaceGoroutine).Interfaces(0xc0005af500)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/namespace_linux.go:55 +0xb9
github.com/influxdata/telegraf/plugins/inputs/ethtool.(*CommandEthtool).Interfaces(0xc000998e40, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/ethtool_linux.go:291 +0x505
github.com/influxdata/telegraf/plugins/inputs/ethtool.(*Ethtool).Gather(0xc0007aa750, {0x6cb41a0?, 0xc00099e520})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/ethtool_linux.go:65 +0x69
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc00012d590, {0x6cb41a0, 0xc00099e520})
        /go/src/github.com/influxdata/telegraf/models/running_input.go:118 +0x5a
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()
        /go/src/github.com/influxdata/telegraf/agent/agent.go:487 +0x2e
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
        /go/src/github.com/influxdata/telegraf/agent/agent.go:486 +0x12a
telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
telegraf.service: Failed with result 'exit-code'.
telegraf.service: Scheduled restart job, restart counter is at 1.
Stopped Telegraf.
```

### System info

Telegraf 1.25.1-1 and 1.25.3-1 from Influx Debian repo, Ubuntu 20.04.5 LTS

### Docker

N/A

### Steps to reproduce

1. Enable ethtool plugin with defaults.
2. Observe gradual increase in open files.
3. System open files get exhausted, system becomes unstable.

### Expected behavior

1. No increase in open files over time.
2. Sensible/reasonable default limits in systemd service preventing system instability.

### Actual behavior

Leaking file descriptors.

### Additional info

![image](https://user-images.githubusercontent.com/22742/223574296-2183bca0-0355-4bf6-b6e4-749b7023240f.png)
![image](https://user-images.githubusercontent.com/22742/223575188-62112d37-503c-462e-a523-626f93e2dc70.png)

```
$ sudo lsof -u telegraf
COMMAND      PID     USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME
telegraf 1471173 telegraf  cwd       DIR                9,2      4096          2 /
telegraf 1471173 telegraf  rtd       DIR                9,2      4096          2 /
telegraf 1471173 telegraf  txt       REG                9,2 160923648  191133877 /usr/bin/telegraf
telegraf 1471173 telegraf  mem       REG                9,2     51856  191104702 /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
telegraf 1471173 telegraf  mem       REG                9,2   2029592  191104875 /usr/lib/x86_64-linux-gnu/libc-2.31.so
telegraf 1471173 telegraf  mem       REG                9,2    157224  191105020 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
telegraf 1471173 telegraf  mem       REG                9,2    191504  191104721 /usr/lib/x86_64-linux-gnu/ld-2.31.so
telegraf 1471173 telegraf    0r      CHR                1,3       0t0          6 /dev/null
telegraf 1471173 telegraf    1u     unix 0xffff8a571de8cc00       0t0 1602553299 type=STREAM
telegraf 1471173 telegraf    2u     unix 0xffff8a571de8cc00       0t0 1602553299 type=STREAM
telegraf 1471173 telegraf    3u     unix 0xffff8a567b9d2400       0t0 1602553300 type=DGRAM
telegraf 1471173 telegraf    4u  a_inode               0,14         0      10547 [eventpoll]
telegraf 1471173 telegraf    5r     FIFO               0,13       0t0 1602551231 pipe
telegraf 1471173 telegraf    6w     FIFO               0,13       0t0 1602551231 pipe
telegraf 1471173 telegraf    7r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf    8r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf    9u     sock                0,9       0t0 1602543527 protocol: UDP
telegraf 1471173 telegraf   10u     IPv4         1602544492       0t0        TCP xxx:syslog-tls (LISTEN)
telegraf 1471173 telegraf   11r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   12r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   13u     IPv6         1609528719       0t0        TCP xxx:54836->xxx:9200 (ESTABLISHED)
telegraf 1471173 telegraf   14r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   15u     IPv4         1605211234       0t0        TCP xxx:58820->hopcroft.dwebsearch.org:5001 (ESTABLISHED)
telegraf 1471173 telegraf   16u     IPv4         1602636906       0t0        TCP xxx:55080->172.16.34.32:8086 (ESTABLISHED)
telegraf 1471173 telegraf   17r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   18r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   19r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   20r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   21r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   22r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   23r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   24r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   25r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   26r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   27r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   28r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   29r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   30r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   31r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   32r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   33r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   34r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   35r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   36r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   37r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   38r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   39r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   40r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   41r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   42r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   43r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   44r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   45r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   46r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   47r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   48r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   49r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   50r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   51r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   52r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   53r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   54r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   55r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   56r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   57r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   58r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   59r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   60r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   61r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   62r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   63r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   64r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   65r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   66r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   67r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   68r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   69r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   70r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   71r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   72r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   73r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   74r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   75r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   76r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   77r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   78r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   79r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   80r      REG                0,4         0 4026531992 net
telegraf 1471173 telegraf   81r      REG                0,4         0 4026531992 net
... (~50k more entries like this)
```

**Comment by powersj** [comment]
Thanks for the report and the details.

I think we are missing a call to `initialNamespace.Close()` in `Interfaces`. Without it, I had the interval set to `1s` and saw `lsof` output grow into the 1000s after a minute. With that call, I see it stay mid-300s and even go down.

I'll look into this a bit more and try to get a PR up tomorrow.

**Comment by dokterbob** [comment]
Thanks @powersj for picking this up so swiftly!

As a workaround, I've disabled ethtool and it seems the issue is gone, for now.

![image](https://user-images.githubusercontent.com/22742/223667879-f0934002-37ed-4128-a4f1-f59874c74179.png)

**Comment by powersj** [comment]
@dokterbob in 20-30mins https://github.com/influxdata/telegraf/pull/12815 will have artifacts attached to it. Could you please download the artifact for your system and confirm that the file descriptors do not increase after a couple of minutes?

Thanks again!

**Comment by dokterbob** [comment]
Hi @powersj, that's amazingly fast! 

I just installed it on one of our machines and will be monitoring throughout the night.

By the way, setting it up I discovered that the leak rate averages at ~1/minute.

![image](https://user-images.githubusercontent.com/22742/223842655-13102840-38e3-4aa5-ad21-34628dbf58ec.png)

**Comment by dokterbob** [comment]
![image](https://user-images.githubusercontent.com/22742/223844880-21b85e42-b2f0-4f86-83c7-f1a6789ded0d.png)

BAM! There you go. No more leaking files! 🙇🏼

**Comment by powersj** [comment]
Thank you for confirming! I'll get this reviewed and landed. It will go out with v1.26.0 on or around Monday, March 13
