### ISSUE TITLE
ethtool plugin panics consistently when probing an ena NIC (regression in v1.26.0)

### ISSUE THREAD

**Issue by kierdavis** [influxdata/telegraf#12866]
### Relevant telegraf.conf

```toml
[global_tags]
  host = "redactedhostname"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "500ms"
  flush_interval = "30s"
  flush_jitter = "30s"
  hostname = "redactedhostname"
  omit_hostname = false

[[outputs.http]]
  url = "redacted"
  data_format = "influx"
  [outputs.http.headers]
    Content-Type = "text/plain"

[[inputs.cpu]]
  totalcpu = true
  percpu = false

[[inputs.cpu]]
  interval = "60s"
  fieldpass = ["usage_active"]
  percpu = true
  report_active = true
  totalcpu = false
  name_suffix = "_details"

[[inputs.disk]]
  ignore_fs = ["gpfs", "fuse", "fuse.sshfs", "tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs", "nfs", "nfs4"]

[[inputs.diskio]]
  skip_serial_number = true
  device_tags = ["DM_LV_NAME", "DM_NAME"]

[[inputs.ethtool]]
  interface_exclude = ["bond*", "br*", "cni*", "docker*", "flannel*", "lxcbr*", "lxdbr*", "tap*", "virbr*"]

[[inputs.mem]]

[[inputs.net]]

[[inputs.swap]]

[[inputs.system]]

[[processors.starlark]]
  namepass = ["diskio"]
  drop_original = true
  script = "/etc/telegraf/non_negative_rate.star"
```

### Logs from Telegraf

```text
Mar 14 13:46:40 redactedhostname systemd[1]: Starting Telegraf...
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Loading config file: /etc/telegraf/telegraf.conf
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Starting Telegraf 1.26.0
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Loaded inputs: cpu (2x) disk diskio ethtool mem net swap system
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Loaded aggregators:
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Loaded processors: starlark
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Loaded secretstores:
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Loaded outputs: http
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! Tags enabled: host=redactedhostname
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"redactedhostname", Flush Interval:30s
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z D! [agent] Initializing plugins
Mar 14 13:46:40 redactedhostname systemd[1]: Started Telegraf.
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z D! [agent] Connecting outputs
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z D! [agent] Attempting connection to [outputs.http]
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z D! [agent] Successfully connected to outputs.http
Mar 14 13:46:40 redactedhostname telegraf[142069]: 2023-03-14T13:46:40Z D! [agent] Starting service inputs
Mar 14 13:46:50 redactedhostname telegraf[142069]: 2023-03-14T13:46:50Z D! [inputs.disk] [SystemPS] => unable to get disk usage ("/sys/kernel/debug/tracing"): permission denied
Mar 14 13:46:50 redactedhostname telegraf[142069]: panic: interface conversion: interface {} is nil, not map[string]uint64
Mar 14 13:46:50 redactedhostname telegraf[142069]: goroutine 58 [running]:
Mar 14 13:46:50 redactedhostname telegraf[142069]: github.com/influxdata/telegraf/plugins/inputs/ethtool.(*NamespaceGoroutine).Get(0xc00127bb80, {{0x2, 0x2329, {0xc00134996c, 0x4}, {0xc000224608, 0x6, 0x478}, 0x33}, {0x70475c0, ...}})
Mar 14 13:46:50 redactedhostname telegraf[142069]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/namespace_linux.go:99 +0x125
Mar 14 13:46:50 redactedhostname telegraf[142069]: github.com/influxdata/telegraf/plugins/inputs/ethtool.(*CommandEthtool).Get(0xc0007bb5d8?, {{0x2, 0x2329, {0xc00134996c, 0x4}, {0xc000224608, 0x6, 0x478}, 0x33}, {0x70475c0, ...}})
Mar 14 13:46:50 redactedhostname telegraf[142069]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/ethtool_linux.go:235 +0x55
Mar 14 13:46:50 redactedhostname telegraf[142069]: github.com/influxdata/telegraf/plugins/inputs/ethtool.(*Ethtool).gatherEthtoolStats(0xc0003ef6c0, {{0x2, 0x2329, {0xc00134996c, 0x4}, {0xc000224608, 0x6, 0x478}, 0x33}, {0x70475c0, ...}}, ...)
Mar 14 13:46:50 redactedhostname telegraf[142069]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/ethtool_linux.go:135 +0x595
Mar 14 13:46:50 redactedhostname telegraf[142069]: github.com/influxdata/telegraf/plugins/inputs/ethtool.(*Ethtool).Gather.func1({{0x2, 0x2329, {0xc00134996c, 0x4}, {0xc000224608, 0x6, 0x478}, 0x33}, {0x70475c0, 0xc00127bb80}})
Mar 14 13:46:50 redactedhostname telegraf[142069]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/ethtool_linux.go:79 +0x58
Mar 14 13:46:50 redactedhostname telegraf[142069]: created by github.com/influxdata/telegraf/plugins/inputs/ethtool.(*Ethtool).Gather
Mar 14 13:46:50 redactedhostname telegraf[142069]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/ethtool_linux.go:78 +0x2a8
Mar 14 13:46:50 redactedhostname systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 14 13:46:50 redactedhostname systemd[1]: telegraf.service: Failed with result 'exit-code'.
Mar 14 13:46:50 redactedhostname systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Mar 14 13:46:50 redactedhostname systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 17.
Mar 14 13:46:50 redactedhostname systemd[1]: Stopped Telegraf.
```

### System info

Telegraf 1.26.0, RHEL 8.6, Linux 4.18.0-372.32.1.el8_6.x86_64

### Steps to reproduce

* Start Telegraf with aforementioned configuration in /etc/telegraf/telegraf.conf
* Wait for the first metric collection interval (10 seconds per my config)

### Expected behavior

Telegraf collects the first batch of metrics without panicking

### Actual behavior

Telegraf panics with the aforementioned backtrace

### Additional info

This appears to be a regression in 1.26.0. We only began seeing this behaviour after upgrading from 1.25.3.

This appears to be specific to systems running on Amazon EC2 VMs. We operate a fleet of identically-configured Linux systems across Amazon EC2, Google Compute Engine and other providers; this behaviour is seen on every EC2-backed system and none of the others. Given that the panic is in the ethtool plugin, it's probably due to a nuance of the kind of NIC present on EC2 VMs, or Linux's driver for it (`ena`).

Given the above conditions (telegraf v1.26.0 on RHEL 8 on an EC2 instance), this crash appears to be reproducible 100% of the time.

**Comment by powersj** [comment]
Hi,

> Mar 14 13:46:50 redactedhostname telegraf[142069]: panic: interface conversion: interface {} is nil, not map[string]uint64
> Mar 14 13:46:50 redactedhostname telegraf[142069]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/ethtool/namespace_linux.go:99 +0x125

I put a check in for nil in PR #12867. That PR will have artifacts that you can test to see if there are additional issues at play. Can you try that out and let me know?

I am a little surprised this did not show up on 1.25.3, given the only changes since then were to close a file and add some additional metrics. It makes me wonder if there is something else at play.

Thanks!

**Comment by powersj** [comment]
> https://github.com/influxdata/telegraf/pull/12867 indeed resolves the panic.

Thanks for confirming

> We don't get that with v1.25.3, though that could be due to v1.26 introducing new features rather than a regression.

I want to confirm you also get metrics from ens5, in addition to the new error message? I believe that is also related to the usage of `ethtool.EthtoolCmd` to gather additional data. Do you also get that error with `ethtool -a ens5`?

I'd rather not be reporting errors if we cannot get some stats, so we may need to suppress that error as well.

**Comment by powersj** [comment]
Hi,

I went and launched a i3en.large with appeared to use the ena driver. Because these additional metrics are extra items that as we have discovered are not reporting on all devices, we should ignore the operation not supported error when trying to get them.

I have updated the PR with this change and tried it out on the instance with success. If you could do the same once new artifacts are posted I would appreciate it.

Thanks again!

**Comment by kierdavis** [comment]
@powersj Yep, looks good. With your additional change 736f028c I get ethtool metrics again. Thanks!
