### ISSUE TITLE
Crash in Tail-Plugin

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13221]
### Relevant telegraf.conf

```toml
[don't have a minimal config yet, sorry]
```

### Logs from Telegraf

```text
Apr 30 08:33:11 thishost telegraf[1283127]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 30 08:33:11 thishost telegraf[1283127]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x36edc55]
Apr 30 08:33:11 thishost telegraf[1283127]: goroutine 75 [running]:
Apr 30 08:33:11 thishost telegraf[1283127]: github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).receiver(0xc000140c80, {0x702cb70, 0xc0004bd220}, 0xc0003d74a0)
Apr 30 08:33:11 thishost telegraf[1283127]: #011/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:341 +0x8f5
Apr 30 08:33:11 thishost telegraf[1283127]: github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles.func2()
Apr 30 08:33:11 thishost telegraf[1283127]: #011/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:233 +0x85
Apr 30 08:33:11 thishost telegraf[1283127]: created by github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles
Apr 30 08:33:11 thishost telegraf[1283127]: #011/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:231 +0x7db
```

### System info

Telegraf 1.26.0-1, RHEL 8.7

### Steps to reproduce

Can't yet reproduce reliably. Happens irregularly but multiple times a day. 
Perhaps the stacktrace is already pointing to a problem?

### Expected behavior

No panics or memory corruption

### Actual behavior

telegraf crashes

**Comment by knollet** [comment]
Probably duplicate of #13078
