### ISSUE TITLE
Cloud PubSub gzip compression decoder error under high load

### ISSUE THREAD

**Issue by dayvar14** [influxdata/telegraf#13236]
### Relevant telegraf.conf

```toml
Output Telegraf Container:
    [[outputs.cloud_pubsub]]
        project = "wp-engine-development"
        topic = "my-topic-id"
        data_format = "influx"
        credentials_file = "/secret/gcp-service-account.json"
        namedrop = ["internal_metrics_*"]
        send_batched = true
        content_encoding = "gzip"

Input Telegraf Container:
    [[inputs.cloud_pubsub]]
        content_encoding = "gzip"
        credentials_file = "/secret/gcp-service-account.json"
        data_format = "influx"
        project = "my-project-id"
        subscription = "my-subscription-id"
```

### Logs from Telegraf

```text
2023-05-02T19:49:16Z I! Loading config: /etc/telegraf/telegraf.conf
2023-05-02T19:49:16Z I! Starting Telegraf 1.27.0-04f26f45
2023-05-02T19:49:16Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-05-02T19:49:16Z I! Loaded inputs: cloud_pubsub internal
2023-05-02T19:49:16Z I! Loaded aggregators: 
2023-05-02T19:49:16Z I! Loaded processors: 
2023-05-02T19:49:16Z I! Loaded secretstores: 
2023-05-02T19:49:16Z I! Loaded outputs: influxdb prometheus_client
2023-05-02T19:49:16Z I! Tags enabled: 
2023-05-02T19:49:16Z I! [agent] Config: Interval:15s, Quiet:false, Hostname:"", Flush Interval:15s
2023-05-02T19:49:16Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
2023-05-02T19:49:16Z I! [inputs.cloud_pubsub] Starting receiver for subscription test-subscription...
2023-05-02T19:49:17Z E! [inputs.cloud_pubsub] Error in plugin: unable to add message from subscription test-subscription: unable to decompress gzip message: flate: corrupt input before offset 75
2023-05-02T19:49:17Z E! [inputs.cloud_pubsub] Error in plugin: unable to add message from subscription test-subscription: unable to decompress gzip message: flate: corrupt input before offset 80
2023-05-02T19:49:17Z E! [inputs.cloud_pubsub] Error in plugin: unable to add message from subscription test-subscription: unable to decompress gzip message: flate: corrupt input before offset 1
2023-05-02T19:49:17Z E! [inputs.cloud_pubsub] Error in plugin: unable to add message from subscription test-subscription: unable to decompress gzip message: flate: corrupt input before offset 1
2023-05-02T19:49:18Z E! [inputs.cloud_pubsub] Error in plugin: unable to add message from subscription test-subscription: unable to decompress gzip message: flate: corrupt input before offset 10855
2023-05-02T19:49:18Z E! [inputs.cloud_pubsub] Error in plugin: unable to add message from subscription test-subscription: unable to decompress gzip message: flate: corrupt input before offset 10855

goroutine 203 [running]:
compress/flate.(*decompressor).Read(0xc00079cc00, {0xc007000000, 0x80000, 0x0?})
        /usr/local/go/src/compress/flate/inflate.go:338 +0x20c
compress/gzip.(*Reader).Read(0xc00094a580, {0xc007000000, 0x80000, 0x80000})
        /usr/local/go/src/compress/gzip/gunzip.go:252 +0xbb
io.(*LimitedReader).Read(0xc007c912c0, {0xc007000000?, 0x0?, 0xc0083adc18?})
        /usr/local/go/src/io/io.go:477 +0x45
bytes.(*Buffer).ReadFrom(0xc000811ec0, {0x6fcf600, 0xc007c912c0})
        /usr/local/go/src/bytes/buffer.go:202 +0x98
io.copyBuffer({0x6fbe780, 0xc000811ec0}, {0x6fcf600, 0xc007c912c0}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:413 +0x14b
io.Copy(...)
        /usr/local/go/src/io/io.go:386
io.CopyN({0x6fbe780, 0xc000811ec0}, {0x6fc1400?, 0xc00094a580}, 0x1f400000)
        /usr/local/go/src/io/io.go:362 +0x9a
github.com/influxdata/telegraf/internal.(*GzipDecoder).Decode(0xc000319f00, {0xc00812e000, 0x8143, 0xa000}, 0x1f400000)
        /go/src/github.com/influxdata/telegraf/internal/content_coding.go:230 +0xdc
github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub.(*PubSub).decompressData(0x0?, {0xc00812e000?, 0xc000216680?, 0x0?})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub/cloud_pubsub.go:219 +0x6f
github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub.(*PubSub).onMessage(0xc00045d680, {0x7024370, 0xc006c8c900}, {0x7031ed0?, 0xc007c70620})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub/cloud_pubsub.go:174 +0xe7
github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub.(*PubSub).startReceiver.func1({0x7024370?, 0xc006c8c900?}, {0x7031ed0?, 0xc007c70620?})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub/cloud_pubsub.go:154 +0x4f
github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub.(*gcpSubscription).Receive.func1({0x7024370, 0xc006c8c900}, 0xc000316ee0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/cloud_pubsub/subscription_gcp.go:42 +0x77
cloud.google.com/go/pubsub.(*Subscription).Receive.func2.2({0x5ae4740?, 0xc000316ee0?})
        /go/pkg/mod/cloud.google.com/go/pubsub@v1.28.0/subscription.go:1184 +0x87
cloud.google.com/go/pubsub/internal/scheduler.(*ReceiveScheduler).Add.func1()
        /go/pkg/mod/cloud.google.com/go/pubsub@v1.28.0/internal/scheduler/receive_scheduler.go:84 +0x2e
created by cloud.google.com/go/pubsub/internal/scheduler.(*ReceiveScheduler).Add
        /go/pkg/mod/cloud.google.com/go/pubsub@v1.28.0/internal/scheduler/receive_scheduler.go:82 +0x352
```

### System info

Telegraf 1.27.0

### Steps to reproduce

1. Create a telegraf instance with an input from a cloud_pubsub subscription.
2. "gzip" compression should be set as the content_encoding in the plugin
3. Output metrics at a rate of at least 3k metrics an hour. 

### Expected behavior

To successfully handle the load of metrics and reduce the amount of messages stuck in the gcp subscription.

### Actual behavior

Telegraf errors out and amount of unacked messages stuck in the gcp subscription rises.

**Comment by dayvar14** [comment]
Created a pr that resolves this issue https://github.com/influxdata/telegraf/pull/13238
