### ISSUE TITLE
EXEC plugin panics on Freebsd  (panic: runtime error: index out of range)

### ISSUE THREAD

**Issue by lunetics** [influxdata/telegraf#1330]
I'm getting a crash with latest master build from src on freebsd 10.3 with the exec plugin:

panic: runtime error: index out of range

 ```
goroutine 28 [running]:
panic(0x10ac8c0, 0xc820010130)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/exec.(*Exec).Gather(0xc8201b6000, 0x801cb6f78, 0xc8200834a0, 0x0, 0x0)
    /root/work/src/github.com/influxdata/telegraf/plugins/inputs/exec/exec.go:181 +0x7b5
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc820012660, 0xc820176660, 0xc8200834a0)
    /root/work/src/github.com/influxdata/telegraf/agent/agent.go:161 +0x73
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
    /root/work/src/github.com/influxdata/telegraf/agent/agent.go:162 +0xe0
 ```

with 13.1 everything works fine. just want that zfs plugin

also tested the config path with:
 ```
    commands = ["/bin/echo"]
```

**Comment by lunetics** [comment]
Just found out adding a space at the end makes the command work. So commands with no parameter give that panic.

not a GO dev  but with not args it shouldn't jump to line 181:

```go
commands, strings.Join([]string{match, cmdAndArgs[1]}, " "))
```

```
   commands = ["/bin/echo "]
```
