### ISSUE TITLE
zfs on freebsd: panic (telegraf 1.0.0b1)

### ISSUE THREAD

**Issue by jbergstroem** [influxdata/telegraf#1355]
I get a panic when enabling the zfs plugin on FreeBSD 10.3:

```
2016/06/10 07:56:48 Starting Telegraf (version )
2016/06/10 07:56:48 Loaded outputs: influxdb
2016/06/10 07:56:48 Loaded inputs: kernel mem processes exec cpu disk system zfs diskio swap
2016/06/10 07:56:48 Tags enabled: host=gut
2016/06/10 07:56:48 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"gut", Flush Interval:10s
panic: runtime error: index out of range

goroutine 82 [running]:
panic(0x10ac8c0, 0xc820010030)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/exec.(*Exec).Gather(0xc8204ce000, 0x803560800, 0xc82006eed0, 0x0, 0x0)
	/wrkdirs/usr/ports/net-mgmt/telegraf/work/telegraf-1.0.0-beta1/src/github.com/influxdata/telegraf/plugins/inputs/exec/exec.go:181 +0x7b5
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc82011a0c0, 0xc820160900, 0xc82006eed0)
	/wrkdirs/usr/ports/net-mgmt/telegraf/work/telegraf-1.0.0-beta1/src/github.com/influxdata/telegraf/agent/agent.go:161 +0x73
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
	/wrkdirs/usr/ports/net-mgmt/telegraf/work/telegraf-1.0.0-beta1/src/github.com/influxdata/telegraf/agent/agent.go:162 +0xe0
```

No specific config; I just uncommented `[inputs.zfs]`.

System info:
- OS: FreeBSD 10.3
- CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (3400.07-MHz K8-class CPU)
- MEMORY: hw.physmem: 34001588224
- Telegraf version: 1.0.0.b1 (installed with pkg install telegraf)
- InfluxDB version: 0.13.1 (installed with pkg install influxdb)
- loaded modules:  cpu processes swap system exec disk diskio kernel mem zfs

Output of `zfs list`:
```
NAME                    USED  AVAIL  REFER  MOUNTPOINT
zroot                  7.04T  8.27T   140K  /zroot
zroot/ROOT             10.6G  8.27T   140K  none
zroot/ROOT/default     10.6G  8.27T  10.6G  /
zroot/influxd          28.0M  8.27T  28.0M  /usr/local/var/influxd
zroot/iohyve           51.8G  8.27T   140K  /iohyve
zroot/iohyve/Firmware   140K  8.27T   140K  /iohyve/Firmware
zroot/iohyve/ISO        241M  8.27T   241M  /iohyve/ISO
zroot/iohyve/g2        51.6G  8.27T   151K  /iohyve/g2
zroot/iohyve/g2/disk0  51.6G  8.32T   192K  -
zroot/mariadb          3.14M  8.27T  3.14M  /var/db/mysql
zroot/media            6.76T  8.27T  6.76T  /zroot/media
zroot/ss               17.2G  8.27T  17.2G  /zroot/ss
zroot/timemachine       150G  8.27T   150G  /zroot/timemachine
zroot/tmp               238K  8.27T   238K  /tmp
zroot/usr              57.3G  8.27T   140K  /usr
zroot/usr/home         57.3G  8.27T  57.3G  /usr/home
zroot/var              23.9M  8.27T   140K  /var
zroot/var/audit         140K  8.27T   140K  /var/audit
zroot/var/crash         140K  8.27T   140K  /var/crash
zroot/var/log          22.9M  8.27T  22.9M  /var/log
zroot/var/mail          186K  8.27T   186K  /var/mail
zroot/var/tmp           453K  8.27T   453K  /var/tmp
```

Btw, should I file these upstream in FreeBSD prior to here seeing how I use a compiled ports version?

Refs #1224.

**Comment by jbergstroem** [comment]
Here's the output of sysctl as well (posted in gist to avoid making this issue too long): https://gist.github.com/jbergstroem/1d77d117b1df5c89837e1de2e0b6b155

**Comment by sparrc** [comment]
@rickard-von-essen see anything obvious?

**Comment by jbergstroem** [comment]
Actually, this is probably my own bad; its coming from the exec plugin which is executing a script I wrote. It worked fine in 0.13 so I need to have a closer look. Apologies for the noise.

**Comment by jbergstroem** [comment]
Here's my output from the command:
```text
cpu,cpu=cpu7 temperature=35.0
cpu,cpu=cpu6 temperature=35.0
cpu,cpu=cpu5 temperature=23.0
cpu,cpu=cpu4 temperature=24.0
cpu,cpu=cpu3 temperature=38.0
cpu,cpu=cpu2 temperature=38.0
cpu,cpu=cpu1 temperature=39.0
cpu,cpu=cpu0 temperature=38.0
cpu frequency=1600
```

I can reproduce the panic every time. Should I create a new issue wrt this?

**Comment by sparrc** [comment]
looks to be the same as #1330, I should have a fix for that soon
