### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by S-Paul** [influxdata/telegraf#14118]
### Relevant telegraf.conf

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
```

### Logs from Telegraf

```text
Oct 16 13:05:54 vs112 telegraf[369890]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 16 13:05:54 vs112 telegraf[369890]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xae4174]
Oct 16 13:05:54 vs112 telegraf[369890]: goroutine 1 [running]:
Oct 16 13:05:54 vs112 telegraf[369890]: github.com/awnumar/memguard/core.Purge.func1(0xc000043c70)
Oct 16 13:05:54 vs112 telegraf[369890]: #011/go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:23 +0x34
Oct 16 13:05:54 vs112 telegraf[369890]: github.com/awnumar/memguard/core.Purge()
Oct 16 13:05:54 vs112 telegraf[369890]: #011/go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:51 +0x1e
Oct 16 13:05:54 vs112 telegraf[369890]: github.com/awnumar/memguard/core.Panic(...)
Oct 16 13:05:54 vs112 telegraf[369890]: #011/go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/exit.go:85
Oct 16 13:05:54 vs112 telegraf[369890]: github.com/awnumar/memguard/core.NewBuffer(0x20)
Oct 16 13:05:54 vs112 telegraf[369890]: #011/go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/buffer.go:73 +0x51c
Oct 16 13:05:54 vs112 telegraf[369890]: github.com/awnumar/memguard/core.NewCoffer()
Oct 16 13:05:54 vs112 telegraf[369890]: #011/go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/coffer.go:30 +0x2d
Oct 16 13:05:54 vs112 telegraf[369890]: github.com/awnumar/memguard/core.init.0()
Oct 16 13:05:54 vs112 telegraf[369890]: #011/go/pkg/mod/github.com/awnumar/memguard@v0.22.3/core/enclave.go:15 +0x29
Oct 16 13:05:54 vs112 systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 16 13:05:54 vs112 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Oct 16 13:05:54 vs112 systemd[1]: Failed to start Telegraf.
```

### System info

Telegraf 1.25 - 1.28, Almalinux 8, x86_64

### Steps to reproduce

1. Install latest telegraf from repo
2. Start telegraf systemd-unit or "telegraf --test -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d"
3. Got error...
...

### Expected behavior

I expect "ok"

### Actual behavior

I got error

### Additional info

Last working telegraf version on AlmaLinux 8 - 1.24.4-1

**Comment by powersj** [comment]
Hi,

The error is coming from the memguard library we use to store secrets. The stack trace can happen when memguard was unable to lock memory. This matches previous issues (e.g. #12502, #12838)

If you are running in a container you may need to add the --capability=CAP_IPC_LOCK.

**Comment by S-Paul** [comment]
Hello.
Thank you for reply. Yes, we use it in systemd-nspawn container. How
can i set those parameter in that case?

Paul.

2023-10-16 22:41 GMT+06:00, Joshua Powers ***@***.***>:

**Comment by powersj** [comment]
What we have seen from users is they add that flag to the nspawn command: https://github.com/awnumar/memguard/issues/144#issuecomment-1360166231

**Comment by S-Paul** [comment]
Thank you!
My inattentionplay bad game with me...

2023-10-17 18:49 GMT+06:00, Joshua Powers ***@***.***>:
