### ISSUE TITLE
[inputs.netflow] panic when decoding uint

### ISSUE THREAD

**Issue by CameronNemo** [influxdata/telegraf#14370]
### Relevant telegraf.conf

```toml
[[inputs.netflow]]
  service_address = "udp://:2055"
  protocol = "ipfix"
  dump_packets = true
```

### Logs from Telegraf

```text
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: 2023-11-30T17:32:01Z D! [inputs.netflow] raw data: 000a0122000000000000000000000000000200840100000f000100040002000400030004000a0002000e00020010000400110004003d00010004000100070002000b0002009600000097000000080004000c00040101000f000100040002000400030004000a0002000e00020010000400110004003d00010004000100070002000b00020096000000970000001b0010001c00100100003c000001000000000100000001006500c90000ffff00000868000601bbc41a000000006568c711000000006568c711c0a80101c0a8fe01000001010054000001000000000100000001006500c90000ffff00000868000601bbc41a000000006568c711000000006568c71120010db800000001000000000000000120010db80000000200000000000000010000
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: panic: invalid length for uint buffer []
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: goroutine 25 [running]:
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: github.com/influxdata/telegraf/plugins/inputs/netflow.decodeUint({0xc001ec20b6?, 0xc000f0e4b0?, 0xc000df9628?})
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/netflow/type_conversion.go:101 +0xee
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: github.com/influxdata/telegraf/plugins/inputs/netflow.(*netflowDecoder).decodeValueIPFIX(0xc002662000, {0x0, 0x96, 0x0, {0x66140e0, 0xc001fde3f0}})
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/netflow/netflow_decoder.go:737 +0xa58
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: github.com/influxdata/telegraf/plugins/inputs/netflow.(*netflowDecoder).Decode(0xc002662000, {0xc001cfc3e0, 0x10, 0x10}, {0xc001ec2000, 0x124, 0x10000})
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/netflow/netflow_decoder.go:610 +0xea5
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: github.com/influxdata/telegraf/plugins/inputs/netflow.(*NetFlow).read(0xc001969800, {0x860ede0, 0xc000fc81c0})
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/netflow/netflow.go:141 +0x1d3
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: github.com/influxdata/telegraf/plugins/inputs/netflow.(*NetFlow).Start.func1()
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/netflow/netflow.go:111 +0x57
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]: created by github.com/influxdata/telegraf/plugins/inputs/netflow.(*NetFlow).Start in goroutine 1
Nov 30 09:32:01 ipfix-dev-1.lab.svl.cenic.org telegraf[39044]:         /go/src/github.com/influxdata/telegraf/plugins/inputs/netflow/netflow.go:109 +0x26b
```

### System info

Rocky 8

### Steps to reproduce

1. Send IPFIX packet
2. Observe crash

### Expected behavior

No crash, even if decoding fails

### Actual behavior

Panics

### Additional info

I have a pcap but MSFT won't let me share it with you via this platform 🤷🏼 .

This is the packet according to [scapy](https://scapy.readthedocs.io/en/latest/api/scapy.layers.netflow.html#module-scapy.layers.netflow):

```
###[ IP ]### 
  version   = 4
  ihl       = None
  tos       = 0x0
  len       = None
  id        = 1
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = udp
  chksum    = None
  src       = 127.0.0.1
  dst       = 127.0.0.1
  \options   \
###[ UDP ]### 
     sport     = safetynetp
     dport     = iop
     len       = None
     chksum    = None
###[ Netflow Header ]### 
        version   = 10
###[ IPFix (Netflow V10) Header ]### 
           length    = None
           ExportTime= Thu, 01 Jan 1970 00:00:00 +0000 (0)
           flowSequence= 0
           ObservationDomainID= 0
###[ Netflow FlowSet V9/10 ]### 
              flowSetID = 2
              length    = None
              \templates \
               |###[ Netflow Flowset Template V9/10 ]### 
               |  templateID= 256
               |  fieldCount= 15
               |  \template_fields\
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IN_BYTES
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IN_PKTS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = FLOWS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = INPUT_SNMP
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = OUTPUT_SNMP
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = SRC_AS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = DST_AS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = DIRECTION
               |   |  fieldLength= 1
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = PROTOCOL
               |   |  fieldLength= 1
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = L4_SRC_PORT
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = L4_DST_PORT
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = flowStartSeconds
               |   |  fieldLength= None
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = flowEndSeconds
               |   |  fieldLength= None
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IPV4_SRC_ADDR
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IPV4_DST_ADDR
               |   |  fieldLength= 4
               |###[ Netflow Flowset Template V9/10 ]### 
               |  templateID= 257
               |  fieldCount= 15
               |  \template_fields\
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IN_BYTES
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IN_PKTS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = FLOWS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = INPUT_SNMP
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = OUTPUT_SNMP
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = SRC_AS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = DST_AS
               |   |  fieldLength= 4
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = DIRECTION
               |   |  fieldLength= 1
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = PROTOCOL
               |   |  fieldLength= 1
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = L4_SRC_PORT
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = L4_DST_PORT
               |   |  fieldLength= 2
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = flowStartSeconds
               |   |  fieldLength= None
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = flowEndSeconds
               |   |  fieldLength= None
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IPV6_SRC_ADDR
               |   |  fieldLength= 16
               |   |###[ Netflow Flowset Template Field V9/10 ]### 
               |   |  enterpriseBit= 0
               |   |  fieldType = IPV6_DST_ADDR
               |   |  fieldLength= 16
###[ Netflow DataFlowSet V9/10 ]### 
                 templateID= 256
                 length    = None
                 \records   \
                  |###[ Netflow DataFlowset Record V9/10 ]### 
                  |  IN_BYTES  = b'\x00\x00\x01\x00'
                  |  IN_PKTS   = b'\x00\x00\x00\x01'
                  |  FLOWS     = b'\x00\x00\x00\x01'
                  |  INPUT_SNMP= b'\x00e'
                  |  OUTPUT_SNMP= b'\x00\xc9'
                  |  SRC_AS    = 65535
                  |  DST_AS    = 2152
                  |  DIRECTION = Ingress flow
                  |  PROTOCOL  = tcp
                  |  L4_SRC_PORT= 443
                  |  L4_DST_PORT= 50202
                  |  flowStartSeconds= Thu, 30 Nov 2023 17:38:24 +0000 (1701365904)
                  |  flowEndSeconds= Thu, 30 Nov 2023 17:38:24 +0000 (1701365904)
                  |  IPV4_SRC_ADDR= 192.168.1.1
                  |  IPV4_DST_ADDR= 192.168.254.1
###[ Netflow DataFlowSet V9/10 ]### 
                    templateID= 257
                    length    = None
                    \records   \
                     |###[ Netflow DataFlowset Record V9/10 ]### 
                     |  IN_BYTES  = b'\x00\x00\x01\x00'
                     |  IN_PKTS   = b'\x00\x00\x00\x01'
                     |  FLOWS     = b'\x00\x00\x00\x01'
                     |  INPUT_SNMP= b'\x00e'
                     |  OUTPUT_SNMP= b'\x00\xc9'
                     |  SRC_AS    = 65535
                     |  DST_AS    = 2152
                     |  DIRECTION = Ingress flow
                     |  PROTOCOL  = tcp
                     |  L4_SRC_PORT= 443
                     |  L4_DST_PORT= 50202
                     |  flowStartSeconds= Thu, 30 Nov 2023 17:38:24 +0000 (1701365904)
                     |  flowEndSeconds= Thu, 30 Nov 2023 17:38:24 +0000 (1701365904)
                     |  IPV6_SRC_ADDR= 2001:db8:0:1::1
                     |  IPV6_DST_ADDR= 2001:db8:0:2::1
```

And the program used to generate the packet:

```
import argparse
import datetime

from scapy.config import conf
from scapy.layers import inet, netflow
from scapy.sendrecv import send
from scapy.supersocket import L3RawSocket

_COMMON_TEMPLATE_FIELDS = [
    netflow.NetflowTemplateFieldV9(fieldType="IN_BYTES"),
    netflow.NetflowTemplateFieldV9(fieldType="IN_PKTS"),
    netflow.NetflowTemplateFieldV9(fieldType="FLOWS"),
    netflow.NetflowTemplateFieldV9(fieldType="INPUT_SNMP"),
    netflow.NetflowTemplateFieldV9(fieldType="OUTPUT_SNMP"),
    netflow.NetflowTemplateFieldV9(fieldType="SRC_AS", fieldLength=4),
    netflow.NetflowTemplateFieldV9(fieldType="DST_AS", fieldLength=4),
    netflow.NetflowTemplateFieldV9(fieldType="DIRECTION"),
    netflow.NetflowTemplateFieldV9(fieldType="PROTOCOL"),
    netflow.NetflowTemplateFieldV9(fieldType="L4_SRC_PORT"),
    netflow.NetflowTemplateFieldV9(fieldType="L4_DST_PORT"),
    netflow.NetflowTemplateFieldV9(fieldType="flowStartSeconds"),
    netflow.NetflowTemplateFieldV9(fieldType="flowEndSeconds"),
]

_V4_TEMPLATE_FIELDS = [
    *_COMMON_TEMPLATE_FIELDS,
    netflow.NetflowTemplateFieldV9(fieldType="IPV4_SRC_ADDR"),
    netflow.NetflowTemplateFieldV9(fieldType="IPV4_DST_ADDR"),
]
_V6_TEMPLATE_FIELDS = [
    *_COMMON_TEMPLATE_FIELDS,
    netflow.NetflowTemplateFieldV9(fieldType="IPV6_SRC_ADDR"),
    netflow.NetflowTemplateFieldV9(fieldType="IPV6_DST_ADDR"),
]


def _common_fields() -> dict:
    now = datetime.datetime.now(datetime.timezone.utc)
    now_secs = int(now.timestamp())
    return {
        "IN_BYTES": b"\x00\x00\x01\x00",
        "IN_PKTS": b"\x00\x00\x00\x01",
        "FLOWS": b"\x00\x00\x00\x01",
        "DIRECTION": 0,
        "INPUT_SNMP": b"\x00\x65",
        "OUTPUT_SNMP": b"\x00\xc9",
        "SRC_AS": 0xffff,
        "DST_AS": 0x0868,
        "PROTOCOL": 0x06,
        "L4_SRC_PORT": 0x01bb,
        "L4_DST_PORT": 0xc41a,
        "flowStartSeconds": now_secs,
        "flowEndSeconds": now_secs,
    }


def _ipfix_packet():
    header = inet.IP() / inet.UDP(sport=40000, dport=2055)
    netflow_header = netflow.NetflowHeader() / netflow.NetflowHeaderV10()

    flowset = netflow.NetflowFlowsetV9(
        templates=[
            netflow.NetflowTemplateV9(
                templateID=256,
                fieldCount=len(_V4_TEMPLATE_FIELDS),
                template_fields=_V4_TEMPLATE_FIELDS,
            ),
            netflow.NetflowTemplateV9(
                templateID=257,
                fieldCount=len(_V6_TEMPLATE_FIELDS),
                template_fields=_V6_TEMPLATE_FIELDS,
            ),
        ],
        flowSetID=2,
    )
    class4 = netflow.GetNetflowRecordV9(flowset, 256)
    class6 = netflow.GetNetflowRecordV9(flowset, 257)
    fields4 = {
        "IPV4_SRC_ADDR": b"192.168.1.1",
        "IPV4_DST_ADDR": b"192.168.254.1",
    }
    fields6 = {
        "IPV6_SRC_ADDR": b"2001:db8:0:1::1",
        "IPV6_DST_ADDR": b"2001:db8:0:2::1",
    }
    data_flowset4 = netflow.NetflowDataflowsetV9(
        templateID=256,
        records=[
            class4(**_common_fields(), **fields4),
        ],
    )
    data_flowset6 = netflow.NetflowDataflowsetV9(
        templateID=257,
        records=[
            class6(**_common_fields(), **fields6),
        ],
    )
    return header / netflow_header / flowset / data_flowset4 / data_flowset6


def _config(args):
    conf.iface = args.iface

    # "On Linux, in order to speak to local IPv4 applications,
    #  you need to build your packets one layer upper,
    #  using a PF_INET/SOCK_RAW socket instead of a PF_PACKET/SOCK_RAW"
    # <https://scapy.readthedocs.io/en/latest/troubleshooting.html>
    if args.iface == "lo":
        conf.L3socket = L3RawSocket


def _parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--iface", default="lo", help="Send packets on this interface")
    parser.add_argument(
        "--show", action="store_true", help="Show packet")
    parser.add_argument(
        "--send", action="store_true", help="Send packet")
    return parser.parse_args()


def _main():
    args = _parse_args()
    # set scapy configuration *before* creating packet(s)
    _config(args)
    packet = _ipfix_packet()

    if args.show:
        packet.show()
        print(packet.route())

    if args.send:
        send(packet, iface=args.iface)


if __name__ == '__main__':
    _main()
```

**Comment by srebhan** [comment]
@CameronNemo your device is not the only one sending malformed data, so I decided to do something about it. :-) Please test the binary in PR #14373 available once CI finished all tests. Let me know if this fixes your issue!

In case you do see more issues, please report them together `raw data:` log-line!
