### ISSUE TITLE
Add vsphere virtual machine power state metric/label

### ISSUE THREAD

**Issue by imperatives** [influxdata/telegraf#14677]
### Use Case

When we are asked for a total count of virtual machines the resulting number doesn't include virtual machines that are not currently powered on.  This causes some confusion when the counts differ from what is presented in the main vsphere overview screen.  Additionally, we are often asked to generate counts of the number of virtual machines that are currently in a poweredOff or suspended state.  While adding an additional label to all vm metrics may not be reasonable.  The creation of a single metric that will allow for the count of vm's by state would be beneficial. 

- [ ] #

### Expected behavior

When querying the new metric vsphere_vm_state a standard set of bounded label values like clustername, dcname, esxhostname, guest, guesthostname, rpname, source, vmname, and vcenter should be included so that counts can be performed against these dimensions (e.g., how many rhel7 hosts are powered down).  The vsphere_vm_state metric value could numerical define the state such a 0 = poweredOn, 1 = poweredOff, 2 = suspended.  Alternatively, the PowerState data could be included into an existing vm metric as a label value if that doesn't add too much complexity and cardinality.

### Actual behavior

If we wanted to count the number of powered off virtual machines running on the esxi host named `esxhostanme01` we could perform a Prometheus query like:
`count(count by (guesthostname) (vsphere_vm_state{esxhostname="<esxhostanme01>"}==1))`. 

### Additional info

A similar issue was raised up here: https://github.com/influxdata/telegraf/issues/10438 and https://github.com/influxdata/telegraf/issues/5993. It appears that vm's with states other than poweredOn are being filtered out from the metrics.

**Comment by powersj** [comment]
Hi,

> It appears that vm's with states other than poweredOn are being filtered out from the metrics.

If you look at those previous issues then you will find this comment:

> This is prior to the collection is being scrubbed for powered down VMs.

Meaning, that the power downed VMs are filtered either by VSphere or govmomi before telegraf even gets any data. As such it is not clear what telegraf can even do about this.

**Comment by imperatives** [comment]
Oh, ok.  I misinterpreted the comment and thought that the scrubbing was being performed by the telegraf vsphere plugin.  I'll open up a request in the govmomi project. Thanks!

**Comment by powersj** [comment]
> It appears like the powerstate is being collected and evaluated in this conditional:

ha! this is what I get for reading those prior issues and not looking at the code ;)

I do not have access to any vsphere systems, so if I put up a PR removing this would you be willing to give it a try? It is possible that we may not have all the same info since the VM is off.

**Comment by imperatives** [comment]
No worries.

Yes, I'd be glad to test out the PR! Thanks!

**Comment by powersj** [comment]
I put up https://github.com/influxdata/telegraf/pull/14683 which should have artifacts in the next 20-30mins. If you could provide the logs that would be helpful.

Thanks!

**Comment by imperatives** [comment]
Will do.  Thanks!

**Comment by imperatives** [comment]
It is failing on startup...
```
2024-02-05T18:38:52Z I! [inputs.vsphere] Starting plugin
power state for "<testhost01>": poweredOn
power state for "<testhost02>": poweredOn
power state for "": poweredOff
power state for "<testhost04>": poweredOn
power state for "": poweredOff
power state for "<testhost06>": poweredOn
power state for "<testhost07>": poweredOn
power state for "<testhost08>": poweredOn
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x408b266]

goroutine 1 [running]:
github.com/influxdata/telegraf/plugins/inputs/vsphere.getVMs({0x8a87c80, 0xc0023bbf10}, 0xc0018c7380, 0xc002b50410)
    /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:797 +0x466
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*Endpoint).discover(0xc0018c7380, {0x8a87c10, 0xc0018ab4a0})
    /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:487 +0x6f0
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*Endpoint).initalDiscovery(0xc0018c7380, {0x8a87c10, 0xc0018ab4a0})
    /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:315 +0x26
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*Endpoint).init(0xc0018c7380, {0x8a87c10, 0xc0018ab4a0})
    /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:350 +0x28f
github.com/influxdata/telegraf/plugins/inputs/vsphere.NewEndpoint({0x8a87c10, 0xc0018ab4a0}, 0xc0023fc000, 0xc000422f30, {0x8aafa18?, 0xc0023cf950?})
    /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/endpoint.go:261 +0x18fd
github.com/influxdata/telegraf/plugins/inputs/vsphere.(*VSphere).Start(0xc0023fc000, {0x8a2d9e8?, 0xc0023fc000?})
    /go/src/github.com/influxdata/telegraf/plugins/inputs/vsphere/vsphere.go:106 +0x191
github.com/influxdata/telegraf/agent.(*Agent).startInputs(0xc0003a4150?, 0xc001927740, {0xc0023de298, 0x1, 0x1?})
    /go/src/github.com/influxdata/telegraf/agent/agent.go:358 +0x20a
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc001e335a0, {0x8a87c10?, 0xc002271860})
    /go/src/github.com/influxdata/telegraf/agent/agent.go:157 +0x69c
main.(*Telegraf).runAgent(0xc0023d0140, {0x8a87c10, 0xc002271860}, 0x10?, 0xc0?)
    /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:386 +0x1730
main.(*Telegraf).reloadLoop(0xc0023d0140)
    /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:173 +0x25b
main.(*Telegraf).Run(0x0?)
    /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf_posix.go:14 +0x52
main.runApp.func1(0xc00239af40)
    /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:249 +0xbf0
github.com/urfave/cli/v2.(*Command).Run(0xc0023d7080, 0xc00239af40, {0xc0000b4100, 0x1, 0x1})
    /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x998
github.com/urfave/cli/v2.(*App).RunContext(0xc000468f00, {0x8a87a18?, 0xdfdb600}, {0xc0000b4100, 0x1, 0x1})
    /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x5b7
github.com/urfave/cli/v2.(*App).Run(...)
    /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.runApp({0xc0000b4100, 0x1, 0x1}, {0x8a0ade0?, 0xc0000d6048}, {0x8a291a0?, 0xc001ec3ec8}, {0x8a291c8?, 0xc002389a20}, {0x8a87900, ...})
    /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:376 +0x10d3
main.main()
    /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:386 +0xed
```

**Comment by powersj** [comment]
Hi,

Sorry for the delay. Unfortunately, this is what I was expecting. This code is run during the initial discovery of resources. The previous behavior was ensuring that a VM was powered on otherwise some information is nil.

You can already see this in the debug info I was printing, in that we don't even know the hostname:

> power state for "": poweredOff

As such, I am not sure we would even want to continue pursuing this as we don't appear to have any data for the VM anyway.

**Comment by imperatives** [comment]
Although there is no additional vm data.  The simple correlation of vm guesthostname and power state would be valuable.  Do you see anyway forward to capture those two dimensions into a metric given the failure during the initial discovery?  (e.g., vsphere_vm_power_state{guesthostname="< guesthostname>",state="poweredoff" })?

**Comment by powersj** [comment]
Unfortunately, I do not. This does confirm why we are checking for the power state today. I am going to close this for now, but if someone comes up with a way to gather additional data we can reopen this.

**Comment by simonwhybrow-cbre** [comment]
We had the same requirement so that we could see all VMs on each guest.
I ended up collecting this via an exec command running a simple powershell script to collect some vm details including the powerstate. This requires the vmware.powercli module to be installed/configured.
At it's most basic:

```powershell
Connect-VIServer -Server xxxxxxx -User xxxxxx -Password "xxxxxx" -Force | out-null

$vms = Get-VM | select-object "name", "VMHost", "powerstate", "NumCPU"

foreach ($vm in $vms)
{
    Write-Host "vsphere_vm_details,vmname=$($vm.name),vmhost=$($vm.vmhost),vmpowerstate=$($vm.powerstate) numcpu=$($vm.NumCPU)"
}
```

**Comment by baguilartech** [comment]
Was able to add a collection script with govc, maybe someone can add it to the native input plugin:

```
[[inputs.exec]]
commands = ["/scripts/collect-inventory.sh"]
timeout = "4m"
interval = "5m"
data_format = "influx"
[inputs.exec.tags]
  collection_type = "inventory"
  vcenter_name = "{{ vcenter_name }}"
```
           
```
#!/bin/sh
# Collect VM inventory using govc
export GOVC_URL="https://vcenter.DOMAIN.com/sdk"
export GOVC_USERNAME="{ vcenter_username }"
export GOVC_PASSWORD="${vcenter_password}"
export GOVC_INSECURE=true

# Get VM counts (excluding templates)
total_all=$(govc find / -type m 2>/dev/null | wc -l)
templates=$(govc find / -type m -config.template true 2>/dev/null | wc -l)
total_vms=$((total_all - templates))

# Get powered on/off counts (templates are never powered on)
powered_on=$(govc find / -type m -runtime.powerState poweredOn 2>/dev/null | wc -l)
powered_off=$((total_vms - powered_on))

echo "vsphere_inventory_summary,vcenter={{ vcenter_name }} total_vms=${total_vms}i,powered_on=${powered_on}i,powered_off=${powered_off}i,templates=${templates}i,total_objects=${total_all}i"
```

**Comment by tguenneguez** [comment]
View https://github.com/influxdata/telegraf/pull/19161
