### ISSUE TITLE
inputs.ecs panicked Fargate

### ISSUE THREAD

**Issue by philiptrovato** [influxdata/telegraf#15455]
### Relevant telegraf.conf

```toml
[agent]
  debug = true
  interval = 15

[[inputs.ecs]]
  timeout = "5s"
  #endpoint_url = "http://169.254.170.2"

[[inputs.disk]]
  
[[outputs.prometheus_client]]
  listen = "0.0.0.0:38073"
  metric_version = 2
```

### Logs from Telegraf

```text
20 minutes ago	2024-06-03T20:03:15Z E! FATAL: [inputs.ecs] panicked: runtime error: invalid memory address or nil pointer dereference, Stack:	telegraf
20 minutes ago	goroutine 39 [running]:	telegraf
20 minutes ago	github.com/influxdata/telegraf/agent.panicRecover(0xc0019c5a40)	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/agent/agent.go:1199 +0x70	telegraf
20 minutes ago	panic({0x70a8180?, 0xdc68f90?})	telegraf
20 minutes ago	/usr/local/go/src/runtime/panic.go:770 +0x132	telegraf
20 minutes ago	github.com/influxdata/telegraf/plugins/inputs/ecs.mergeTaskStats(0xc00141d130, 0xc001cc49c0)	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/plugins/inputs/ecs/types.go:76 +0xc1	telegraf
20 minutes ago	github.com/influxdata/telegraf/plugins/inputs/ecs.(*Ecs).Gather(0xc001ab3000, {0x8d11b40, 0xc001354740})	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/plugins/inputs/ecs/ecs.go:69 +0x5a	telegraf
20 minutes ago	github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc0019c5a40, {0x8d11b40, 0xc001354740})	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/models/running_input.go:149 +0x54	telegraf
20 minutes ago	github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/agent/agent.go:583 +0x5e	telegraf
20 minutes ago	created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce in goroutine 34	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/agent/agent.go:581 +0xf7	telegraf
20 minutes ago	goroutine 1 [semacquire]:	telegraf
20 minutes ago	sync.runtime_Semacquire(0xc001cd8230?)	telegraf
20 minutes ago	/usr/local/go/src/runtime/sema.go:62 +0x25	telegraf
20 minutes ago	sync.(*WaitGroup).Wait(0xc0001ae0b0?)	telegraf
20 minutes ago	/usr/local/go/src/sync/waitgroup.go:116 +0x48	telegraf
20 minutes ago	github.com/influxdata/telegraf/agent.(*Agent).Run(0xc0001ae0b0, {0x8cdbd10, 0xc0014b44b0})	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/agent/agent.go:197 +0xa2c	telegraf
20 minutes ago	main.(*Telegraf).runAgent(0xc001b0fa40, {0x8cdbd10, 0xc0014b44b0}, 0x7fe7df0a55b8?, 0x10?)	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:386 +0x176c	telegraf
20 minutes ago	main.(*Telegraf).reloadLoop(0xc001b0fa40)	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:173 +0x24c	telegraf
20 minutes ago	main.(*Telegraf).Run(0xc001b0fa40)	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf_posix.go:14 +0x52	telegraf
20 minutes ago	main.runApp.func1(0xc001917dc0)	telegraf
20 minutes ago	/go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:249 +0xc90	telegraf
20 minutes ago	github.com/urfave/cli/v2.(*Command).Run(0xc0014c0160, 0xc001917dc0, {0xc0001ac050, 0x1, 0x1})	telegraf
20 minutes ago	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:27	telegraf
20 minutes ago	2024-06-03T20:03:15Z E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new/choose	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Loaded processors:	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Loaded secretstores:	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Loaded outputs: prometheus_client	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Tags enabled: host=ip-XXXXXXXXX.ec2.internal	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! [agent] Config: Interval:15s, Quiet:false, Hostname:"ip-XXXXXXXXX.ec2.internal", Flush Interval:10s	telegraf
20 minutes ago	2024-06-03T20:03:08Z D! [agent] Initializing plugins	telegraf
20 minutes ago	2024-06-03T20:03:08Z D! [agent] Connecting outputs	telegraf
20 minutes ago	2024-06-03T20:03:08Z D! [agent] Attempting connection to [outputs.prometheus_client]	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! [outputs.prometheus_client] Listening on http://[::]:38073/metrics	telegraf
20 minutes ago	2024-06-03T20:03:08Z D! [agent] Successfully connected to outputs.prometheus_client	telegraf
20 minutes ago	2024-06-03T20:03:08Z D! [agent] Starting service inputs	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Starting Telegraf 1.30.3 brought to you by InfluxData the makers of InfluxDB	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Available plugins: 233 inputs, 9 aggregators, 31 processors, 24 parsers, 60 outputs, 6 secret-stores	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Loaded inputs: ecs	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Loaded aggregators:	telegraf
20 minutes ago	2024-06-03T20:03:08Z I! Loading config: /telegraf.conf	telegraf
```

### System info

Telegraf 1.30.3

### Steps to reproduce

Deploy a Fargate ECS service with telegraf running as sidecar. 

Been running Telegraf on "fargate and ecs on ec2" for sometime. This issue looks to only occur on Fargate. And from what I can tell, works up to version 1.29.1, then I see this behavior on 1.29.2 and above.

Looks to be timing related, if I delay the telegraf sidecar from starting for like 60 seconds, it runs fine. So maybe the metadata endpoint is not ready, has no data, or has some odd data if queried to quickly.

### Expected behavior

The error should not cause a panic.

### Actual behavior

Telegraf process aborts on panic.

**Comment by powersj** [comment]
Hi,

Could you try one of the artifacts in #15456 and let us know if that helps resolve the issue? There is a comment by the [telegraf tiger](https://github.com/influxdata/telegraf/pull/15456#issuecomment-2148089723) that has downloadable artifacts that contain a possible fix.

Thanks!

**Comment by philiptrovato** [comment]
That artifact looks to resolve, can no longer duplicate the issue!

**Comment by srebhan** [comment]
@philiptrovato did this work with older version of Telegraf? I'm asking because I wonder if maybe the returned data changed in structure or anything... Please double check the results with the PR for missing metrics or data-points!

**Comment by philiptrovato** [comment]
@srebhan All Looks well with the datapoints! Old versions like 1.22, 1.26, and newer versions 1.30.

And the current version does work fine depending on the startup timing. I suspect the cause was something between slower starting containers (like if telegraf starts before your main container) and maybe the newer "v4 metadata" thats now in use. Maybe the stats, or structure returned when queried before all containers are started is a little different v2 vs v4
