### ISSUE TITLE
Translate option isn’t working 

### ISSUE THREAD

**Issue by PFraire** [influxdata/telegraf#15617]
### Relevant telegraf.conf

```toml
[[inputs.snmp.field]]
    oid = "SNMPv2-MIB::sysObjectID.0"
    translate = true
```

### Logs from Telegraf

```text
[server test]$ telegraf --config telegraf.cfg --config-directory /test/ --debug --test
2024-07-11T12:06:17Z I! Loading config: telegraf.cfg
2024-07-11T12:06:17Z I! Loading config: /test/INPUTS_SNMPv2-MIB.conf
2024-07-11T12:06:17Z I! Starting Telegraf 1.30.3 brought to you by InfluxData the makers of InfluxDB
2024-07-11T12:06:17Z I! Available plugins: 233 inputs, 9 aggregators, 31 processors, 24 parsers, 60 outputs, 6 secret-stores
2024-07-11T12:06:17Z I! Loaded inputs: snmp
2024-07-11T12:06:17Z I! Loaded aggregators:
2024-07-11T12:06:17Z I! Loaded processors:
2024-07-11T12:06:17Z I! Loaded secretstores:
2024-07-11T12:06:17Z W! Outputs are not used in testing mode!
2024-07-11T12:06:17Z I! Tags enabled:
2024-07-11T12:06:17Z D! [agent] Initializing plugins
2024-07-11T12:06:30Z D! [agent] Starting service inputs
2024-07-11T12:06:30Z D! [agent] Stopping service inputs
2024-07-11T12:06:30Z D! [agent] Input channel closed
2024-07-11T12:06:30Z D! [agent] Stopped Successfully
> SNMPv2-MIB::system,SNMPv2-MIB::sysContact=X,SNMPv2-MIB::sysLocation=X,SNMPv2-MIB::sysName=X,source=172.18.35.21,sysDescr.0=X,sysObjectID.0=.1.3.6.1.4.1.2011.2.239.57 IF-MIB::ifNumber=60i,SNMPv2-MIB::sysUpTime=12535234.94 1720699590000000000
[server test]$ telegraf --config /test/telegraf.cfg --config-directory /test/ --debug --test
2024-07-11T12:08:22Z I! Loading config: /test/telegraf.cfg
2024-07-11T12:08:22Z W! DeprecationWarning: Value "netsnmp" for option "snmp_translator" of plugin "agent" deprecated since version 1.25.0 and will be removed in 2.0.0: Use 'gosmi' instead
2024-07-11T12:08:22Z I! Loading config: /test/INPUTS_SNMPv2-MIB.conf
2024-07-11T12:08:22Z W! DeprecationWarning: Value "netsnmp" for option "snmp_translator" of plugin "agent" deprecated since version 1.25.0 and will be removed in 2.0.0: Use 'gosmi' instead
2024-07-11T12:08:22Z I! Starting Telegraf 1.30.3 brought to you by InfluxData the makers of InfluxDB
2024-07-11T12:08:22Z I! Available plugins: 233 inputs, 9 aggregators, 31 processors, 24 parsers, 60 outputs, 6 secret-stores
2024-07-11T12:08:22Z I! Loaded inputs: snmp
2024-07-11T12:08:22Z I! Loaded aggregators:
2024-07-11T12:08:22Z I! Loaded processors:
2024-07-11T12:08:22Z I! Loaded secretstores:
2024-07-11T12:08:22Z W! Outputs are not used in testing mode!
2024-07-11T12:08:22Z I! Tags enabled:
2024-07-11T12:08:22Z D! [agent] Initializing plugins
2024-07-11T12:08:22Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "SNMPv2-MIB::sysDescr.0"
2024-07-11T12:08:22Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "SNMPv2-MIB::sysObjectID.0"
2024-07-11T12:08:23Z D! [agent] Starting service inputs
2024-07-11T12:08:23Z D! [agent] Stopping service inputs
2024-07-11T12:08:23Z D! [agent] Input channel closed
2024-07-11T12:08:23Z D! [agent] Stopped Successfully
> SNMPv2-MIB::system,SNMPv2-MIB::sysContact=X,SNMPv2-MIB::sysLocation=X,SNMPv2-MIB::sysName=X,source=172.18.35.21,sysDescr.0=X,sysObjectID.0=.1.3.6.1.4.1.2011.2.239.57 IF-MIB::ifNumber=60i,SNMPv2-MIB::sysUpTime=12535347.95 1720699703000000000
```

### System info

Telegraf 1.30.3 CentOS Linux 7 (Core)

### Steps to reproduce

translate = true

### Expected behavior

`SNMPv2-MIB::sysObjectID=HUAWEI-MIB::ce6857-48S6CQ-EI`

### Actual behavior

`SNMPv2-MIB::sysObjectID=.1.3.6.1.4.1.2011.2.239.57`

### Additional info

More debugging detail in:

https://community.influxdata.com/t/begginer-question-snmp-plugin-how-to-translate-oid-when-is-a-tag-value/34906

**Comment by Hipska** [comment]
@PFraire please test the binary in PR https://github.com/influxdata/telegraf/pull/15618, available as soon as CI finished tests, and let me know if this works for you!

**Comment by PFraire** [comment]
Hi!

Sorry, as I don’t have a testing server I expanded the file on my user home directory, backuped current telegraf binary and replace with the new one,  don’t know if it is correct though.

This is the output :

WARN[0000]log.go:244 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.
2024-07-11T16:16:47Z I! Loading config: /home/pdfraire/telegraf/telegraf.cfg
2024-07-11T16:16:47Z I! Loading config: /home/pdfraire/telegraf/CloudEngine/test/INPUTS_SNMPv2-MIB.conf
2024-07-11T16:16:47Z I! Starting Telegraf 1.32.0-76e9964b brought to you by InfluxData the makers of InfluxDB
2024-07-11T16:16:47Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 61 outputs, 6 secret-stores
2024-07-11T16:16:47Z I! Loaded inputs: snmp (4x)
2024-07-11T16:16:47Z I! Loaded aggregators:
2024-07-11T16:16:47Z I! Loaded processors:
2024-07-11T16:16:47Z I! Loaded secretstores:
2024-07-11T16:16:47Z W! Outputs are not used in testing mode!
2024-07-11T16:16:47Z I! Tags enabled:
2024-07-11T16:16:47Z D! [agent] Initializing plugins
2024-07-11T16:16:59Z D! [agent] Starting service inputs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x3c93ce9]

goroutine 76 [running]:
github.com/influxdata/telegraf/internal/snmp.Table.Build({{0xc002eff519, 0x12}, {0x0, 0x0, 0x0}, 0x0, {0xc001d2e008, 0x9, 0x9}, {0x0, ...}, ...}, ...)
        /go/src/github.com/influxdata/telegraf/internal/snmp/table.go:179 +0x689
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).gatherTable(0xc00263b0e0, {0x9b8dca0, 0xc00a83a220}, {0x9b526c8, 0xc00a37e000}, {{0xc002eff519, 0x12}, {0x0, 0x0, 0x0}, ...}, ...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:134 +0x87
github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Gather.func1(0x0?, {0xc0031cf4a1, 0x16})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:116 +0x20b
created by github.com/influxdata/telegraf/plugins/inputs/snmp.(*Snmp).Gather in goroutine 53
        /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp/snmp.go:102 +0x66

Regards!

De: Thomas Casteleyn ***@***.***>
Enviado el: jueves 11 de julio de 2024 11:58
Para: influxdata/telegraf ***@***.***>
CC: Pablo Fraire ***@***.***>; Mention ***@***.***>
Asunto: Re: [influxdata/telegraf] Translate option isn’t working (Issue #15617)


@PFraire<https://github.com/PFraire> please test the binary in PR #15618<https://github.com/influxdata/telegraf/pull/15618>, available as soon as CI finished tests, and let me know if this works for you!

**Comment by Hipska** [comment]
You are right, a new fixed binary is on its way in the PR!

**Comment by PFraire** [comment]
Hi!

It worked perfect!

I used my original imputs.snmp:

`  [[inputs.snmp.field]]
    oid = ".1.3.6.1.2.1.1.2.0"
    name = "SNMPv2-MIB::sysObjectID"
    translate = true
    is_tag = true
` 

`[server ~]$ telegraf --config telegraf.cfg --config-directory /test/ --debug --test
WARN[0000]log.go:244 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.
2024-07-12T15:00:06Z I! Loading config: /telegraf.cfg
2024-07-12T15:00:06Z I! Loading config: /test/INPUTS_SNMPv2-MIB.conf
2024-07-12T15:00:06Z I! Starting Telegraf 1.32.0-7417f686 brought to you by InfluxData the makers of InfluxDB
2024-07-12T15:00:06Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 61 outputs, 6 secret-stores
2024-07-12T15:00:06Z I! Loaded inputs: snmp (4x)
2024-07-12T15:00:06Z I! Loaded aggregators:
2024-07-12T15:00:06Z I! Loaded processors:
2024-07-12T15:00:06Z I! Loaded secretstores:
2024-07-12T15:00:06Z W! Outputs are not used in testing mode!
2024-07-12T15:00:06Z I! Tags enabled:
2024-07-12T15:00:06Z D! [agent] Initializing plugins
2024-07-12T15:00:18Z D! [agent] Starting service inputs
> SNMPv2-MIB::system,SNMPv2-MIB::sysContact=X,SNMPv2-MIB::sysDescr=X,SNMPv2-MIB::sysLocation=X,SNMPv2-MIB::sysName=X,SNMPv2-MIB::sysObjectID=ce6857-48S6CQ-EI,source=172.18.35.21 IF-MIB::ifNumber=60i,SNMPv2-MIB::sysUpTime=12632062.7 1720796419000000000
`
Should I do something to clear that WARN?

**Comment by PFraire** [comment]
Ok! Thanks again!
