### ISSUE TITLE
Concurrent map read write in inputs.influxdb_v2_listener

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#15952]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = ${BATCH_SIZE:?err}
  metric_buffer_limit = ${BUFFER_SIZE:?err}
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = true
  debug = false
  quiet = true  # only log errors


[[secretstores.docker]]
  id = "k8s_secrets"
  path = "/secrets"
  dynamic = true


[[outputs.influxdb_v2]]
  tagpass = {"?dlg_destination"=["data"]}
  tagexclude=["?dlg_destination"]
  urls = ["${DESTINATION_URL?:err}"]
  token = "@{k8s_secrets:dest_token_w}"
  organization = "allseas"
  bucket_tag = "?dlg_destination_bucket"
  timeout = "15s"
  exclude_bucket_tag = true
  content_encoding = "gzip"
  influx_uint_support = true

  ## HTTP/2 Timeouts
  ## The following values control the HTTP/2 client's timeouts. These settings
  ## are generally not required unless a user is seeing issues with client
  ## disconnects. If a user does see issues, then it is suggested to set these
  ## values to "15s" for ping timeout and "30s" for read idle timeout and
  ## retry.
  ##
  ## Note that the timer for read_idle_timeout begins at the end of the last
  ## successful write and not at the beginning of the next write.
  # ping_timeout = "15s"
  # read_idle_timeout = "30s"


# Configuration for the Prometheus client to spawn
[[outputs.prometheus_client]]
  ## Address to listen on.
  listen = ":1234"
  tagpass={"?dlg_destination"=["monitoring"]}
  tagexclude=["?dlg_destination"]

# Collect statistics about Telegraf itself
[[inputs.internal]]
  tags={"?dlg_destination"="monitoring"}
  interval="15s"


[[inputs.influxdb_v2_listener]]
  tags = {"?dlg_destination"="data"}
  service_address = ":8086"
  max_undelivered_metrics = ${BUFFER_SIZE:?err}
  max_body_size = "32MiB"
  bucket_tag = "?dlg_destination_bucket"
  token = "@{k8s_secrets:dest_token_w}"
  parser_type = "upstream"
```

### Logs from Telegraf

```text
fatal error: concurrent map read and map write

goroutine 66 [running]:
github.com/influxdata/telegraf/plugins/inputs/influxdb_v2_listener.(*InfluxDBV2Listener).Start.func1()
	/home/vsts/work/1/s/plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go:169 +0xee
created by github.com/influxdata/telegraf/plugins/inputs/influxdb_v2_listener.(*InfluxDBV2Listener).Start in goroutine 1
	/home/vsts/work/1/s/plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go:163 +0x1a5

goroutine 1 [semacquire, 40419 minutes]:
sync.runtime_Semacquire(0xc000d4cfa0?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc000b9c728?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/sync/waitgroup.go:116 +0x48
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc000b9c728, {0x3cb5768, 0xc000b86870})
	/home/vsts/work/1/s/agent/agent.go:197 +0xa2c
main.(*Telegraf).runAgent(0xc000bb8000, {0x3cb5768, 0xc000b86870}, 0x0?)
	/home/vsts/work/1/s/cmd/telegraf/telegraf.go:443 +0x174c
main.(*Telegraf).reloadLoop(0xc000bb8000)
	/home/vsts/work/1/s/cmd/telegraf/telegraf.go:189 +0x265
main.(*Telegraf).Run(0xc000bb8000)
	/home/vsts/work/1/s/cmd/telegraf/telegraf_posix.go:19 +0xbe
main.runApp.func1(0xc000b9a640)
	/home/vsts/work/1/s/cmd/telegraf/main.go:251 +0xcf0
github.com/urfave/cli/v2.(*Command).Run(0xc000bb9b80, 0xc000b9a640, {0xc000074570, 0x3, 0x3})
	/home/vsts/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x97d
github.com/urfave/cli/v2.(*App).RunContext(0xc000bbe000, {0x3cb5570, 0x5ed6a80}, {0xc000074570, 0x3, 0x3})
	/home/vsts/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
	/home/vsts/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:307
main.runApp({0xc000074570, 0x3, 0x3}, {0x3c82be0, 0xc0000a4028}, {0x3c8ffe0, 0xc000b9c0c0}, {0x3c90008, 0xc000bb8160}, {0x3cb5420, ...})
	/home/vsts/work/1/s/cmd/telegraf/main.go:394 +0x1065
main.main()
	/home/vsts/work/1/s/cmd/telegraf/main.go:408 +0xe8

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000600b80)
	/home/vsts/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/home/vsts/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 57 [chan receive]:
github.com/awnumar/memguard/core.NewCoffer.func1(0xc000b89220)
	/home/vsts/go/pkg/mod/github.com/awnumar/memguard@v0.22.5/core/coffer.go:39 +0x45
created by github.com/awnumar/memguard/core.NewCoffer in goroutine 1
	/home/vsts/go/pkg/mod/github.com/awnumar/memguard@v0.22.5/core/coffer.go:36 +0x116

goroutine 59 [syscall, 40419 minutes]:
os/signal.signal_recv()
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/opt/hostedtoolcache/go/1.22.0/x64/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	/opt/hostedtoolcache/go/1.22.0/x64/src/os/signal/signal.go:151 +0x1f

goroutine 60 [select, 40419 minutes]:
main.(*Telegraf).reloadLoop.func1()
	/home/vsts/work/1/s/cmd/telegraf/telegraf.go:173 +0xbb
created by main.(*Telegraf).reloadLoop in goroutine 1
	/home/vsts/work/1/s/cmd/telegraf/telegraf.go:172 +0x245

goroutine 63 [chan receive]:
github.com/influxdata/telegraf/plugins/outputs/prometheus_client/v1.NewCollector.func1()
	/home/vsts/work/1/s/plugins/outputs/prometheus_client/v1/collector.go:85 +0x28
created by github.com/influxdata/telegraf/plugins/outputs/prometheus_client/v1.NewCollector in goroutine 1
	/home/vsts/work/1/s/plugins/outputs/prometheus_client/v1/collector.go:83 +0x196

goroutine 33 [IO wait]:
internal/poll.runtime_pollWait(0x7fa20472a760, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0x3?, 0x1?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000ce9b00)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000ce9b00)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc000d3b900)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc000d3b900)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/tcpsock.go:327 +0x30
net/http.(*Server).Serve(0xc000aae000, {0x3ca0ed0, 0xc000d3b900})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3255 +0x33e
github.com/influxdata/telegraf/plugins/outputs/prometheus_client.(*PrometheusClient).Connect.func1()
	/home/vsts/work/1/s/plugins/outputs/prometheus_client/prometheus_client.go:250 +0x6a
created by github.com/influxdata/telegraf/plugins/outputs/prometheus_client.(*PrometheusClient).Connect in goroutine 1
	/home/vsts/work/1/s/plugins/outputs/prometheus_client/prometheus_client.go:248 +0x247

goroutine 67 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0x7fa20472a668, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0x7?, 0x27?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000ce9b80)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000ce9b80)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc000d3b9a0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc000d3b9a0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/tcpsock.go:327 +0x30
net/http.(*Server).Serve(0xc000bee578, {0x3ca0ed0, 0xc000d3b9a0})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3255 +0x33e
github.com/influxdata/telegraf/plugins/inputs/influxdb_v2_listener.(*InfluxDBV2Listener).Start.func2()
	/home/vsts/work/1/s/plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go:209 +0x45
created by github.com/influxdata/telegraf/plugins/inputs/influxdb_v2_listener.(*InfluxDBV2Listener).Start in goroutine 1
	/home/vsts/work/1/s/plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go:208 +0x45f

goroutine 68 [chan receive]:
github.com/influxdata/telegraf/agent.(*Agent).runOutputs(0xc000b9c728, 0xc000a8a540)
	/home/vsts/work/1/s/agent/agent.go:874 +0x265
github.com/influxdata/telegraf/agent.(*Agent).Run.func1()
	/home/vsts/work/1/s/agent/agent.go:166 +0x51
created by github.com/influxdata/telegraf/agent.(*Agent).Run in goroutine 1
	/home/vsts/work/1/s/agent/agent.go:164 +0x74e

goroutine 69 [semacquire, 40419 minutes]:
sync.runtime_Semacquire(0xc000d2f290?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x0?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/sync/waitgroup.go:116 +0x48
github.com/influxdata/telegraf/agent.(*Agent).runInputs(0xc000b9c728, {0x3cb5768, 0xc000b86870}, {0x0?, 0x0?, 0x5938ce0?}, 0xc000d3b940)
	/home/vsts/work/1/s/agent/agent.go:429 +0x525
github.com/influxdata/telegraf/agent.(*Agent).Run.func5()
	/home/vsts/work/1/s/agent/agent.go:194 +0x69
created by github.com/influxdata/telegraf/agent.(*Agent).Run in goroutine 1
	/home/vsts/work/1/s/agent/agent.go:192 +0xa1f

goroutine 70 [select]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc000ce3f40, {0x3cb5768, 0xc000d4cff0}, 0xc000d4d090)
	/home/vsts/work/1/s/agent/tick.go:87 +0x12e
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	/home/vsts/work/1/s/agent/tick.go:65 +0x5b
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 69
	/home/vsts/work/1/s/agent/tick.go:63 +0x16f

goroutine 71 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000b9c728, {0x3cb5768, 0xc000b86870}, {0x3ccdc18, 0xc000d3ba00}, 0xc000bb02d0, {0x3c90ee8, 0xc000ce3f40}, 0x37e11d600)
	/home/vsts/work/1/s/agent/agent.go:561 +0xc6
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	/home/vsts/work/1/s/agent/agent.go:425 +0x73
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 69
	/home/vsts/work/1/s/agent/agent.go:423 +0xde

goroutine 45 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flushLoop(0xc000b9c728, {0x3cb5768, 0xc000a9c410}, 0xc000b8c280, {0x3c90ec0, 0xc000a862a0})
	/home/vsts/work/1/s/agent/agent.go:919 +0x1c5
github.com/influxdata/telegraf/agent.(*Agent).runOutputs.func1(0xc000b8c280)
	/home/vsts/work/1/s/agent/agent.go:870 +0x116
created by github.com/influxdata/telegraf/agent.(*Agent).runOutputs in goroutine 68
	/home/vsts/work/1/s/agent/agent.go:864 +0xbc

goroutine 46 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flushLoop(0xc000b9c728, {0x3cb5768, 0xc000a9c410}, 0xc000b8c3c0, {0x3c90ec0, 0xc000a86240})
	/home/vsts/work/1/s/agent/agent.go:919 +0x1c5
github.com/influxdata/telegraf/agent.(*Agent).runOutputs.func1(0xc000b8c3c0)
	/home/vsts/work/1/s/agent/agent.go:870 +0x116
created by github.com/influxdata/telegraf/agent.(*Agent).runOutputs in goroutine 68
	/home/vsts/work/1/s/agent/agent.go:864 +0xbc

goroutine 47 [select]:
github.com/influxdata/telegraf/agent.(*RollingTicker).run(0xc000a86240, {0x3cb5768, 0xc000a9c460}, 0xc000a9c500)
	/home/vsts/work/1/s/agent/tick.go:258 +0xc5
github.com/influxdata/telegraf/agent.(*RollingTicker).start.func1()
	/home/vsts/work/1/s/agent/tick.go:248 +0x5b
created by github.com/influxdata/telegraf/agent.(*RollingTicker).start in goroutine 46
	/home/vsts/work/1/s/agent/tick.go:246 +0x159

goroutine 72 [select]:
github.com/influxdata/telegraf/agent.(*AlignedTicker).run(0xc000dba000, {0x3cb5768, 0xc000d4d130}, 0xc000d4d1d0)
	/home/vsts/work/1/s/agent/tick.go:87 +0x12e
github.com/influxdata/telegraf/agent.(*AlignedTicker).start.func1()
	/home/vsts/work/1/s/agent/tick.go:65 +0x5b
created by github.com/influxdata/telegraf/agent.(*AlignedTicker).start in goroutine 69
	/home/vsts/work/1/s/agent/tick.go:63 +0x16f

goroutine 73 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherLoop(0xc000b9c728, {0x3cb5768, 0xc000b86870}, {0x3ccdc18, 0xc000d3ba20}, 0xc000bb0360, {0x3c90ee8, 0xc000dba000}, 0x2540be400)
	/home/vsts/work/1/s/agent/agent.go:561 +0xc6
github.com/influxdata/telegraf/agent.(*Agent).runInputs.func1(0x0?)
	/home/vsts/work/1/s/agent/agent.go:425 +0x73
created by github.com/influxdata/telegraf/agent.(*Agent).runInputs in goroutine 69
	/home/vsts/work/1/s/agent/agent.go:423 +0xde

goroutine 48 [select]:
github.com/influxdata/telegraf/agent.(*RollingTicker).run(0xc000a862a0, {0x3cb5768, 0xc000a9c550}, 0xc000a9c5f0)
	/home/vsts/work/1/s/agent/tick.go:258 +0xc5
github.com/influxdata/telegraf/agent.(*RollingTicker).start.func1()
	/home/vsts/work/1/s/agent/tick.go:248 +0x5b
created by github.com/influxdata/telegraf/agent.(*RollingTicker).start in goroutine 45
	/home/vsts/work/1/s/agent/tick.go:246 +0x159

goroutine 8884080 [IO wait]:
internal/poll.runtime_pollWait(0x7fa20472a190, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc0009f0280?, 0xc000bec000?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0009f0280, {0xc000bec000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0009f0280, {0xc000bec000?, 0xc00124da98?, 0x4f5985?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0011b6038, {0xc000bec000?, 0x0?, 0xc000bf9e08?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/net.go:179 +0x45
net/http.(*connReader).Read(0xc000bf9e00, {0xc000bec000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:789 +0x14b
bufio.(*Reader).fill(0xc0015cdda0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc0015cdda0, 0x4)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:148 +0x53
net/http.(*conn).serve(0xc0006f05a0, {0x3cb5730, 0xc000e30450})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2074 +0x749
created by net/http.(*Server).Serve in goroutine 67
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3285 +0x4b4

goroutine 8882986 [IO wait]:
internal/poll.runtime_pollWait(0x7fa20472a098, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000680000?, 0xc000624000?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000680000, {0xc000624000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000680000, {0xc000624000?, 0xc001337a98?, 0x4f5985?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0007ea000, {0xc000624000?, 0x0?, 0xc0009feab8?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/net.go:179 +0x45
net/http.(*connReader).Read(0xc0009feab0, {0xc000624000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:789 +0x14b
bufio.(*Reader).fill(0xc00060e000)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc00060e000, 0x4)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:148 +0x53
net/http.(*conn).serve(0xc000a9a120, {0x3cb5730, 0xc000e30450})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2074 +0x749
created by net/http.(*Server).Serve in goroutine 67
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3285 +0x4b4

goroutine 8886707 [IO wait]:
internal/poll.runtime_pollWait(0x7fa20472a478, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000318000?, 0xc00017c0a1?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000318000, {0xc00017c0a1, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000318000, {0xc00017c0a1?, 0xc001777748?, 0x478eb0?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0000a4000, {0xc00017c0a1?, 0xc000e6a4e0?, 0xc0016429f8?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/net.go:179 +0x45
net/http.(*connReader).backgroundRead(0xc00017c090)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:681 +0x37
created by net/http.(*connReader).startBackgroundRead in goroutine 8884776
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:677 +0xba

goroutine 8622528 [IO wait]:
internal/poll.runtime_pollWait(0x7fa20472a288, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00053a580?, 0xc000049000?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00053a580, {0xc000049000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc00053a580, {0xc000049000?, 0xc000ac7f28?, 0xc0015cc4e0?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000b9c4b8, {0xc000049000?, 0xc000ac7b00?, 0x0?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/net.go:179 +0x45
net/http.(*persistConn).Read(0xc0001f06c0, {0xc000049000?, 0x457700?, 0xc000ac7f28?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/transport.go:1976 +0x4a
bufio.(*Reader).fill(0xc000e96360)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc000e96360, 0x1)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:148 +0x53
net/http.(*persistConn).readLoop(0xc0001f06c0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/transport.go:2140 +0x1b9
created by net/http.(*Transport).dialConn in goroutine 8622551
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/transport.go:1798 +0x152f

goroutine 8884776 [runnable]:
bufio.(*Writer).Write(0xc000688000, {0xc0001f5224?, 0x1d?, 0x1d?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:673 +0x1cf
net/http.extraHeader.Write({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc0001f5224, 0x1d, 0x1d}, {0x0, ...}}, ...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:1233 +0x65
net/http.(*chunkWriter).writeHeader(0xc0001f51c0, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:1524 +0xfd8
net/http.(*chunkWriter).close(0xc0001f51c0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:406 +0x29
net/http.(*response).finishRequest(0xc0001f5180)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:1668 +0x65
net/http.(*conn).serve(0xc0006f0090, {0x3cb5730, 0xc000e30450})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2045 +0x62b
created by net/http.(*Server).Serve in goroutine 67
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3285 +0x4b4

goroutine 8880636 [IO wait]:
internal/poll.runtime_pollWait(0x7fa204729fa0, 0x72)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc0009f0200?, 0xc001477000?, 0x0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0009f0200, {0xc001477000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0009f0200, {0xc001477000?, 0xc001247a98?, 0x4f5985?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000cce530, {0xc001477000?, 0x0?, 0xc0016429f8?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/net.go:179 +0x45
net/http.(*connReader).Read(0xc0016429f0, {0xc001477000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:789 +0x14b
bufio.(*Reader).fill(0xc000ad05a0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc000ad05a0, 0x4)
	/opt/hostedtoolcache/go/1.22.0/x64/src/bufio/bufio.go:148 +0x53
net/http.(*conn).serve(0xc000bb0ab0, {0x3cb5730, 0xc000e30450})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2074 +0x749
created by net/http.(*Server).Serve in goroutine 67
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3285 +0x4b4

goroutine 8622529 [select]:
net/http.(*persistConn).writeLoop(0xc0001f06c0)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/transport.go:2443 +0xf0
created by net/http.(*Transport).dialConn in goroutine 8622551
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/transport.go:1799 +0x1585
```

### System info

Telegraf 1.31.2

### Steps to reproduce

1. Not sure how, it happens very rarely

### Expected behavior

No crash

### Actual behavior

Crash

**Comment by LarsStegman** [comment]
Looking into it more, looks I made this code haha.
