### ISSUE TITLE
MongoDB Input plugin panics when connecting to a MongoDB 2.2 instance

### ISSUE THREAD

**Issue by leforsman** [influxdata/telegraf#1625]
Running telegraf 0.13.2 with the following input configuration against mongodb 2.2 which produces a panic.

[[inputs.mongodb]]
 servers = ["mongodb://telegraf:password@127.0.0.1:27017"]

```
$telegraf -config /etc/telegraf/telegraf.conf -test
...
* Plugin: mongodb, Collection 1
* Plugin: mongodb, Collection 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5d12d3]

goroutine 114 [running]:
panic(0x107ebc0, 0xc8200100d0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/mongodb.NewStatLine(0xecf3e5ebe, 0x32c86f86, 0x1c532a0, 0xc82084e000, 0xc820594020, 0xc8204dbae0, 0xecf3e5ebf, 0x1552a702, 0x1c532a0, 0xc820234000, ...)
    /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongostat.go:474 +0x483
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*Server).gatherData(0xc820832660, 0x7fcf995f7940, 0xc8201ecd50, 0x0, 0x0)
    /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb_server.go:65 +0xbfe
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).gatherServer(0xc8201dab40, 0xc820832660, 0x7fcf995f7940, 0xc8201ecd50, 0x0, 0x0)
    /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb.go:138 +0x95e
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).Gather.func1(0xc8204fe040, 0xc8204fe050, 0xc8201dab40, 0x7fcf995f7940, 0xc8201ecd50, 0xc820832660)
    /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb.go:74 +0x6a
created by github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).Gather
    /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb.go:75 +0x5dc
```

**Comment by sparrc** [comment]
can you try running with 1.0 beta3 ? https://github.com/influxdata/telegraf#installation

**Comment by leforsman** [comment]
Retested with 1.0.0-beta3 and it gives the same result.

**Comment by sparrc** [comment]
can you provide the traceback? it can't be exactly the same I don't think because the code has changed and the relevant line should be different

**Comment by leforsman** [comment]
Here is the traceback when using the same config on 1.0.0-beta3

```
$telegraf -version
Telegraf - version 1.0.0-beta3

$telegraf -config /etc/telegraf/telegraf.conf -test -input-filter mongodb
* Plugin: mongodb, Collection 1
* Plugin: mongodb, Collection 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5aaa13]

goroutine 68 [running]:
panic(0x12a82e0, 0xc8200100d0)
  /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/mongodb.NewStatLine(0xecf3e8d3a, 0xcbbeb2, 0x1ffd580, 0xc8204de000, 0xc820233e40, 0xc8204dd240, 0xecf3e8d3a, 0x1f0616b4, 0x1ffd580, 0xc8204de0f0, ...)
  /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongostat.go:474 +0x483
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*Server).gatherData(0xc8200e15a0, 0x7fa481163cd8, 0xc820246f00, 0x0, 0x0)
  /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb_server.go:65 +0xc5a
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).gatherServer(0xc820246e40, 0xc8200e15a0, 0x7fa481163cd8, 0xc820246f00, 0x0, 0x0)
  /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb.go:138 +0x95e
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).Gather.func1(0xc8204d7bf0, 0xc8204d7c00, 0xc820246e40, 0x7fa481163cd8, 0xc820246f00, 0xc8200e15a0)
  /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb.go:74 +0x6a
created by github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).Gather
  /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb.go:75 +0x5dc  
```

**Comment by sparrc** [comment]
closed by https://github.com/influxdata/telegraf/pull/1713
