### ISSUE TITLE
Attempting to parse IP address as float

### ISSUE THREAD

**Issue by stub42** [influxdata/telegraf#1627]
### Relevant telegraf.conf:
```toml
[[inputs.postgresql_extensible.query]]
  sqlquery="""
    SELECT
      COALESCE(client_hostname, host(client_addr)) AS standby,
      pg_xlog_location_diff(pg_current_xlog_insert_location(),
                            replay_location) AS lag_bytes
    FROM pg_stat_replication"""
  version=902
  withdbname=false
  tagvalue=""
```

### System info:

Ubuntu 16.04, Telegraf 1.0.0-beta3

### Steps to reproduce:

1. Create an inputs.postgresql_extensible.query that may return an IP address in one of the columns.
2. Watch telegraf panic when it attempts to parse the string as a float.

### Expected behavior:

telegraf should notice there are multiple periods and not parse the value as a number.

### Actual behavior:

It explodes.

### Additional info:

```
panic: unable to parse number value '10.0.4.52': strconv.ParseFloat: parsing "10.0.4.52": invalid syntax
goroutine 27 [running]:
panic(0x103dde0, 0xc8206e85c0)
#011/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/models.newFieldsFromBinary(0xc8200ddc40, 0x1d, 0x20, 0x6)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/models/points.go:1456 +0x6a1
github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/models.(*point).unmarshalBinary(0xc82036e510, 0xc8206e4698)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/models/points.go:1338 +0x40
github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/models.(*point).Fields(0xc82036e510, 0xc8206e46f8)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/models/points.go:1251 +0x3a
github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/client/v2.(*Point).Fields(0xc8204af300, 0x1fcbee0)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/influxdb/client/v2/client.go:392 +0x39
github.com/influxdata/telegraf.(*metric).Fields(0xc820116068, 0xc8206ea060)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/metric.go:76 +0x24
github.com/influxdata/telegraf/plugins/outputs/prometheus_client.(*PrometheusClient).Write(0xc820119d60, 0xc8206a6a80, 0xe, 0xe, 0x0, 0x0)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/plugins/outputs/prometheus_client/prometheus_client.go:116 +0x3c6
github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc820186230, 0xc8206a6a80, 0xe, 0xe, 0x0, 0x0)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/internal/models/running_output.go:145 +0xcd
github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc820186230, 0x0, 0x0)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/internal/models/running_output.go:131 +0x527
github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc8204b3670, 0xc820186230)
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/agent/agent.go:245 +0x6e
created by github.com/influxdata/telegraf/agent.(*Agent).flush
#011/build/telegraf-F1CATD/telegraf-1.0.0/obj-x86_64-linux-gnu/src/github.com/influxdata/telegraf/agent/agent.go:250 +0xc0
```

**Comment by stub42** [comment]
Not a bug. I needed to use tagvalue to specify the column as one to use as a tag.

```toml
[[inputs.postgresql_extensible.query]]
  sqlquery="""
    SELECT
      COALESCE(client_hostname,
               host(client_addr)) AS standby,
      pg_xlog_location_diff(pg_current_xlog_insert_location(),
                            replay_location) AS lag_bytes
    FROM pg_stat_replication"""
  version=902
  withdbname=false
  tagvalue="standby"
```
