### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by KammutierSpule** [influxdata/telegraf#16350]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  # debug = true
  # quiet = false
  # logtarget = "stderr"

  interval = "5m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5m"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false
```

### Logs from Telegraf

```text
2024-12-28T00:45:35.919455+00:00 orangepizeroplus telegraf[2083]: panic: runtime error: index out of range [0] with length 0
2024-12-28T00:45:35.926049+00:00 orangepizeroplus telegraf[2083]: goroutine 705 [running]:
2024-12-28T00:45:35.940842+00:00 orangepizeroplus telegraf[2083]: github.com/influxdata/telegraf/plugins/outputs/influxdb_v2.(*httpClient).Write(0x4002581180, {0x937c360, 0xf687960}, {0x40001e0c88, 0x25, 0x25})
2024-12-28T00:45:35.941386+00:00 orangepizeroplus telegraf[2083]: #011/go/src/github.com/influxdata/telegraf/plugins/outputs/influxdb_v2/http.go:213 +0x844
2024-12-28T00:45:35.941633+00:00 orangepizeroplus telegraf[2083]: github.com/influxdata/telegraf/plugins/outputs/influxdb_v2.(*InfluxDB).Write(0x40029e5688, {0x40001e0c88, 0x25, 0x25})
2024-12-28T00:45:35.941794+00:00 orangepizeroplus telegraf[2083]: #011/go/src/github.com/influxdata/telegraf/plugins/outputs/influxdb_v2/influxdb_v2.go:201 +0x10c
2024-12-28T00:45:35.965380+00:00 orangepizeroplus telegraf[2083]: github.com/influxdata/telegraf/models.(*RunningOutput).writeMetrics(0x40029d24d0, {0x40001e0c88, 0x25, 0x25})
2024-12-28T00:45:35.965849+00:00 orangepizeroplus telegraf[2083]: #011/go/src/github.com/influxdata/telegraf/models/running_output.go:355 +0xf8
2024-12-28T00:45:35.966121+00:00 orangepizeroplus telegraf[2083]: github.com/influxdata/telegraf/models.(*RunningOutput).Write(0x40029d24d0)
2024-12-28T00:45:35.966301+00:00 orangepizeroplus telegraf[2083]: #011/go/src/github.com/influxdata/telegraf/models/running_output.go:313 +0x38c
2024-12-28T00:45:35.966519+00:00 orangepizeroplus telegraf[2083]: github.com/influxdata/telegraf/agent.(*Agent).flushOnce.func1()
2024-12-28T00:45:35.966720+00:00 orangepizeroplus telegraf[2083]: #011/go/src/github.com/influxdata/telegraf/agent/agent.go:938 +0x30
2024-12-28T00:45:35.966897+00:00 orangepizeroplus telegraf[2083]: created by github.com/influxdata/telegraf/agent.(*Agent).flushOnce in goroutine 74
2024-12-28T00:45:35.967292+00:00 orangepizeroplus telegraf[2083]: #011/go/src/github.com/influxdata/telegraf/agent/agent.go:937 +0x94
2024-12-28T00:45:36.049336+00:00 orangepizeroplus systemd[1]: telegraf.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2024-12-28T00:45:36.055622+00:00 orangepizeroplus systemd[1]: telegraf.service: Failed with result 'exit-code'.
2024-12-28T00:45:36.114815+00:00 orangepizeroplus systemd[1]: telegraf.service: Consumed 5.217s CPU time.
2024-12-28T00:45:36.436469+00:00 orangepizeroplus systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 1.
2024-12-28T00:45:36.438362+00:00 orangepizeroplus systemd[1]: Stopped telegraf.service - Telegraf.
2024-12-28T00:45:36.439013+00:00 orangepizeroplus systemd[1]: telegraf.service: Consumed 5.217s CPU time.
2024-12-28T00:45:36.478791+00:00 orangepizeroplus systemd[1]: Starting telegraf.service - Telegraf...
```

### System info

Telegraf 1.33.0

### Steps to reproduce

I don't know

### Expected behavior

don't panic

### Actual behavior

is panicking

**Comment by gone-for-coding** [comment]
Same here beginning with 1.33.

**Comment by srebhan** [comment]
@KammutierSpule or @gone-for-coding could you please add your redacted `outputs.influxdb_v2` config part as well as a few more log lines before the panic (at least the last 5 "normal" log lines)!?!

**Comment by KammutierSpule** [comment]
outputs.influxdb_v2.conf
```
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "mytoken" 
  organization = "myorganization"
  bucket = "Telegraf"
  bucket_tag = "destination"
  exclude_bucket_tag = true
```

So all my inputs has
```
  [inputs. *** .tags]
    destination = "Telegraf_bucket_name"
```

I don't remember where I got these logs, could you remember me and point me with some commands?

**Comment by srebhan** [comment]
@KammutierSpule and @gone-for-coding please test the binary in PR #16388, available as soon as CI finished the tests, and let me know if this fixes the issue!

**Comment by jdstrand** [comment]
I was able to reproduce this using a python server script I modified for reproducing another issue.

`server.py`:
<details>

```
#!/usr/bin/env python3

import getopt
from http.server import BaseHTTPRequestHandler, HTTPServer
import random
import sys
import time

class ErrorServerHandler(BaseHTTPRequestHandler):
    status: int = 200
    def fake_request(self):
        self.send_response(self.status)
        if self.status == 200:
            self.send_header("Content-type", "application/json")
        self.end_headers()
        if self.status == 200:
            try:
                self.wfile.write(b"{}\n")
            except Exception:
                print("%s: broken pipe (client disconnect?)" % self.path)

    def do_GET(self):
        self.fake_request()

    def do_POST(self):
        self.fake_request()

def run(port: int, status: int = 200):
    # XXX: validate delay and port
    addr = ('', port)
    httpd = HTTPServer(addr, ErrorServerHandler)
    ErrorServerHandler.status = status
    httpd.serve_forever()

if __name__ == '__main__':
    global delay
    try:
        opts, rest = getopt.getopt(sys.argv[1:], "hp:s:", [])
    except Exception:
        print("Bad args. See -h")
        sys.exit(1)

    port: int = 8000
    status: int = 200
    for opt, arg in opts:
        if opt == "-h":
            print("""Usage: server.py ARGS
 -h     this message
 -p N   listen on port N
 -s N   return status code N

GET and POST are supported an all paths and simply return an empty JSON
document.
""")
            sys.exit(0)
        elif opt == "-p":
            port = int(arg)
        elif opt == "-s":
            status = int(arg)
    try:
        run(port, status)
    except KeyboardInterrupt:
        pass
```

</details>

To reproduce:
1. start the server:
```
$ python3 ./server.py -s 400
127.0.0.1 - - [09/Jan/2025 16:01:16] "POST /api/v2/write?bucket=Telegraf_bucket_name&org=myorganization HTTP/1.1" 400 -
```
2. use this `telegraf.conf`:
```
$ cat ./telegraf.conf 
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  [inputs.cpu.tags]
    destination = "Telegraf_bucket_name"

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8000"]
  token = "mytoken"
  organization = "myorganization"
  bucket = "Telegraf"
  bucket_tag = "destination"
  exclude_bucket_tag = true
```
3. start telegraf:
```
$ telegraf --debug --config ./telegraf.conf 
2025-01-09T22:00:46Z I! Loading config: ./telegraf.conf
2025-01-09T22:00:46Z I! Starting Telegraf 1.33.0 brought to you by InfluxData the makers of InfluxDB
2025-01-09T22:00:46Z I! Available plugins: 236 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
2025-01-09T22:00:46Z I! Loaded inputs: cpu
2025-01-09T22:00:46Z I! Loaded aggregators:
2025-01-09T22:00:46Z I! Loaded processors:
2025-01-09T22:00:46Z I! Loaded secretstores:
2025-01-09T22:00:46Z I! Loaded outputs: influxdb_v2
2025-01-09T22:00:46Z I! Tags enabled: host=tg16388
2025-01-09T22:00:46Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"tg16388", Flush Interval:10s
2025-01-09T22:00:46Z D! [agent] Initializing plugins
2025-01-09T22:00:46Z D! [agent] Connecting outputs
2025-01-09T22:00:46Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2025-01-09T22:00:46Z D! [agent] Successfully connected to outputs.influxdb_v2
2025-01-09T22:00:46Z D! [agent] Starting service inputs
2025-01-09T22:00:56Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2025-01-09T22:01:06Z D! [outputs.influxdb_v2] Buffer fullness: 21 / 10000 metrics
2025-01-09T22:01:06Z E! [agent] Error writing to outputs.influxdb_v2: Post "http://127.0.0.1:8000/api/v2/write?bucket=Telegraf_bucket_name&org=myorganization": dial tcp 127.0.0.1:8000: connect: connection refused
panic: runtime error: index out of range [0] with length 0

goroutine 103 [running]:
github.com/influxdata/telegraf/plugins/outputs/influxdb_v2.(*httpClient).Write(0xc0023d6280, {0xa461d70, 0x109d2ac0}, {0xc00243c2c8, 0x2a, 0x2a})
	/go/src/github.com/influxdata/telegraf/plugins/outputs/influxdb_v2/http.go:216 +0xa4e
github.com/influxdata/telegraf/plugins/outputs/influxdb_v2.(*InfluxDB).Write(0xc002456248, {0xc00243c2c8, 0x2a, 0x2a})
	/go/src/github.com/influxdata/telegraf/plugins/outputs/influxdb_v2/influxdb_v2.go:201 +0x131
github.com/influxdata/telegraf/models.(*RunningOutput).writeMetrics(0xc00243ac60, {0xc00243c2c8, 0x2a, 0x2a})
	/go/src/github.com/influxdata/telegraf/models/running_output.go:355 +0x10f
github.com/influxdata/telegraf/models.(*RunningOutput).Write(0xc00243ac60)
	/go/src/github.com/influxdata/telegraf/models/running_output.go:313 +0x38a
github.com/influxdata/telegraf/agent.(*Agent).flushOnce.func1()
	/go/src/github.com/influxdata/telegraf/agent/agent.go:938 +0x23
created by github.com/influxdata/telegraf/agent.(*Agent).flushOnce in goroutine 86
	/go/src/github.com/influxdata/telegraf/agent/agent.go:937 +0xa6
```

Using the telegraf binary from PR #16388, it no longer crashes:
```
$ telegraf --debug --config ./telegraf.conf 
2025-01-09T22:03:40Z I! Loading config: ./telegraf.conf
2025-01-09T22:03:40Z I! Starting Telegraf 1.34.0-1304dd90 brought to you by InfluxData the makers of InfluxDB
2025-01-09T22:03:40Z I! Available plugins: 236 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
2025-01-09T22:03:40Z I! Loaded inputs: cpu
2025-01-09T22:03:40Z I! Loaded aggregators:
2025-01-09T22:03:40Z I! Loaded processors:
2025-01-09T22:03:40Z I! Loaded secretstores:
2025-01-09T22:03:40Z I! Loaded outputs: influxdb_v2
2025-01-09T22:03:40Z I! Tags enabled: host=tg16388
2025-01-09T22:03:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"tg16388", Flush Interval:10s
2025-01-09T22:03:40Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
2025-01-09T22:03:40Z D! [agent] Initializing plugins
2025-01-09T22:03:40Z D! [agent] Connecting outputs
2025-01-09T22:03:40Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2025-01-09T22:03:40Z D! [agent] Successfully connected to outputs.influxdb_v2
2025-01-09T22:03:40Z D! [agent] Starting service inputs
2025-01-09T22:03:50Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2025-01-09T22:04:00Z E! [outputs.influxdb_v2] When writing to [http://127.0.0.1:8000/api/v2/write]: failed to write metric to Telegraf_bucket_name (will be dropped: 400 Bad Request)
2025-01-09T22:04:00Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2025-01-09T22:04:00Z E! [agent] Error writing to outputs.influxdb_v2: failed to write metric to Telegraf_bucket_name (will be dropped: 400 Bad Request)
2025-01-09T22:04:10Z E! [outputs.influxdb_v2] When writing to [http://127.0.0.1:8000/api/v2/write]: failed to write metric to Telegraf_bucket_name (will be dropped: 400 Bad Request)
2025-01-09T22:04:10Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2025-01-09T22:04:10Z E! [agent] Error writing to outputs.influxdb_v2: failed to write metric to Telegraf_bucket_name (will be dropped: 400 Bad Request)
...
```

**Comment by srebhan** [comment]
Thanks @jdstrand! I also reproduced the issue in unit-tests (see PR) and see this fixed. @KammutierSpule and @gone-for-coding could you please also confirm the PR fixes the issue with a _real_ server? Would love to get a confirmation before releasing...

**Comment by KammutierSpule** [comment]
Sorry this is a hobby project, I forgot how to reproduce or I can't see these errors at moment (but I didn't tried the new version).

**Comment by srebhan** [comment]
Thanks for letting us know @KammutierSpule and @gone-for-coding and thanks for reporting the issue. As the unit-tests I added in the PR were able to reproduce your issue and the PR fixed the panics there we are going to merge and release Telegraf soon. In case you find some time to test over the weekend or so I would appreciate your feedback still.

**Comment by gone-for-coding** [comment]
@srebhan version 1.33.1 is now running for over 24h without an issue. The quick fix is highly appreciated!
