### ISSUE TITLE
Telegraf panics when StatsD plugin enabled

### ISSUE THREAD

**Issue by mclate** [influxdata/telegraf#1849]
When enabling StatsD pugin in telegraf, at some point it panics with division by zero error. This happens for v0.13 as well as for v1.0

```
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x621709 pc=0x621709]

goroutine 25 [running]:
panic(0x12cefe0, 0xc82000e0a0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).udpListen(0xc8200d4680, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/statsd/statsd.go:298 +0x7d9
created by github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).Start
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/statsd/statsd.go:261 +0x2a7
```

### Relevant telegraf.conf:

```
[[inputs.statsd]]
  service_address = ":8125"
  metric_separator = "_"
```

### System info:

```
OS: Ubuntu 14.04

Package: telegraf
Version: 1.0.0-1
License: MIT
Vendor: InfluxData
Maintainer: support@influxdb.com
Installed-Size: 40.0 MB
Homepage: https://github.com/influxdata/telegraf
Priority: extra
Section: default
Download-Size: 10.5 MB
APT-Manual-Installed: yes
APT-Sources: https://repos.influxdata.com/ubuntu/ trusty/stable amd64 Packages
Description: Plugin-driven server agent for reporting metrics into InfluxDB.
```

### Additional info:

There are consul (consul.io) and nomad (nomadproject.io) reporting to statsd on localhost

**Comment by sparrc** [comment]
you can workaround this by setting `allowed_pending_messages = 10000` in the configuration.

it'll be fixed in version 1.0.1: https://github.com/influxdata/telegraf/pull/1785
