### ISSUE TITLE
phpfpm module crashes when fastcgi endpoint is down

### ISSUE THREAD

**Issue by jeichorn** [influxdata/telegraf#1886]
## Bug report
Using fcgi urls in phpfpm causes telegraf to crash when the endpoint doesnt' exist

### Relevant telegraf.conf:
```
[phpfpm]
  urls = ["fcgi://127.0.0.1:48840/fpmstatus"]
```

### System info:
Telegraf 1.0.1, Ubuntu 16.04
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:
Add in a bad fcgi config, launch telegraf

## Expected behavior:
Not crashing

### Actual behavior:
Crashing

### Additional info:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5f0530]

goroutine 63 [running]:
panic(0x12ecf20, 0xc8200100c0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*conn).Request(0xc82060e090, 0xc8206080c0, 0xc8205b5c18, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /build/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/fcgi_client.go:40 +0x750
github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).gatherFcgi(0xc8200bfac0, 0xc82060e090, 0xc82021ebe8, 0x9, 0x7fd4ebce2840, 0xc82021e540, 0x0, 0x0)
        /build/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:163 +0x263
github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).gatherServer(0xc8200bfac0, 0xc82021ebd1, 0x20, 0x7fd4ebce2840, 0xc82021e540, 0x0, 0x0)
        /build/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:150 +0x75e
github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).Gather.func1(0xc82048bf30, 0xc82048bf40, 0xc8200bfac0, 0x7fd4ebce2840, 0xc82021e540, 0xc82021ebd1, 0x20)
        /build/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:89 +0x7b
created by github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).Gather
        /build/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:90 +0x1d1
```

**Comment by odoucet** [comment]
There is a regression and this bug happens again : if FPM status page does not exist / is unreachable, telegraf 1.24.2 failed to launch : 

```
panic: runtime error: index out of range [1] with length 1

goroutine 56 [running]:
github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).gatherServer(0x0?, {0xc0003ee931, 0x1d}, {0x67147a0, 0xc000e09340})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:120 +0x458
github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).Gather.func1({0xc0003ee931?, 0x0?})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:91 +0x7c
created by github.com/influxdata/telegraf/plugins/inputs/phpfpm.(*phpfpm).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/phpfpm/phpfpm.go:89 +0x1ed
```

```
# note here that port was forgotten
[[inputs.phpfpm]]
urls = [
      "fcgi://127.0.0.1/status",
    "fcgi://127.0.0.2/status",
    "fcgi://127.0.0.3/status",
    ]
```

**Comment by powersj** [comment]
@odoucet - Please do not comment on closed issues it is unhelpful. Additionally, this is not a regression, you have not followed the readme or configuration. It says the following when using the fcgi protocol:

```
  ##   - fcgi: the URL must start with fcgi:// or cgi://, and port must be present, ie:
```

You have left that port out. As soon as I add it I instead get:

```
2023-06-26T13:21:56Z E! [inputs.phpfpm] Error in plugin: dial tcp 127.0.0.3:9999: connect: connection refused
2023-06-26T13:21:56Z E! [inputs.phpfpm] Error in plugin: dial tcp 127.0.0.2:9900: connect: connection refused
2023-06-26T13:21:56Z E! [inputs.phpfpm] Error in plugin: dial tcp 127.0.0.1:9001: connect: connection refused
```

**Comment by odoucet** [comment]
Thanks for https://github.com/influxdata/telegraf/pull/13495/files , it is so much more helpful to have a clear error message than a Go error :)
