### ISSUE TITLE
Ticker error starting telegraf

### ISSUE THREAD

**Issue by rashtisouciance** [influxdata/telegraf#2270]
I run telegraf 1.1.1 and once I started it I got the following exception:

```
2017/01/13 14:29:25 E! FATAL: Input [inputs.netstat] panicked: non-positive interval for NewTicker, Stack:
goroutine 16 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244d20)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc42000d2f0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244d20, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244d20, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [semacquire]:
runtime.Stack(0xc4201c2800, 0x800, 0x800, 0xc4201c2801, 0x800)
        /usr/local/go/src/runtime/mprof.go:584 +0x11a
github.com/influxdata/tel
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2017/01/13 14:29:25 E! FATAL: Input [inputs.diskio] panicked: non-positive interval for NewTicker, Stack:
goroutine 12 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244ba0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc42000d350)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244ba0, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244ba0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [runnable]:
sync.runtime_Semacquire(0xc420052054)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420052050)
        /usr/local/go/src/syn
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2017/01/13 14:29:25 E! FATAL: Input [inputs.swap] panicked: non-positive interval for NewTicker, Stack:
goroutine 15 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244cc0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc42000d3f0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244cc0, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244cc0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [semacquire]:
sync.runtime_Semacquire(0xc420052054)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420052050)
        /usr/local/go/src/s
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2017/01/13 14:29:25 E! FATAL: Input [inputs.mem] panicked: non-positive interval for NewTicker, Stack:
goroutine 13 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244c00)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc42000d380)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244c00, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244c00, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [runnable]:
sync.runtime_Semacquire(0xc420052054)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420052050)
        /usr/local/go/src/syn
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2017/01/13 14:29:25 E! FATAL: Input [inputs.system] panicked: non-positive interval for NewTicker, Stack:
goroutine 14 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244c60)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc42000d3b0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244c60, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244c60, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [semacquire]:
sync.runtime_Semacquire(0xc420052054)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420052050)
        /usr/local/go/src/s
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2017/01/13 14:29:25 E! FATAL: Input [inputs.cpu] panicked: non-positive interval for NewTicker, Stack:
goroutine 10 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244ab0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc4200ed8c0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244ab0, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244ab0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [runnable]:
runtime.Stack(0xc4201c2800, 0x800, 0x800, 0xc4201c2801, 0x800)
        /usr/local/go/src/runtime/mprof.go:584 +0x11a
github.com/influxdata/teleg
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2017/01/13 14:29:25 E! FATAL: Input [inputs.disk] panicked: non-positive interval for NewTicker, Stack:
goroutine 11 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244b10)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:90 +0xc1
panic(0xef9680, 0xc4200ed870)
        /usr/local/go/src/runtime/panic.go:458 +0x243
time.NewTicker(0x0, 0x1140538)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420106080, 0xc42005c240, 0xc420244b10, 0x0, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:109 +0x8b
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc420244b10, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:381 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:382 +0x47b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000d2cc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42000d2c0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420106080, 0xc42005c240, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:385 +0x4be
main.reloadLoop(0xc4201028a0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:284 +0xcec
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x85

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 10 [runnable]:
github.com/influxdata/telegraf/agent.panicRecover(0xc420244ab0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/age
2017/01/13 14:29:25 E! PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
panic: non-positive interval for NewTicker

goroutine 9 [running]:
panic(0xef9680, 0xc4200ed990)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
time.NewTicker(0x0, 0x1140528)
        /usr/local/go/src/time/tick.go:23 +0x18d
github.com/influxdata/telegraf/agent.(*Agent).flusher(0xc420106080, 0xc42005c240, 0xc42005c4e0, 0xc4200f0770, 0x1141120)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:290 +0x10a
github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0xc42000d2c0, 0xc420106080, 0xc42005c240, 0xc42005c4e0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:355 +0x77
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:359 +0x300

```

Any idea what could be the problem? A parameter missing on the input plugin config? Or the agent?

**Comment by sparrc** [comment]
please provide config file

**Comment by sparrc** [comment]
also are you sure you are using 1.1.1? the traceback doesn't quite match that version

**Comment by rashtisouciance** [comment]
Ok I think I found the problem. I install telegraf via ansible and for some reason the units for some of the agent parameters hade 30ss rather than 30s which seems to have caused the issue. I'll close this.
