### ISSUE TITLE
Missing error handling in the MySQL plugin leads to segmentation violation

### ISSUE THREAD

**Issue by marieof9** [influxdata/telegraf#2414]
Upon start of telegraf it imminently exited with a segmentation violation.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x999806]

goroutine 52 [running]:
panic(0xf19ae0, 0xc420012050)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
database/sql.(*Rows).Next(0x0, 0x10a6d7f)
	/usr/local/go/src/database/sql/sql.go:1752 +0x26
github.com/influxdata/telegraf/plugins/inputs/mysql.(*Mysql).gatherGlobalStatuses(0xc420421420, 0xc420266210, 0xc42026c4b0, 0x4f, 0x18dfd20, 0xc420248e10, 0x0, 0xc420466730)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mysql/mysql.go:860 +0xf5c
github.com/influxdata/telegraf/plugins/inputs/mysql.(*Mysql).gatherServer(0xc420421420, 0xc42026c4b0, 0x4f, 0x18dfd20, 0xc420248e10, 0x0, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mysql/mysql.go:550 +0x155
github.com/influxdata/telegraf/plugins/inputs/mysql.(*Mysql).Gather.func1(0xc4200fb950, 0xc420114068, 0xc420421420, 0x18dfd20, 0xc420248e10, 0xc420053771, 0x44)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mysql/mysql.go:138 +0x89
created by github.com/influxdata/telegraf/plugins/inputs/mysql.(*Mysql).Gather
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mysql/mysql.go:139 +0x19a
```

The behaviour was triggered through miss configured file system permission. The query used to  gather connection metrics from process list would simply return an error instead of a result.

```
mysql> SELECT user, sum(1) FROM INFORMATION_SCHEMA.PROCESSLIST GROUP BY user;
ERROR 1 (HY000): Can't create/write to file '/tmp/#sql_418_0.MYI' (Errcode: 13 - Permission denied)
```

For the `SHOW GLOBAL STATUS` query there is an error detection after the query. However for the 
`GatherProcessList` and `GatherUserStatistics` this is missing and the non existent rows are iterated directly leading to a crash.

# Version Information
* Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)
* Ubuntu 14.04.5 LTS

**Comment by sparrc** [comment]
thanks for the report! will get this fixed for version 1.3.

if anyone else hits this, the workaround is to disable `gather_process_list` & `gather_user_statistics`
