### ISSUE TITLE
Fatal error on SIGWINCH

### ISSUE THREAD

**Issue by desa** [influxdata/telegraf#2539]
## Bug report
Got this in my logs randomly
```
2017-03-16T15:01:53Z I! Agent Config: Interval:1s, Quiet:false, Hostname:"Michaels-MBP-2.fios-router.home", Flush Interval:5s
ksignal 28 received on thread with no signal stack
fatal error: non-Go code disabled sigaltstack

goroutine 17 [running, locked to thread]:
runtime.throw(0x4d9a093, 0x20)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420040e60 sp=0xc420040e40
runtime.noSignalStack(0xc40000001c)
	/usr/local/go/src/runtime/signal1_unix.go:325 +0x94 fp=0xc420040e80 sp=0xc420040e60
runtime.call32(0x0, 0xc420051210, 0xc4200512bc, 0x4)
	/usr/local/go/src/runtime/asm_amd64.s:479 +0x4c fp=0xc420040eb0 sp=0xc420040e80
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:283 +0x19d fp=0xc420040f28 sp=0xc420040eb0
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:170 +0x84 fp=0xc420040f90 sp=0xc420040f28
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:728 +0x74 fp=0xc420040fb0 sp=0xc420040f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420040fb8 sp=0xc420040fb0

goroutine 1 [semacquire, 133 minutes]:
sync.runtime_Semacquire(0xc42035622c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc420356220)
	/usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420136030, 0xc420074120, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:400 +0x4de
main.reloadLoop(0xc420132600, 0x552e250, 0x0, 0x0, 0x552e250, 0x0, 0x0, 0x552e250, 0x0, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:214 +0xafe
main.main()
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:367 +0x650

goroutine 5 [syscall, 133 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 50 [select, 133 minutes, locked to thread]:
runtime.gopark(0x4e62c90, 0x0, 0x4d7432d, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc4201b7f30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc4201b7f30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 51 [select, 133 minutes]:
main.reloadLoop.func1(0xc420074180, 0xc420074120, 0xc4203480e0, 0xc420132600)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:175 +0x264
created by main.reloadLoop
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:189 +0x79f

goroutine 52 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher(0xc420136030, 0xc420074120, 0xc4200743c0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:297 +0x3e3
github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:370 +0x77
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:374 +0x320

goroutine 53 [runnable]:
runtime.gopark(0x4d6fccf, 0x2, 0xc400000002, 0xc420050c18, 0x402ffc7, 0x4d6fd8a)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 54 [runnable]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420136030, 0xc420074120, 0xc420012b80, 0x3b9aca00, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x37e
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0, 0xc420012b80, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 55 [runnable]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420136030, 0xc420074120, 0xc420012c40, 0x3b9aca00, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x37e
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0, 0xc420012c40, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 56 [select]:
github.com/influxdata/telegraf/agent.gatherWithTimeout(0xc420074120, 0xc420012d00, 0xc4200d8a20, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:157 +0x2a0
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420136030, 0xc420074120, 0xc420012d00, 0x3b9aca00, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:124 +0x280
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0, 0xc420012d00, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 57 [runnable]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420136030, 0xc420074120, 0xc420012e80, 0x3b9aca00, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x37e
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0, 0xc420012e80, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 58 [runnable]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420136030, 0xc420074120, 0xc420012f40, 0x3b9aca00, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x37e
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0, 0xc420012f40, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 59 [runnable]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420136030, 0xc420074120, 0xc420012fc0, 0x3b9aca00, 0xc4200743c0)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x37e
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc420356220, 0xc420136030, 0xc420074120, 0xc4200743c0, 0xc420012fc0, 0x3b9aca00)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7f
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x49b

goroutine 89 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher.func1(0xc4203a3af0, 0xc420074120, 0xc4201322a0, 0xc420136030)
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:263 +0x2fa
created by github.com/influxdata/telegraf/agent.(*Agent).flusher
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:292 +0xf4

goroutine 219 [select]:
net/http.(*persistConn).writeLoop(0xc420073100)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e

goroutine 218 [IO wait]:
net.runtime_pollWait(0x7106b40, 0x72, 0x8)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420348300, 0x72, 0xc4205c09d0, 0xc4200100a8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420348300, 0x542bce0, 0xc4200100a8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4203482a0, 0xc42041b000, 0x1000, 0x1000, 0x0, 0x542bce0, 0xc4200100a8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420314030, 0xc42041b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420073100, 0xc42041b000, 0x1000, 0x1000, 0x30, 0xc4205c0b58, 0x403ec8c)
	/usr/local/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc42014e480)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc42014e480, 0x1, 0x0, 0x1, 0x0, 0xc420518660, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420073100)
	/usr/local/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9

goroutine 188905 [select]:
net/http.setRequestCancel.func4(0x0, 0xc420775830, 0xc42075e180, 0xc4205185a0)
	/usr/local/go/src/net/http/client.go:329 +0x15a
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:337 +0x29f

goroutine 188863 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
	/Users/michaeldesa/go/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xd4

goroutine 188962 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
2017-03-16T17:15:17Z E! Error in plugin [inputs.system]: exit status 2
2017-03-16T18:24:59Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:24:59Z W! Skipping a scheduled flush because there is already a flush ongoing.
2017-03-16T18:25:00Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:25:00Z E! Error in plugin [inputs.swap]: took longer to collect than collection interval (1s)
2017-03-16T18:25:00Z E! Error in plugin [inputs.processes]: took longer to collect than collection interval (1s)
2017-03-16T18:25:01Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:25:01Z E! Error in plugin [inputs.processes]: took longer to collect than collection interval (1s)
2017-03-16T18:25:01Z E! Error in plugin [inputs.swap]: took longer to collect than collection interval (1s)
2017-03-16T18:25:02Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:25:02Z E! Error in plugin [inputs.processes]: took longer to collect than collection interval (1s)
2017-03-16T18:25:02Z E! Error in plugin [inputs.swap]: took longer to collect than collection interval (1s)
2017-03-16T18:25:03Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:25:03Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency=any&db=telegraf: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017-03-16T18:25:03Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2017-03-16T18:25:03Z E! Error in plugin [inputs.swap]: took longer to collect than collection interval (1s)
2017-03-16T18:25:03Z E! Error in plugin [inputs.processes]: took longer to collect than collection interval (1s)
2017-03-16T18:25:04Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:25:06Z E! Error in plugin [inputs.swap]: took longer to collect than collection interval (1s)
2017-03-16T18:25:06Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (1s)
2017-03-16T18:25:06Z E! Error in plugin [inputs.processes]: took longer to collect than collection interval (1s)
```

### Relevant telegraf.conf:
```
[global_tags]
[agent]
  interval = "1s"
  round_interval = true

  metric_batch_size = 1000
  metric_buffer_limit = 10000

  collection_jitter = "0s"

  flush_interval = "5s"
  flush_jitter = "0s"

  precision = ""
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false


[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  database = "telegraf" # required

  retention_policy = ""
  write_consistency = "any"

  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]


[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]

[[inputs.kernel]]


[[inputs.mem]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]
```
### System info:

```
OSX
Telegraf vdev-54-g45a168e (git: master 45a168e)
```

### Steps to reproduce:

1. No repro steps. It just happened randomly

**Comment by mark-rushakoff** [comment]
Looks related: https://github.com/golang/go/issues/18600

**Comment by danielnelson** [comment]
I just bumped version of Go in the official builds to 1.9, hopefully this solves the issue but let me know if you see it again. https://github.com/influxdata/telegraf/commit/a63f80e017721c3ca77b5e8e553d401224227d98
