### ISSUE TITLE
fatal error: stack growth after fork

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2585]
## Bug report

@ms7s has experienced this crash.  Appears to me to be originating from the system input.  Searched around a big and found this: https://walac.github.io/golang-patch/

### Relevant telegraf.conf:

[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/877079/telegraf.conf.txt)

### System info:
```
$ telegraf -version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
$ strings /usr/bin/telegraf | grep -E -o 'go1\.[0-9]+\.[0-9]+'
go1.7.5
```

Linux amd64

### Steps to reproduce:

Unknown

### Additional info:
```
fatal error: stack growth after fork
...[snip]...
goroutine 3317444 [syscall]:
syscall.Syscall(0x0, 0x13, 0xc4c38e5938, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.readlen(0x13, 0xc4c38e5938, 0x8, 0x4, 0xc4db85f8c0, 0x21)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1085 +0x56
syscall.forkExec(0x1083863, 0xc, 0xc5332d4750, 0x3, 0x3, 0xc4c38e5ad0, 0x1150f70, 0xc41766943a, 0xc4d6a601a0)
	/usr/local/go/src/syscall/exec_unix.go:202 +0x33e
syscall.StartProcess(0x1083863, 0xc, 0xc5332d4750, 0x3, 0x3, 0xc4c38e5ad0, 0x2, 0x4, 0x459b70, 0xc51ef231c0)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x64
os.startProcess(0x1083863, 0xc, 0xc5332d4750, 0x3, 0x3, 0xc4c38e5c78, 0xc505e65400, 0x20, 0x20)
	/usr/local/go/src/os/exec_posix.go:45 +0x1a3
os.StartProcess(0x1083863, 0xc, 0xc5332d4750, 0x3, 0x3, 0xc4c38e5c78, 0x0, 0x0, 0x6)
	/usr/local/go/src/os/doc.go:28 +0x64
os/exec.(*Cmd).Start(0xc50128f760, 0x1083801, 0xc4db891f90)
	/usr/local/go/src/os/exec/exec.go:358 +0x3c9
os/exec.(*Cmd).Run(0xc50128f760, 0xc4db891f90, 0x2)
	/usr/local/go/src/os/exec/exec.go:276 +0x2b
os/exec.(*Cmd).Output(0xc50128f760, 0xc, 0xc4c38e5da8, 0x2, 0x2, 0xc50128f760)
	/usr/local/go/src/os/exec/exec.go:473 +0x136
github.com/shirou/gopsutil/internal/common.DoSysctrl(0x1092619, 0x15, 0xc4cdf82f50, 0x1, 0x1, 0x18ec040, 0xc5332d4720)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/internal/common/common_linux.go:20 +0x1d4
github.com/shirou/gopsutil/host.Info(0xc533298460, 0x0, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/host/host_linux.go:78 +0x1d8
github.com/influxdata/telegraf/plugins/inputs/system.(*SystemStats).Gather(0x19c6638, 0x18faca0, 0xc4c3908020, 0xebfa80, 0xc509498900)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/system.go:30 +0x55
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc4db89c8a0, 0xc420114d80, 0xc4c3908020)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x49
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xef
```

[Full Stack](https://github.com/influxdata/telegraf/files/877078/stack-growth-after-fork.txt)

**Comment by danielnelson** [comment]
I believe this problem has been fixed by new Go releases.
