### ISSUE TITLE
SIGSEGV: segmentation violation in diskio input

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2586]
## Bug report
@ms7s has experienced this crash.  Appears to be originating from the diskio input.
### Relevant telegraf.conf:

[telegraf.conf.txt](https://github.com/influxdata/telegraf/files/877100/telegraf.conf.txt)

### System info:
```
$ telegraf -version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
$ strings /usr/bin/telegraf | grep -E -o 'go1\.[0-9]+\.[0-9]+'
go1.7.5
```

Linux amd64

### Steps to reproduce:

Unknown

### Additional info:
```
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc4c40972a0 pc=0xc4c40972a0]

goroutine 3317174 [running]:
runtime.throw(0x1078ccc, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4c4097200 sp=0xc4c40971e0
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4c4097258 sp=0xc4c4097200
sync.(*RWMutex).Unlock(0xf)
	/usr/local/go/src/sync/rwmutex.go:115 +0x26 fp=0xc4c40972b0 sp=0xc4c4097258
syscall.forkExec(0x108507e, 0xd, 0xc53008a3c0, 0x4, 0x4, 0xc4c40974c8, 0x1150f70, 0xc417650dfa, 0xc4c10b9040)
	/usr/local/go/src/syscall/exec_unix.go:202 +0x33e fp=0xc4c40973e0 sp=0xc4c40972b0
syscall.StartProcess(0x108507e, 0xd, 0xc53008a3c0, 0x4, 0x4, 0xc4c40974c8, 0x2, 0x4, 0x459b70, 0xc4b0a5c5c0)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x64 fp=0xc4c4097438 sp=0xc4c40973e0
os.startProcess(0x108507e, 0xd, 0xc53008a3c0, 0x4, 0x4, 0xc4c4097670, 0xc5335ea000, 0x20, 0x20)
	/usr/local/go/src/os/exec_posix.go:45 +0x1a3 fp=0xc4c4097520 sp=0xc4c4097438
os.StartProcess(0x108507e, 0xd, 0xc53008a3c0, 0x4, 0x4, 0xc4c4097670, 0x0, 0x0, 0x1150f71)
	/usr/local/go/src/os/doc.go:28 +0x64 fp=0xc4c4097578 sp=0xc4c4097520
os/exec.(*Cmd).Start(0xc4c749f340, 0xc530047dc0, 0xc4c749f340)
	/usr/local/go/src/os/exec/exec.go:358 +0x3c9 fp=0xc4c40976c8 sp=0xc4c4097578
github.com/shirou/gopsutil/internal/common.CombinedOutputTimeout(0xc4c749f340, 0xb2d05e00, 0xc530081bf0, 0x3, 0x3, 0xc4c749f340, 0xc420272000)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/internal/common/common.go:315 +0x9d fp=0xc4c4097700 sp=0xc4c40976c8
github.com/shirou/gopsutil/internal/common.Invoke.Command(0x108507e, 0xd, 0xc530081bf0, 0x3, 0x3, 0x414b18, 0x30, 0xed81e0, 0x1, 0xc530081bf0)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/internal/common/common.go:40 +0x71 fp=0xc4c4097748 sp=0xc4c4097700
github.com/shirou/gopsutil/internal/common.(*Invoke).Command(0x19c6638, 0x108507e, 0xd, 0xc530081bf0, 0x3, 0x3, 0xb, 0x17baaad733f4f60, 0xd, 0xe, ...)
	<autogenerated>:8 +0x88 fp=0xc4c40977a8 sp=0xc4c4097748
github.com/shirou/gopsutil/disk.GetDiskSerialNumber(0xc4c6fcf86d, 0x4, 0x0, 0x40)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/disk/disk_linux.go:368 +0x1e2 fp=0xc4c4097878 sp=0xc4c40977a8
github.com/shirou/gopsutil/disk.IOCounters(0xc4ddc8c438, 0x493ff0, 0xffffffffffffff9c)
	/home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/disk/disk_linux.go:353 +0x690 fp=0xc4c4097bc8 sp=0xc4c4097878
github.com/influxdata/telegraf/plugins/inputs/system.(*systemPS).DiskIO(0x19c6638, 0x482fe0, 0x10806b0, 0xa)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/ps.go:124 +0x26 fp=0xc4c4097c18 sp=0xc4c4097bc8
github.com/influxdata/telegraf/plugins/inputs/system.(*DiskIOStats).Gather(0xc4202890b0, 0x18faca0, 0xc4c38c2d80, 0xebfa80, 0xc539b831a0)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/disk.go:106 +0x4b fp=0xc4c4097f40 sp=0xc4c4097c18
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc4c40be6c0, 0xc420114c80, 0xc4c38c2d80)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x49 fp=0xc4c4097f88 sp=0xc4c4097f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4c4097f90 sp=0xc4c4097f88
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xef
```
[Full Stack](https://github.com/influxdata/telegraf/files/877104/telegraf-panic.txt)

**Comment by danielnelson** [comment]
Have not seen this reported in some time, assuming it was fixed upstream.
