### ISSUE TITLE
Intermittent hang in logparser tests

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2648]
## Bug report
There is an intermittent hang in the leofs input's tests.

### System info:

Telegraf 1.3.0 dev
07c428ef89e225a480a7835f32890f4db3cd534d

### Steps to reproduce:

1. Run tests

### Expected behavior:
Test Passes

### Actual behavior:
Test Hangs

### Additional info:
```
ok  	github.com/influxdata/telegraf/plugins/inputs/leofs	1.746s
2017/04/10 22:41:58 Seeked /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/logparser/grok/testdata/test_a.log - &{Offset:0 Whence:0}
2017/04/10 22:41:58 Seeked /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/logparser/grok/testdata/test_b.log - &{Offset:0 Whence:0}
SIGQUIT: quit
PC=0x49999a m=0 sigcode=0

goroutine 20 [syscall]:
syscall.Syscall6(0xe8, 0x8, 0xc42002b45c, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x4663f9, 0xc420172ca8, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5 fp=0xc42002b378 sp=0xc42002b370
syscall.EpollWait(0x8, 0xc42002b45c, 0x7, 0x7, 0xffffffffffffffff, 0xc42002b460, 0xc420020000, 0x1)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:365 +0x8b fp=0xc42002b3f8 sp=0xc42002b378
github.com/influxdata/tail/vendor/gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc4202da080, 0x87a700, 0xc4202da080, 0x42c93c)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/tail/vendor/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0xb7 fp=0xc42002b4f0 sp=0xc42002b3f8
github.com/influxdata/tail/vendor/gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc420062140)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/tail/vendor/gopkg.in/fsnotify.v1/inotify.go:179 +0x260 fp=0xc42002b7d8 sp=0xc42002b4f0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42002b7e0 sp=0xc42002b7d8
created by github.com/influxdata/tail/vendor/gopkg.in/fsnotify%2ev1.NewWatcher
	/home/ubuntu/telegraf-build/src/github.com/influxdata/tail/vendor/gopkg.in/fsnotify.v1/inotify.go:58 +0x394

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420064dd0, 0x86c1ec, 0x15, 0x87a7e8, 0xc4200c7c01)
	/usr/local/go/src/testing/testing.go:698 +0x582
testing.runTests.func1(0xc420064dd0)
	/usr/local/go/src/testing/testing.go:882 +0xab
testing.tRunner(0xc420064dd0, 0xc4200c7d78)
	/usr/local/go/src/testing/testing.go:657 +0x108
testing.runTests(0xc4200f1640, 0xa32980, 0x5, 0x5, 0x0)
	/usr/local/go/src/testing/testing.go:888 +0x4e1
testing.(*M).Run(0xc4200c7f28, 0xc4200c7ed0)
	/usr/local/go/src/testing/testing.go:822 +0x1c4
main.main()
	github.com/influxdata/telegraf/plugins/inputs/logparser/_test/_testmain.go:50 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [semacquire]:
sync.runtime_notifyListWait(0xc420265cd0, 0xc400000000)
	/usr/local/go/src/runtime/sema.go:297 +0x11a
sync.(*Cond).Wait(0xc420265cc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/influxdata/telegraf/testutil.(*Accumulator).Wait(0xc420172c00, 0x2)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/testutil/accumulator.go:211 +0xa2
github.com/influxdata/telegraf/plugins/inputs/logparser.TestGrokParseLogFiles(0xc4201be680)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/logparser/logparser_test.go:62 +0x4c6
testing.tRunner(0xc4201be680, 0x87a7e8)
	/usr/local/go/src/testing/testing.go:657 +0x108
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x544

goroutine 7 [select]:
github.com/influxdata/telegraf/plugins/inputs/logparser.(*LogParserPlugin).parser(0xc420185180)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/logparser/logparser.go:214 +0x54b
created by github.com/influxdata/telegraf/plugins/inputs/logparser.(*LogParserPlugin).Start
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/logparser/logparser.go:132 +0x7f1

goroutine 19 [select]:
github.com/influxdata/tail/watch.(*InotifyTracker).run(0xc4202d81c0)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/tail/watch/inotify_tracker.go:237 +0x61d
created by github.com/influxdata/tail/watch.glob..func1
	/home/ubuntu/telegraf-build/src/github.com/influxdata/tail/watch/inotify_tracker.go:54 +0x32a

rax    0xfffffffffffffffc
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x7
rdi    0x8
rsi    0xc42002b45c
rbp    0xc42002b3e8
rsp    0xc42002b370
r8     0x0
r9     0x0
r10    0xffffffffffffffff
r11    0x202
r12    0xc42002b368
r13    0xa37020
r14    0xc420060340
r15    0x0
rip    0x49999a
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
```

https://circleci.com/gh/influxdata/telegraf/6548

**Comment by danielnelson** [comment]
Similar issue with tail https://circleci.com/gh/influxdata/telegraf/6597

**Comment by danielnelson** [comment]
Haven't seen this for a long time, closing.
