### ISSUE TITLE
SIGSEGV with socket_writer on shutdown if could not write

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2746]
### Relevant telegraf.conf:
```toml
[[outputs.socket_writer]]
  address = "udp://127.0.0.1:8099"
```

### System info:

6e76731b

### Steps to reproduce:

1. Start Telegraf with nothing listening to udp address
2. Send SIGINT to initiate shutdown

### Expected behavior:

Clean shutdown

### Actual behavior:
```
2017-05-02T01:17:15Z E! Error writing to output [socket_writer]: write udp 127.0.0.1:56307->127.0.0.1:8099: write: connection refused
^C2017-05-02T01:17:15Z I! Hang on, flushing any cached metrics before shutdown
2017-05-02T01:17:15Z E! Error writing to output [socket_writer]: write udp 127.0.0.1:34613->127.0.0.1:8099: write: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1052c5c]

goroutine 1 [running]:
github.com/influxdata/telegraf/plugins/outputs/socket_writer.(*SocketWriter).Close(0xc4200198c0, 0x1aff960, 0xc42014c100)
        <autogenerated>:3 +0x3c
github.com/influxdata/telegraf/agent.(*Agent).Close(0xc42016c040, 0x13f19e0, 0xc42014ff80)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/agent/agent.go:77 +0x66
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc42016c040, 0xc420168cc0, 0x0, 0x0)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/agent/agent.go:401 +0x4c4
main.reloadLoop(0xc4201687e0, 0x1c0b6b0, 0x0, 0x0, 0x1c0b6b0, 0x0, 0x0, 0x1c0b6b0, 0x0, 0x0, ...)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:222 +0xa06
main.main()
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:392 +0x65b
```

**Comment by phemmer** [comment]
> write udp 127.0.0.1:56307->127.0.0.1:8099: write: connection refused

What? How?
"udp", "connection". Those 2 things don't go together.

I'm also unable to reproduce:

```
[[outputs.socket_writer]]
  address = "udp://127.0.0.1:1234"

[[outputs.file]]
  files = ["stdout"]

[[inputs.exec]]
  commands = ["echo foo v=1i"]
  data_format = "influx"
```

```
# ./telegraf -config telegraf.conf 
2017-05-02T02:00:11Z I! Starting Telegraf (version )
2017-05-02T02:00:11Z I! Loaded outputs: socket_writer file
2017-05-02T02:00:11Z I! Loaded inputs: inputs.exec
2017-05-02T02:00:11Z I! Tags enabled: host=fll1000539l
2017-05-02T02:00:11Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"fll1000539l", Flush Interval:1s 
foo,host=fll1000539l v=1i 1493690420000000000
^C2017-05-02T02:00:28Z I! Hang on, flushing any cached metrics before shutdown

#
```

**Comment by danielnelson** [comment]
I seem to recall something about getting a error code on the next send if you call connect on a datagram socket and you are sending to loopback or maybe on the local network segment... can't really remember.

**Comment by danielnelson** [comment]
I still get it with your config:
```
2017-05-02T02:10:21Z I! Agent Config: Interval:5s, Quiet:false, Hostname:"loaner", Flush Interval:5s 
foo,host=loaner v=1i 1493691025000000000
foo,host=loaner v=1i 1493691030000000000
2017-05-02T02:10:30Z E! Error writing to output [socket_writer]: write udp 127.0.0.1:43138->127.0.0.1:1234: write: connection refused
foo,host=loaner v=1i 1493691035000000000
```

**Comment by phemmer** [comment]
What OS, kernel version, and go version is it built with?

**Comment by danielnelson** [comment]
```
$ go version
go version go1.8.1 linux/amd64
$ uname -a
Linux loaner 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux
```

**Comment by danielnelson** [comment]
Error remains when sending to another computer on my LAN, but is gone when I send out to the internet.

**Comment by danielnelson** [comment]
From `man 7 udp`:
>    Error handling
       All  fatal  errors  will  be passed to the user as an error return even
       when the socket is not connected.  This  includes  asynchronous  errors
       received  from the network.  You may get an error for an earlier packet
       that was sent on the same socket.   This  behavior  differs  from  many
       other BSD socket implementations which don't pass any errors unless the
       socket is connected.  Linux's behavior is mandated by RFC 1122.

**Comment by danielnelson** [comment]
This page is pretty good too: http://www.softlab.ntua.gr/facilities/documentation/unix/unix-socket-faq/unix-socket-faq-5.html

**Comment by phemmer** [comment]
Ok, was finally able to reproduce the panic (i could reproduce the error, but not the panic). Seems to require both Linux & Go 1.8.1. Had a build from 1.8.0 and could not reproduce, nor 1.8.1 on OS-X.
