### ISSUE TITLE
Panic in exec input if wrong type for command option.

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2810]
## Bug report

If you set the `command` option to an array in the exec plugin, Telegraf panics on startup.  The `command` option should be a string, while the `commands` option is an array.

### Relevant telegraf.conf:
```toml
[[inputs.exec]]
   command = ["./foo.sh"]
   data_format = "influx"
```

### System info:

bfeb3020a32b8bd965f65b1b44a91bb9363c8519

### Steps to reproduce:

1. Set command as an array.
2. Start telegraf

### Expected behavior:

Error stating command should be a string.

### Actual behavior:
```
2017/05/15 13:16:46 I! Using config file: /home/dbn/.telegraf/telegraf.conf
panic: reflect.MakeSlice of non-slice type

goroutine 1 [running]:
reflect.MakeSlice(0x1b0a960, 0x1150660, 0x0, 0x1, 0x1150660, 0xc420334d88, 0xc420328ad0)
        /usr/lib/go-1.8/src/reflect/value.go:2049 +0x2ab
github.com/influxdata/toml.setArray(0x1150660, 0xc420334d88, 0x198, 0xc42015b240, 0xc, 0x0)
        /home/dbn/src/influx/src/github.com/influxdata/toml/decode.go:347 +0x216
github.com/influxdata/toml.setValue(0x1150660, 0xc420334d88, 0x198, 0x1afaec0, 0xc42015b240, 0x1150660, 0xc420334d88)
        /home/dbn/src/influx/src/github.com/influxdata/toml/decode.go:266 +0x52c
github.com/influxdata/toml.UnmarshalTable(0xc420334d20, 0x1237040, 0xc420334d70, 0xc4201c4000, 0x0)
        /home/dbn/src/influx/src/github.com/influxdata/toml/decode.go:127 +0xe90
github.com/influxdata/telegraf/internal/config.(*Config).addInput(0xc4201f61e0, 0xc420153d80, 0x4, 0xc420334d20, 0x1c0d8e0, 0x0)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/internal/config/config.go:827 +0x16b
github.com/influxdata/telegraf/internal/config.(*Config).LoadConfig(0xc4201f61e0, 0xc420445f40, 0x1e, 0xc4205237c0, 0x434d8e)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/internal/config/config.go:633 +0x743
github.com/influxdata/telegraf/internal/config.(*Config).LoadDirectory.func1(0xc420445f40, 0x1e, 0x1b04ce0, 0xc420103110, 0x0, 0x0, 0x0, 0x0)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/internal/config/config.go:523 +0x113
path/filepath.walk(0xc420445f40, 0x1e, 0x1b04ce0, 0xc420103110, 0xc420153c40, 0x0, 0x0)
        /usr/lib/go-1.8/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0x7ffc89f49dcc, 0xe, 0x1b04ce0, 0xc42001fe10, 0xc420153c40, 0x0, 0x10)
        /usr/lib/go-1.8/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0x7ffc89f49dcc, 0xe, 0xc420153c40, 0x4000106, 0x0)
        /usr/lib/go-1.8/src/path/filepath/path.go:398 +0x14c
github.com/influxdata/telegraf/internal/config.(*Config).LoadDirectory(0xc4201f61e0, 0x7ffc89f49dcc, 0xe, 0x0, 0x0)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/internal/config/config.go:529 +0x7b
main.reloadLoop(0xc4202be060, 0x1c0c6b0, 0x0, 0x0, 0x1c0c6b0, 0x0, 0x0, 0x1c0c6b0, 0x0, 0x0, ...)
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:142 +0xf24
main.main()
        /home/dbn/src/influx/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:392 +0x65b
```

### Additional info:

N/A

**Comment by DanKans** [comment]
The easiest way, will be permanently removing support for legacy single command input. It is used only in exec.go (179 - 183) to add this single command to array. 
```
	// Legacy single command support
	if e.Command != "" {
		e.Commands = append(e.Commands, e.Command)
		e.Command = ""
	}
``` 
In case when someone will use `command` after change, this output will be produced for him:

```
2017/07/17 12:21:13 E! Error parsing fluentd_issue_2810.conf, line 2: field corresponding to `command' is not defined in `*exec.Exec'
```

If this is not an option, IMHO the best way to fix it is to create some general validator in `internal/config.go -> addInput` just before we do `if err := toml.UnmarshalTable(table, input); err != nil {`.

btw. there was a proposal to write validation on [toml side](https://github.com/naoina/toml/issues/8)
Let me know what do you think. 
Thanks!

**Comment by danielnelson** [comment]
I think this is a more general error that could occur anytime you unmarshal into a string if the config contains a list.  This appears to be fixed in the latest naoina/toml, but we are using a fork which has quite a few changes from upstream.

I'm working on an update in the way we load configuration, and I might switch to a different toml library as part of it, so I think we should hold off on this one until #272 is complete.

**Comment by DanKans** [comment]
@danielnelson agree, the best way is to fix it on library level.

**Comment by sjwang90** [comment]
We'd welcome any PRs from the community that would address this bug.

**Comment by sjwang90** [comment]
Blocked by #272

**Comment by powersj** [comment]
The panic no longer exist and instead, users are given:

```
2022-01-20T16:23:37Z E! [telegraf] Error running agent: Error loading config file config.toml: error parsing exec, line 2: (exec.Exec.Command) cannot unmarshal TOML array into string (need slice)
```

Closing.
