### ISSUE TITLE
Telegraf for x86 windows crash.

### ISSUE THREAD

**Issue by mopsld** [influxdata/telegraf#2826]
Hello. 

I have downloaded new version (1.3) of telegraf for windows x86.(https://dl.influxdata.com/telegraf/releases/telegraf-1.3.0_windows_i386.zip)

And I install that extracted files(telegraf.conf, telegraf.exe) and run that binary but it will crash with this logs.

Telegraf.conf is works for x64 windows binary.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd\

C:\>cd "Program Files"

C:\Program Files>cd Telegraf

C:\Program Files\Telegraf>telegraf.exe
2017/07/22 23:29:29 I! Using config file: C:\Program Files\Telegraf\telegraf.conf
unexpected fault address 0x1f854474
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x1f854474 pc=0x46a2a9]

goroutine 28 [running]:
runtime.throw(0x106a067, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x7c fp=0x13447ec0 sp=0x13447eb4
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:164 +0xe2 fp=0x13447ed4 sp=0x13447ec0
syscall.UTF16ToString(0x1f854474, 0x20000000, 0x20000000, 0x16e4220, 0x13468b90)
        /usr/local/go/src/syscall/syscall_windows.go:49 +0x29 fp=0x13447ef0 sp=0x13447ed4
github.com/influxdata/telegraf/plugins/inputs/win_perf_counters.UTF16PtrToString(0x1f854474, 0x13423ee0, 0x7)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/plugins/inputs/win_perf_counters/pdh.go:421 +0x35 fp=0x1
3447f08 sp=0x13447ef0
github.com/influxdata/telegraf/plugins/inputs/win_perf_counters.(*Win_PerfCounters).Gather(0x134c2ca0, 0x16de5e0, 0x1342
d1a0, 0x0, 0x0)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/plugins/inputs/win_perf_counters/win_perf_counters.go:25
5 +0x2a1 fp=0x13447fc0 sp=0x13447f08
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0x134506c0, 0x134c38a0, 0x1342d1a0)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x38 fp=0x13447fe0 sp=0x13447fc0
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1629 +0x1 fp=0x13447fe4 sp=0x13447fe0
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xba

goroutine 1 [chan receive]:
github.com/kardianos/service.(*windowsService).Run(0x1342c820, 0x13505440, 0x137d00c0)
        /root/Projects/Proj1/src/github.com/kardianos/service/service_windows.go:273 +0x127
main.main()
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:379 +0x98d

goroutine 26 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher(0x135ce3a8, 0x1342a840, 0x1342a9c0, 0x0, 0x1)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:297 +0x305
github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0x134ef200, 0x135ce3a8, 0x1342a840, 0x1342a9c0)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:370 +0x5b
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:374 +0x25c

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x14f
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 4 [semacquire]:
sync.runtime_Semacquire(0x134ef20c)
        /usr/local/go/src/runtime/sema.go:47 +0x29
sync.(*WaitGroup).Wait(0x134ef200)
        /usr/local/go/src/sync/waitgroup.go:131 +0x91
github.com/influxdata/telegraf/agent.(*Agent).Run(0x135ce3a8, 0x1342a840, 0x0, 0x0)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:400 +0x3e5
main.reloadLoop(0x1342a240, 0x17cdf34, 0x0, 0x0, 0x17cdf34, 0x0, 0x0, 0x17cdf34, 0x0, 0x0, ...)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:222 +0x866
main.(*program).run(0x13505440)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:250 +0xdc
created by main.(*program).Start
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:239 +0x33

goroutine 12 [select]:
main.reloadLoop.func1(0x1342a880, 0x1342a840, 0x1342a280, 0x1342a240)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:183 +0x1d5
created by main.reloadLoop
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:197 +0x5aa

goroutine 27 [select]:
github.com/influxdata/telegraf/agent.gatherWithTimeout(0x1342a840, 0x134c38a0, 0x1342d1a0, 0x540be400, 0x2)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:157 +0x234
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0x135ce3a8, 0x1342a840, 0x134c38a0, 0x540be400, 0x2, 0x1342a9c0)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:124 +0x2a4
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0x134ef200, 0x135ce3a8, 0x1342a840, 0x1342a9c0, 0x134c38a0, 0x54
0be400, 0x2)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x6b
created by github.com/influxdata/telegraf/agent.(*Agent).Run
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:397 +0x3b0

goroutine 13 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher.func1(0x134ef230, 0x1342a840, 0x1342aa00, 0x135ce3a8)
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:263 +0x25c
created by github.com/influxdata/telegraf/agent.(*Agent).flusher
        /root/Projects/Proj1/src/github.com/influxdata/telegraf/agent/agent.go:292 +0xc6

C:\Program Files\Telegraf>
```

**Comment by danielnelson** [comment]
It looks that this is the same issues as #2468.

**Comment by mopsld** [comment]
Thank you.

**Comment by ronnix** [comment]
FYI, the default configuration enables `win_perf_counter` plugins, which works fine on 64-bit Windows, but causes a crash on 32-bit Windows (see #2468).

A workaround is to comment all the `[[inputs.win_perf_counters.*]]` sections, and to uncomment the following sections:
```
[[inputs.cpu]]
[[inputs.disk]]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.swap]]
```

Maybe changing the default config shipped with the 32-bit build would prevent this bad out-of-the-box experience?
