### ISSUE TITLE
Minecraft plugin panic

### ISSUE THREAD

**Issue by goller** [influxdata/telegraf#2961]
## Bug report
I got this Minecraft plugin panic after turning on my laptop after several hours.  
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x4804de3]

goroutine 4542 [running]:
github.com/influxdata/telegraf/plugins/inputs/minecraft/internal/rcon.(*Client).Send(0xc42040e210, 0xc400000003, 0xc42022a0e1, 0x9, 0x0, 0x0, 0x40c308a)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/minecraft/internal/rcon/rcon.go:137 +0x1d3
github.com/influxdata/telegraf/plugins/inputs/minecraft/internal/rcon.(*Client).Authorize(0xc42040e210, 0xc42022a0e1, 0x9, 0x5, 0x4012eac, 0xc4202b2068)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/minecraft/internal/rcon/rcon.go:93 +0x4b
github.com/influxdata/telegraf/plugins/inputs/minecraft.(*RCON).Gather(0xc4201a6340, 0x437cbc1, 0x4fdb889, 0x31, 0xc4208fdf28, 0x3)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/minecraft/rcon.go:65 +0x5a
github.com/influxdata/telegraf/plugins/inputs/minecraft.(*Minecraft).Gather(0xc420017040, 0x5739980, 0xc420190340, 0x40344f8, 0x5019840)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/minecraft/minecraft.go:60 +0x69
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc420074240, 0xc4200170c0, 0xc420190340)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x49
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xcc
```
### System info:
telegraf @ 22fc130e97306e8d061893db64daa394467fce14
mac

**Comment by danielnelson** [comment]
#2970
