### ISSUE TITLE
Runtime error 'index out of range' while gathering CPUStats

### ISSUE THREAD

**Issue by heshsmurf** [influxdata/telegraf#3282]
## Bug report
I'm running telegraf on node and it fails after a while.

```
panic: runtime error: index out of range

goroutine 680 [running]:
github.com/influxdata/telegraf/plugins/inputs/system.(*CPUStats).Gather(0xc420294ff0, 0x1c2b160, 0xc42040c480, 0x11e5d80, 0xc4209ec600)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/cpu.go:89 +0x1260
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc420413140, 0xc420127300, 0xc42040c480)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x49
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:154 +0xcc
```
### Relevant telegraf.conf:
```
[[inputs.cpu]]
  percpu = true
  totalcpu = false
  collect_cpu_time = false
  report_active = false
```
### System info:
Telegraf v1.4.1, Linux version 4.4.0-96-generic (buildd@lgw01-10)

### Steps to reproduce:
1. Start telegraf as a daemon

**Comment by danielnelson** [comment]
I can see where this would fail if the number of CPUs in `/proc/stat` changed over time, is this something that is possibly happening?

**Comment by heshsmurf** [comment]
Actually I run telegraf on virtual machine, so that behavior seems possible

**Comment by danielnelson** [comment]
Interesting, can I ask which hypervisor you are using?

**Comment by heshsmurf** [comment]
VM is running under LXC
