### ISSUE TITLE
mssql plugin input: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rbucchi** [influxdata/telegraf#3298]
### Relevant telegraf.conf:

```
[[inputs.sqlserver]]
   ## Specify instances to monitor with a list of connection strings.
   ## All connection parameters are optional.
   ## By default, the host is localhost, listening on default port, TCP 1433.
   ##   for Windows, the user is the currently running AD user (SSO).
   ##   See https://github.com/denisenkom/go-mssqldb for detailed connection
   ##   parameters.
    servers = [
     "Server=10.0.75.1\\sqlexpress;User Id=telegraf;Password=***;database=***;conn
ection timeout=100;log=63;",
    ]
```

### System info:

[Include Telegraf version, operating system name, and other relevant details]

Windows 10, docker Version 17.06.2-ce-win27 (13194) Channel: stable.
SqlServer (on host): MSSQL13.SQLEXPRESS
Telegraf:
```
root@97d76358cacb:~# telegraf --version
Telegraf v1.2.0 (git: release-1.2 b2c1d98cff5a58d5ded3e74741c6bc32d6e789ee)
```
InfluxDB:
```
ii  influxdb                1.2.0-1          amd64            Distributed time-series database.
```
Container:
```
root@97d76358cacb:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```
### Steps to reproduce:

1. run
```
docker run -d \
  --name docker-statsd-influxdb-grafana \
  -p 3003:3003 \
  -p 3004:8083 \
  -p 8086:8086 \
  -p 22022:22 \
  -p 8125:8125/udp \
  samuelebistoletti/docker-statsd-influxdb-grafana:latest
```
2. configure Grant as wiki
3. Configure telegraf.conf as mentioned. I used docker gw as configuration and I got correct connection.
```
root@97d76358cacb:~# telnet 10.0.75.1 1433
Trying 10.0.75.1...
Connected to 10.0.75.1.
Escape character is '^]'.
```

### Expected behavior:

Collect data

### Actual behavior:

it panic: 

```
2017-10-03T08:00:45Z I! Statsd listener listening on:  [::]:8125
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x654edb]

goroutine 88 [running]:
panic(0xf2a2e0, 0xc420010100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/client/v2.(*client).Write(0xc4201960c0, 0x18fd660, 0xc4205a8000, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/influxdb/client/v2/client.go:354 +0xfb
github.com/influxdata/telegraf/plugins/outputs/influxdb.(*InfluxDB).Write(0xc4200d0300, 0xc42056c000, 0x3e8, 0x3e8, 0xc4200445a0
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/outputs/influxdb/influxdb.go:202 +0x27b
github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc4201c4820, 0xc42056c000, 0x3e8, 0x3e8, 0x3e8, 0x2)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:170 +0xa1
github.com/influxdata/telegraf/internal/models.(*RunningOutput).AddMetric(0xc4201c4820, 0x18ff3a0, 0xc420679b80)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:112 +0x149
github.com/influxdata/telegraf/agent.(*Agent).flusher.func1(0xc42070daf0, 0xc42006e1e0, 0xc420730d20, 0xc420068038)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:278 +0x1e7
created by github.com/influxdata/telegraf/agent.(*Agent).flusher
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:286 +0xee
```

**Comment by danielnelson** [comment]
Are you able to test with Telegraf 1.4.1?

**Comment by rbucchi** [comment]
it works with Telegraf 1.4.1, thanks.
