### ISSUE TITLE
deadlock if influxdb output server is unreachable

### ISSUE THREAD

**Issue by anatolijd** [influxdata/telegraf#3397]
## Bug report

If Telegraf starts and InfluxDB output server is not reachable at that moment - Telegraf will not  write to that InfluxDB output until restarted.

A have several servers where Telegraf agent has been started during InfluxDB cluster downtime.
Those Telegraf agents are still not sending any data to influxdb output, despite the cluster went back online more than 3 hours before now.

Seems to be a dead lock  somewhere.

### Relevant telegraf.conf:

```
root:~ # cat /etc/telegraf/telegraf.conf 
[agent]
flush_interval = "60s"
flush_jitter = "5s"
interval = "60s"
round_interval = true
[tags]

root:~# cat /etc/telegraf/telegraf.d/*
[inputs.cpu]
drop = ["cpu_time"]
percpu = true
totalcpu = true
[inputs.disk]
[inputs.io]
[inputs.mem]
[inputs.net]
[inputs.swap]
[inputs.system]
[[outputs.influxdb]]
database = "telegraf"
precision = "s"
timeout = "5s"
urls = ["http://influxdb-write:8086"]
[[inputs.procstat]]
  pattern = "java.*ha_analyzer"
  process_name = "ha_analyzer"
  fielddrop = ["cpu_time_*"]
```

telegraf version: 1.4.0
OS: Ubuntu 14.04.5 LTS
InfluxDB cluster: 1.3.6

### Additional info:

SIGQUIT stack trace:

```
2017-10-27T03:57:14Z I! Starting Telegraf v1.4.0
2017-10-27T03:57:14Z I! Loaded outputs: influxdb
2017-10-27T03:57:14Z I! Loaded inputs: inputs.cpu inputs.disk inputs.diskio inputs.mem inputs.net inputs.swap inputs.system inputs.procstat
2017-10-27T03:57:14Z I! Tags enabled: host=ip-172-20-49-11
2017-10-27T03:57:14Z I! Agent Config: Interval:1m0s, Quiet:false, Hostname:"ip-172-20-49-11", Flush Interval:1m0s 
2017-10-27T03:58:00Z E! Error in plugin [inputs.procstat]: E! Error: procstat getting process, exe: [] pidfile: [] pattern: [java.*ha_analyzer] user: [] Error running /usr/bin/pgrep: exit status 1
2017-10-27T03:59:00Z E! Error in plugin [inputs.procstat]: E! Error: procstat getting process, exe: [] pidfile: [] pattern: [java.*ha_analyzer] user: [] Error running /usr/bin/pgrep: exit status 1
2017-10-27T08:13:00Z E! InfluxDB Output Error: Response Error: Status Code [503], expected [204], [<nil>]
2017-10-27T08:13:00Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2017-10-27T08:14:03Z E! InfluxDB Output Error: Response Error: Status Code [503], expected [204], [<nil>]
2017-10-27T08:14:03Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
SIGQUIT: quit
PC=0x45d003 m=2 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x1d15158, 0x0, 0x7fbaf3390d88, 0x0, 0x7fba00000000, 0x45cc96, 0x3c, 0x0, 0x7fbaf3390dd0, 0x410030, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:426 +0x23
runtime.futexsleep(0x1d15158, 0x0, 0xdf8475800)
	/usr/local/go/src/runtime/os_linux.go:62 +0xd7
runtime.notetsleep_internal(0x1d15158, 0xdf8475800, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:174 +0xd0
runtime.notetsleep(0x1d15158, 0xdf8475800, 0xe2858ad0601)
	/usr/local/go/src/runtime/lock_futex.go:194 +0x56
runtime.sysmon()
	/usr/local/go/src/runtime/proc.go:3805 +0x135
runtime.mstart1()
	/usr/local/go/src/runtime/proc.go:1179 +0x11e
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1149 +0x64

goroutine 1 [semacquire, 261 minutes]:
sync.runtime_Semacquire(0xc4201c841c)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4201c8410)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc420132040, 0xc4201d8c00, 0x0, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:426 +0x54e
main.reloadLoop(0xc4201d8060, 0x1d37f30, 0x0, 0x0, 0x1d37f30, 0x0, 0x0, 0x1d37f30, 0x0, 0x0, ...)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:234 +0xa46
main.main()
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:411 +0x65b

goroutine 17 [syscall, 261 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [syscall, 261 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 51 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher(0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc420062480, 0x762145, 0x1)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:320 +0x444
github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc420062480)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:396 +0x7a
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:400 +0x34f

goroutine 50 [select, 261 minutes]:
main.reloadLoop.func1(0xc4201d8c60, 0xc4201d8c00, 0xc4202820e0, 0xc4201d8060)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:195 +0x24a
created by main.reloadLoop
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:209 +0x6ec

goroutine 31 [select, 261 minutes, locked to thread]:
runtime.gopark(0x14bb280, 0x0, 0x143ad10, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc4201ee750, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc4201ee750)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 52 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc4201567c0, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc4201567c0, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 53 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc420156840, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc420156840, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 54 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc4201568c0, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc4201568c0, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 55 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc420156940, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc420156940, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 56 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc4201569c0, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc4201569c0, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 57 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc420156a80, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc420156a80, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 58 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc420156b00, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc420156b00, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 59 [select]:
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc420132040, 0xc4201d8c00, 0xc4201574c0, 0xdf8475800, 0xc420062420)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:129 +0x3a8
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201c8410, 0xc420132040, 0xc4201d8c00, 0xc420062420, 0xc4201574c0, 0xdf8475800)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505

goroutine 38 [select]:
github.com/influxdata/telegraf/agent.(*Agent).flusher.func1(0xc420014090, 0xc4201d8c00, 0xc4204c6060, 0xc420132040)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:263 +0x2f3
created by github.com/influxdata/telegraf/agent.(*Agent).flusher
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:292 +0xe5

goroutine 39 [select, 260 minutes]:
github.com/influxdata/telegraf/agent.(*Agent).flusher.func2(0xc420014090, 0xc4201d8c00, 0xc420062480, 0xc420132040, 0xc4204c6060)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:298 +0x2ae
created by github.com/influxdata/telegraf/agent.(*Agent).flusher
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:315 +0x155

rax    0xfffffffffffffffc
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x1d15158
rsi    0x0
rbp    0x7fbaf3390d98
rsp    0x7fbaf3390d50
r8     0x0
r9     0x0
r10    0x7fbaf3390d88
r11    0x246
r12    0x0
r13    0x34
r14    0x0
r15    0xf3
rip    0x45d003
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
2017-10-27T08:19:36Z I! Starting Telegraf v1.4.0
2017-10-27T08:19:36Z I! Loaded outputs: influxdb
```

With regards,
Anatoliy Dobrosynets

**Comment by danielnelson** [comment]
Thanks for the bug report, I see the last log message was at `2017-10-27T08:14:03Z`, at what time approximately did you signal the process?

**Comment by anatolijd** [comment]
Somewhen between 08:14  and 08:19  . I killed process, spent some minutes looking for log file and syslog messages, then srarted telegraf service

**Comment by danielnelson** [comment]
And there was never any metrics produced since you started Telegraf?

This looks like a proxy (nginx maybe) returned a 503 Unauthorized error, I say it looks like a proxy because there is no error message and InfluxDB usually reports something more helpful.
```
2017-10-27T08:13:00Z E! InfluxDB Output Error: Response Error: Status Code [503], expected [204], [<nil>]
```

**Comment by anatolijd** [comment]
Yes, never. And yes, there is haproxy balancer in front of.
I see a gap in the metrics for other agents for the downtime period, later they restored writes.
But only those telegraf agents started during downtime - they never restored.

**Comment by danielnelson** [comment]
I tried to reproduce by starting Telegraf with the same plugins and my InfluxDB turned off and then after a few intervals starting InfluxDB, but was unable to reproduce the issue.  I didn't have a haproxy setup.

@anatolijd Are you able to reproduce the issue?

**Comment by danyli78** [comment]
+1 i have the same error message when upgraded to 1.4.3

**Comment by danielnelson** [comment]
@danyli78 The error message in the original case is coming from a proxy and was an accurate error.

**Comment by danielnelson** [comment]
I haven't been able to reproduce, please reopen if you can find a way to do this.
