### ISSUE TITLE
panic/segfault @ goroutine 88

### ISSUE THREAD

**Issue by hestad** [influxdata/telegraf#3909]
### System info:
Telegraf version: 1.4.5-1
OS: Ubuntu 16.04 LTS server

### Steps to reproduce:
We are running 20+ servers 24/7, but only some of them panics like this from time to time (days/weeks can pass). We don't know how to reproduce it.

### Actual behavior:
Panic:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x43dd70]

goroutine 88 [running]:
runtime.throw(0x1477918, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420352a18 sp=0xc4203529f8
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db fp=0xc420352a68 sp=0xc420352a18
runtime.selectgoImpl(0xc420352d80, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:500 +0x1530 fp=0xc420352ce0 sp=0xc420352a68
runtime.selectgo(0xc420352d80)
	/usr/local/go/src/runtime/select.go:238 +0x1c fp=0xc420352d08 sp=0xc420352ce0
github.com/influxdata/telegraf/agent.gatherWithTimeout(0xc42008c7e0, 0xc420043180, 0xc4209d8020, 0x2540be400)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:157 +0x28f fp=0xc420352e48 sp=0xc420352d08
github.com/influxdata/telegraf/agent.(*Agent).gatherer(0xc42000e028, 0xc42008c7e0, 0xc420043180, 0x2540be400, 0xc42008cba0)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:124 +0x2a4 fp=0xc420352f78 sp=0xc420352e48
github.com/influxdata/telegraf/agent.(*Agent).Run.func3(0xc4201b2560, 0xc42000e028, 0xc42008c7e0, 0xc42008cba0, 0xc420043180, 0x2540be400)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:422 +0x7d fp=0xc420352fb0 sp=0xc420352f78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420352fb8 sp=0xc420352fb0
created by github.com/influxdata/telegraf/agent.(*Agent).Run
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:423 +0x505
```

Do you think upgrading Telegraf would help in this case? I didn't see anything about segfault in the latest versions changelog.

**Comment by danielnelson** [comment]
I haven't seen a stack trace like this one.  We haven't made any changes to this code, the only thing that might help would be that we moved from Go 1.8 to 1.9.  Does it always happen on the same servers or does it move around?

**Comment by hestad** [comment]
As far as I recall, we have only seen it on the one server. I have a bit different log from the same server some weeks ago (not sure if it is related error at all).

```fatal error: unexpected signal during runtime execution
runtime: newstack called from g=0xc42030a4e0
	m=0xc42014c800 m->curg=0x0 m->g0=0xc42077eea0 m->gsignal=0xc42077eb60
syscall.Syscall(0x0, 0x9, 0xc4206ea200, 0x200, 0x0, 0x200, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x9, 0xc4206ea200, 0x200, 0x200, 0xc4202e2360, 0x7f2bc8a64ee0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x9, 0xc4206ea200, 0x200, 0x200, 0x42be4f, 0x14bb260, 0xc42081ddc0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
os.(*File).read(0xc42015e028, 0xc4206ea200, 0x200, 0x200, 0x502e9b, 0x11f5a80, 0x200)
	/usr/local/go/src/os/file_unix.go:165 +0x4f
os.(*File).Read(0xc42015e028, 0xc4206ea200, 0x200, 0x200, 0x14461bc, 0xa, 0xc42081de60)
	/usr/local/go/src/os/file.go:101 +0x76
bytes.(*Buffer).ReadFrom(0xc4203e1f80, 0x1c20380, 0xc42015e028, 0x7f2bc89e6028, 0xc4203e1f80, 0x406501)
	/usr/local/go/src/bytes/buffer.go:179 +0x160
io.copyBuffer(0x1c1c440, 0xc4203e1f80, 0x1c20380, 0xc42015e028, 0x0, 0x0, 0x0, 0x7daa85, 0xc4206b2358, 0x7daab9)
	/usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0x1c1c440, 0xc4203e1f80, 0x1c20380, 0xc42015e028, 0xc42015e001, 0xc420d30101, 0xc42081dfb8)
	/usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0xc4206b2600, 0x7620ea)
	/usr/local/go/src/os/exec/exec.go:254 +0x4d
os/exec.(*Cmd).Start.func1(0xc42035c000, 0xc420ad4600)
	/usr/local/go/src/os/exec/exec.go:371 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:372 +0x4e4
fatal error: runtime: wrong goroutine in newstack
2018-03-04T17:26:22Z I! Database creation failed: Post https://lonepine-redacted.influxcloud.net:8086/query?q=CREATE+DATABASE+%22the_dbi%22: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018-03-04T17:26:22Z I! Starting Telegraf v1.4.5
2018-03-04T17:26:22Z I! Loaded outputs: influxdb
2018-03-04T17:26:22Z I! Loaded inputs: inputs.processes inputs.swap inputs.system inputs.cpu inputs.disk inputs.diskio inputs.kernel inputs.mem inputs.exec inputs.exec inputs.exec inputs.exec inputs.procstat inputs.procstat inputs.procstat inputs.statsd
2018-03-04T17:26:22Z I! Tags enabled: area=the_area env=PROD facility=the_facility farm=the_farm host=the_host operator=the_operator server=the_server
2018-03-04T17:26:22Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"the_hostname", Flush Interval:10s 
2018-03-04T17:26:22Z I! Started the statsd service on :8125
2018-03-04T17:26:22Z I! Statsd UDP listener listening on:  [::]:8125
2018-03-04T17:26:45Z E! InfluxDB Output Error: Post https://lonepine-redacted.influxcloud.net:8086/write?consistency=any&db=the_db: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018-03-04T17:26:45Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster

fatal error: schedule: holding locks
.... a lot of "fatal error: runtime·unlock: lock count" which I have removed for readability ......
fatal error: runtime·unlock: lock count 
fatal error: stopm holding locks
releasep: m=0xc4206f5c00 m->p=0xc42002c600 p->m=0 m->mcache=0x7f51dcada058 p->mcache=0x7f51dcada058 p->status=0
fatal error: releasep: invalid p state
releasep: m=0xc4206f2000 m->p=0xc420018000 p->m=0 m->mcache=0x7f51dcace000 p->mcache=0x7f51dcace000 p->status=2
fatal error: releasep: invalid p state
fatal error: schedule: holding locks
fatal error: schedule: holding locks
fatal error: runtime·unlock: lock count 
fatal error: runtime·unlock: lock count 
fatal error: runtime·unlock: lock count 
fatal error: unexpected signal during runtime execution
fatal error: runtime·unlock: lock count 
..... a lot of "fatal error: runtime·unlock: lock count" which I have removed from logs ....
fatal error: runtime·unlock: lock count 
releasep: m=0xc4207f3400 m->p=0xc420024000 p->m=0 m->mcache=0x7f51dcad0ee0 p->mcache=0x7f51dcad0ee0 p->status=2
fatal error: releasep: invalid p state
fatal error: runtime·unlock: lock count   
runtime stack:
runtime.throw(0x145c81c, 0x17)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2176 +0x338
runtime.goschedImpl(0xc4209e9520)
	/usr/local/go/src/runtime/proc.go:2300 +0x106
runtime.gopreempt_m(0xc4209e9520)
	/usr/local/go/src/runtime/proc.go:2315 +0x36
runtime.newstack(0x0)
	/usr/local/go/src/runtime/stack.go:1081 +0x2f0
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:398 +0x86

**Comment by danielnelson** [comment]
Looks like a memory corruption issue, it could be caused by use of unsafe or a Go issue but since I haven't seen any other reports it seems more likely to be an issue with the machine.  Maybe you can try using mcelog?

**Comment by hestad** [comment]
I installed mcelog (I have no previous experience with it) on the mentioned server.
`sudo apt install mcelog`.
Skimming through parts of the doc, I left it with default config.

```
$ sudo service mcelog status
● mcelog.service - LSB: Machine Check Exceptions (MCE) collector & decoder
   Loaded: loaded (/etc/init.d/mcelog; bad; vendor preset: enabled)
   Active: active (running) since Wed 2018-03-21 11:15:53 EET; 1 weeks 0 days ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/mcelog.service
           └─25338 /usr/sbin/mcelog --daemon

Mar 21 11:15:53 <server-name> systemd[1]: Starting LSB: Machine Check Exceptions (MCE) collector & decoder...
Mar 21 11:15:53 <server-name> mcelog[25322]: Starting Machine Check Exceptions decoder: mcelog.
Mar 21 11:15:53 <server-name> systemd[1]: Started LSB: Machine Check Exceptions (MCE) collector & decoder.
```
```
$ cat /var/log/mcelog 
mcelog: mcelog server already running
```

Now we ran into an error on the same server again (no reports of this from other servers).

```
acquirep: p->m=842355777536(13) p->status=1
fatal error: acquirep: invalid p state

runtime stack:
runtime.throw(0x145ebd8, 0x19)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.acquirep1(0xc42001e000)
	/usr/local/go/src/runtime/proc.go:3643 +0x16b
runtime.acquirep(0xc42001e000)
	/usr/local/go/src/runtime/proc.go:3615 +0x2b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1659 +0x123
runtime.findrunnable(0xc420020600, 0x0)
	/usr/local/go/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2222 +0x14c
runtime.park_m(0xc420a1e4e0)
	/usr/local/go/src/runtime/proc.go:2285 +0xab
runtime.mcall(0x7f1632ffcb9f)
	/usr/local/go/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [semacquire, 3188 minutes]:
sync.runtime_Semacquire(0xc4200176ec)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4200176e0)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc42028a000, 0xc420314180, 0x0, 0x0)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:426 +0x54e
main.reloadLoop(0xc4201b6960, 0x1d3cfb0, 0x0, 0x0, 0x1d3cfb0, 0x0, 0x0, 0x1d3cfb0, 0x0, 0x0, ...)
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:234 +0xa46
main.main()
	/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:411 +0x65b

goroutine 17 [syscall, 3188 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 18 [syscall, 3188 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
```

**Comment by danielnelson** [comment]
I guess mcelog didn't notice any processor errors.  Is this a bare-metal machine?

**Comment by hestad** [comment]
I thought mcelog would pick up on memory corruption as well. Yeah all the machines are bare metal. This one is a Lenovo. We will try to run the memory check on it and probably just replace it. We got a new panic this morning as well.

**Comment by hestad** [comment]
We've had no more reports about this issue or Telegraf in general. Mcelog hasn't reported anything on that specific server since we installed it in march either.
