### ISSUE TITLE
logparser not showing all content if \n include.

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/telegraf#4211]
### System info:

ubuntu14.04
telegraf-1.6.3

### Expected behavior:
Want to show all content.

### Actual behavior:

Just show first line:

![telegraf](https://user-images.githubusercontent.com/14313415/40777198-bb79084c-64ff-11e8-819f-0e84ce132f1f.PNG)

### Additional info:

related logs:

2018-05-31 09:39:22,180 [lib.sandbox.taskconsumer] ERROR: Fail to publish jobs in taskconsumer: sql syntax error!
Traceback (most recent call last):
  File "/usr/local/sandboxav/sandbox/lib/sandbox/taskconsumer.py", line 309, in process_message
    self.schedule_jobs(task_info)
  File "/usr/local/sandboxav/sandbox/lib/sandbox/taskconsumer.py", line 266, in schedule_jobs
    client_flag = database.IsCaptureClient(task.utm_serial_number)
  File "/usr/local/sandboxav/sandbox/lib/snwl/database.py", line 934, in IsCaptureClient
    deaid = self.execute_scalar(sql)
  File "/usr/local/sandboxav/sandbox/lib/snwl/database.py", line 227, in execute_scalar
    return self.execute(sql, commit=False).scalar()
  File "/usr/local/sandboxav/sandbox/lib/snwl/database.py", line 161, in execute
    raise Exception("sql syntax error!")
Exception: sql syntax error!

**Comment by danielnelson** [comment]
Duplicate #3228
