### ISSUE TITLE
Unable to use SQL Database in Azure with sqlserver plugin

### ISSUE THREAD

**Issue by erik-wramner** [influxdata/telegraf#4222]
### Relevant telegraf.conf:

[[inputs.sqlserver]]
   servers = [
     "Server=somesqlserver.database.windows.net;Port=1433;Database=db01-example;User ID=telegraf;Password=***;app name=telegraf;log=1"
   ]
   query_version = 2
   azuredb = true

OR:
   servers = [
     "Server=somesqlserver.database.windows.net;Port=1433;User ID=telegraf;Password=***;app name=telegraf;log=1"
   ]

### System info:

Telegraf v1.6.2 (git: release-1.6 1fb4283f), Windows Server 2016
Azure SQL Database with elastic pool and multiple databases:

az sql server create --name sql01 --resource-group rgsql --location westeurope --admin-user sa --admin-password ***
 --assign-identity
az sql elastic-pool create --server sql01 --resource-group rgsql --name sql01ep01 --edition Standard --dtu 100
az sql db create --server sql01 --resource-group rgsql --elastic-pool sql01ep01 --name db01-example

### Steps to reproduce:

I'm unable to configure Telegraf for Azure SQL Database as the grants differ from a classic SQL Server (where my configuration works). First attempt:

1. Create user as described in the docs and grant VIEW SERVER STATE and VIEW ANY DEFINITION.

This fails because there is no VIEW SERVER STATE in SQL Database. Neither is it possible to grant VIEW ANY DEFINITION. Fails with "Securable class 'server' not supported in this version of SQL Server".

Second attempt:

1. Connect to the server without specifying a database using the super user (sa) with telegraf -test.

This works, but (a) it only returns data for master and tempdb and not for db01-example and the other application databases, plus (b) it is not a good idea to use the super user for monitoring. I want to grant as few permissions as possible.

Third attempt:

1. Connect to the server and specify db01-example as database using the super user with telegraf -test.

This crashes with a nil pointer dereference and the log complains about VIEW DATABASE STATE permission denied in database master (apparently the super user can't do that when logged in to a specific database).

Forth attempt:

1. Create user telegraf in db01-example and grant VIEW DATABASE STATE and VIEW DEFINITION (in that database).
2. Connect to the server and specify db01-example using telegraf with telegraf -test.

This crashes with a nil pointer dereference. The log simply says that the connection was forcibly closed.

### Expected behavior:

The documentation should provide instructions on how to set up the telegraf database user for SQL Database as the documented permissions used with SQL Server don't exist. With the right permissions connecting as a user with access rights should return metrics for all databases in the server, not just master and tempdb, just like on a regular SQL Server. Alternatively the instructions should be to create one telegraf database user per database and that should work and return data for the given database.

### Actual behavior:

No configuration I have tried manages to return the expected metrics. Worst case there is a nil pointer dereference and Telegraf crashes, best case metrics for the system databases are returned.

I think this is only a documentation problem, surely someone has tested this as there is support for Azure SQL Database in the plugin. However, try as I might I can't find the right configuration. Ideally I would like to connect with a single user and get statistics for all databases, but if that is not supported I can connect once per database. I need to know how to grant permissions, though.

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
@erik-wramner Can you add the stack traces for the panic cases above?

@m82labs Do you have any advice for how to setup the right permissions and the connection string on Azure?

**Comment by erik-wramner** [comment]
With telegraf user connecting to a specific database:
```
.\telegraf.exe : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ .\telegraf.exe -config .\taz.conf -test 2>err.xt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x106a6a4]

goroutine 30 [running]:
github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).accRow(0xc0420f4040, 0x16457b9, 0x265, 0x1, 0xc0420cc780, 0xc, 0xc, 0x1f39080, 0xc042184160
, 0x1f1d760
, ...
)

	
/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go
:
222
 +
0x864


github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).gatherServer
(
0xc0420f4040
, 
0xc0423d8001
, 
0x9e
, 
0x16457b9
, 
0x265
, 
0x1
, 
0xc0420cc780
, 
0xc
, 
0xc
, 
0x1f39080
, ...
)

	
/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go
:
178
 +
0x237


github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).Gather.func1
(
0xc0422aa0c0
, 
0x1f39080
, 
0xc042184160
, 
0xc0420f4040
, 
0xc0423d8001
, 
0x9e
, 
0x16457b9
, 
0x265
, 
0x1
, 
0x0
, ...
)

	
/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go
:
141
 +
0xb7


created by 
github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).Gather


	
/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go
:
139
 +
0x1da


```

**Comment by erik-wramner** [comment]
Log for above:
```

2018-06-02T06:41:27Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2018-06-02T06:41:27Z I! The user does not have permission to perform this action.
2018-06-02T06:41:27Z E! Error in plugin [inputs.sqlserver]: mssql: The user does not have permission to perform this action.
2018-06-02T06:41:27Z E! Error in plugin [inputs.sqlserver]: read tcp 172.16.0.11:51551->191.233.90.117:11021: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by erik-wramner** [comment]
Super-user connecting to specific database:
```
.\telegraf.exe : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ .\telegraf.exe -config .\taz.conf -test 2>err.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x106a6a4]

goroutine 16 [running]:

github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).accRow(0xc04234e740, 0x16457b9, 0x265, 0x1, 0xc0420ea600, 0xc, 0xc, 0x1f39080, 0xc042040460, 0x1f1d760
, ...
)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go:222 +0x864
github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).gatherServer(0xc04234e740, 0xc0423ec001, 0xbe, 0x16457b9, 0x265, 0x1, 0xc0420ea600, 0xc, 0xc, 0x1f39080, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go:178 +0x237
github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).Gather.func1(0xc0422b9440, 0x1f39080, 0xc042040460, 0xc04234e740, 0xc0423ec001, 0xbe, 0x16457b9, 0x265, 0x1, 0x0, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go:141 +0xb7
created by github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).Gather
	/go/src/github.com/influxdata/telegraf/plugins/inputs/sqlserver/sqlserver.go:139 +0x1da

```

**Comment by erik-wramner** [comment]
As shown in the cli scripts I'm running on standard. Perhaps the plugin requires premium? Apparently the permissions are different. The price difference is quite steep, so if it does require premium it would be nice to make that optional and collect less data instead.

**Comment by erik-wramner** [comment]
Tried with premium and the following permissions to the telegraf user in a target database:
```
GRANT VIEW DEFINITION TO [telegraf];
GRANT VIEW DATABASE STATE TO [telegraf];

```
Connecting to that database succeeds but returns no data. Log file:

`2018-06-05T20:07:12Z I! The server principal "telegraf" is not able to access the database "master" under the current security context.
2018-06-05T20:07:12Z I! Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z E! Error in plugin [inputs.sqlserver]: Login error: mssql: Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z I! The server principal "telegraf" is not able to access the database "master" under the current security context.
2018-06-05T20:07:12Z I! Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z E! Error in plugin [inputs.sqlserver]: Login error: mssql: Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z I! The server principal "telegraf" is not able to access the database "master" under the current security context.
2018-06-05T20:07:12Z I! Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z E! Error in plugin [inputs.sqlserver]: Login error: mssql: Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z I! The server principal "telegraf" is not able to access the database "master" under the current security context.
2018-06-05T20:07:12Z I! Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z E! Error in plugin [inputs.sqlserver]: Login error: mssql: Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z I! The server principal "telegraf" is not able to access the database "master" under the current security context.
2018-06-05T20:07:12Z I! Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z E! Error in plugin [inputs.sqlserver]: Login error: mssql: Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z I! The server principal "telegraf" is not able to access the database "master" under the current security context.
2018-06-05T20:07:12Z I! Cannot open user default database. Using master database instead.
2018-06-05T20:07:12Z E! Error in plugin [inputs.sqlserver]: Login error: mssql: Cannot open user default database. Using master database instead.
`

**Comment by erik-wramner** [comment]
Connecting to the server with database fails with this stack trace:
`.\telegraf : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ .\telegraf -config taz.conf -test
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x106a6a4]
goroutine 14 [running]:
github.com/influxdata/telegraf/plugins/inputs/sqlserver.(*SQLServer).accRow(0xc042354780, 0x16457b9, 0x265, 0x1, 0xc042126480, 0xc, 0xc, 0x1f39080
, `
The server log contains:
`2018-06-05T20:14:02Z E! Error in plugin [inputs.sqlserver]: read tcp 172.16.0.11:62629->191.233.90.117:11195: wsarecv: An existing connection was forcibly closed by the remote host.
2018-06-05T20:14:02Z E! Error in plugin [inputs.sqlserver]: read tcp 172.16.0.11:62628->191.233.90.117:11195: wsarecv: An existing connection was forcibly closed by the remote host.
2018-06-05T20:14:02Z E! Error in plugin [inputs.sqlserver]: read tcp 172.16.0.11:62630->191.233.90.117:11195: wsarecv: An existing connection was forcibly closed by the remote host.
2018-06-05T20:14:02Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2018-06-05T20:14:02Z I! The user does not have permission to perform this action.`

**Comment by erik-wramner** [comment]
Also tried to grant control, no luck. @m82labs, I would really appreciate if you know how to do this.

**Comment by m82labs** [comment]
I will take a look tonight. Are you specifying the Database name in the
connection string?

**Comment by erik-wramner** [comment]
Great. I have tried both with and without the database name in the connection string, see examples in the telegraf config section of this issue.

**Comment by m82labs** [comment]
I'll need some time to look into this, I don't currently have an Azure SQL DB to test with. To the point of documentation, only the V2 queries are going to be compatible, but I will figure out what else needs to be done.

**Comment by erik-wramner** [comment]
I can spin up a database with my personal Azure account for you? I can't grant access to the customer's system, but I can create a similar setup without any data. Please contact me directly (i.e. not through JIRA) if that helps.

**Comment by erik-wramner** [comment]
FYI, I thought it could be the elastic pool, but it makes no difference if I create regular databases.

**Comment by erik-wramner** [comment]
@xin053 would you mind sharing your connection details, i.e. do you connect to a specific database or not and what privileges have you given your user? Plus are you running premium or standard?

@m82labs it would be great to get a build with the proposed changes for testing?

**Comment by m82labs** [comment]
There will soon be some changes to coming that should address these issues
and add some more data. I am working with some folks at Microsoft currently
and will submit a pull request once the changes has been tested.

**Comment by erik-wramner** [comment]
The readme still doesn't describe how to configure the SQL Server account in Azure.  It is not possible to grant VIEW SERVER STATE and VIEW ANY DEFINITION. I can't find it in any of the issues either. Can you add the settings you were using in #4642, please?

**Comment by erik-wramner** [comment]
Hi, I'd just like to mention that I'm still hoping for a solution to this.

**Comment by erik-wramner** [comment]
As cases without activity tend to be closed I'll just note that this is still open.

**Comment by danielnelson** [comment]
@erik-wramner Maybe you are running to the same issue as in https://github.com/influxdata/telegraf/issues/5456, have you tried setting `azuredb = false`?

**Comment by erik-wramner** [comment]
I did, but it was a long time ago. I haven't retested for a while as I'm watching this issue and nothing has happened.

However! The main question above is how to configure the database user account and the connect string to work with Azure. That is still not documented and as you can see above I have tried most of the reasonable alternatives without success.

If someone has this working in Azure, perhaps they can share the way they configured the DB user (the create and grant script) and their connect string cleared from passwords and host names?

**Comment by erik-wramner** [comment]
Update - with 1.9.4 and azuredb=true there is a segfault as in #5456. Without azuredb=false, telegraf seems to hang and the log file complains about:
`VIEW SERVER STATE permission was denied on object server, database master
`
That permission does not exist in Azure. Will try with the latest build from the other case.

**Comment by erik-wramner** [comment]
Update - running telegraf-1.10.0~6aae168c_windows_amd64 with azuredb=true reports the following error and hangs (i.e. doesn't return to terminal until Ctrl+C):
```
.\telegraf : 2019-02-22T08:20:06Z I! Starting Telegraf 
At line:1 char:1
+ .\telegraf -config taz.conf -test
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2019-02-22T08:2...rting Telegraf :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
It works better than before, because it manages to output one line:
```
sqlserver_azurestats,host=thehost,solution=thesolution,sql_instance=theinstance avg_cpu_percent="0.00",otherstatshere
```
The log file contains the usual errors:
```
2019-02-22T08:20:06Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2019-02-22T08:20:06Z I! The user does not have permission to perform this action.
2019-02-22T08:20:06Z E! [inputs.sqlserver]: Error in plugin: mssql: The user does not have permission to perform this action.
2019-02-22T08:20:06Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2019-02-22T08:20:06Z I! The user does not have permission to perform this action.
2019-02-22T08:20:06Z E! [inputs.sqlserver]: Error in plugin: mssql: The user does not have permission to perform this action.
2019-02-22T08:20:06Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2019-02-22T08:20:06Z I! The user does not have permission to perform this action.
2019-02-22T08:20:06Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2019-02-22T08:20:06Z I! The user does not have permission to perform this action.
2019-02-22T08:20:06Z E! [inputs.sqlserver]: Error in plugin: mssql: The user does not have permission to perform this action.
2019-02-22T08:20:06Z I! VIEW SERVER STATE permission was denied on object 'server', database 'master'.
2019-02-22T08:20:06Z I! The user does not have permission to perform this action.
2019-02-22T08:20:06Z E! [inputs.sqlserver]: Error in plugin: mssql: The user does not have permission to perform this action.
```
I'm connecting to a specific database as the DBO for that database with the added permission VIEW DATABASE STATE as suggested in #5456.

I tried with azuredb=false as well and it also fails, just like with 1.9.4 above.

**Comment by erik-wramner** [comment]
Well, finally the latest release 1.10.3 works without crashing when I connect as the super user (the one who created the whole server). It still fails when connecting as a less privileged user. I'll close this issue and report a new one requesting support for running with a non-privileged user instead.
