### ISSUE TITLE
Telegraf with Kafka output dies if the TCP connection is terminated

### ISSUE THREAD

**Issue by sfrode** [influxdata/telegraf#4283]
### Relevant telegraf.conf:

[[outputs.kafka]]
  brokers = [ "serverA.localdomain:9093", "serverB.localdomain:9093" ]
  topic = "telegraf"
  routing_tag = ""
  compression_codec = 1
  required_acks = 1
  max_retry = 3
  ssl_ca   = "/etc/ssl/certs/ca-bundle.crt"
  ssl_cert = ""
  ssl_key  = ""
  insecure_skip_verify = false
  sasl_username = ""
  sasl_password = ""
  data_format = "influx"

### System info:

Telegraf 1.6.0 on RHEL6.9 for this particular system. It happened on 10+ systems connected to the same Kafka cluster in the same time frame.

### Steps to reproduce:

Not attempted.

### Expected behavior:

Reconnect to the Kafka cluster without failure after the TCP connection is re-establoished

### Actual behavior:

Panic, had to be started up again.

### Additional info:

There was a network reconfiguration ongoing at the time where the panic happened. This reconfiguration killed ongoing TCP connections.

```
2018-06-13T14:00:11Z I! Reloading Telegraf config
2018-06-13T14:00:11Z I! Hang on, flushing any cached metrics before shutdown
panic: send on closed channel

goroutine 1148670 [running]:
github.com/Shopify/sarama.(*syncProducer).SendMessage(0xc420874120, 0xc4201161b0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/Shopify/sarama/sync_producer.go:100 +0xf5
github.com/influxdata/telegraf/plugins/outputs/kafka.(*Kafka).Write(0xc4203b8dc0, 0xc4203c4630, 0x3, 0x3, 0xc4203c0101, 0xc420b0be68)
        /go/src/github.com/influxdata/telegraf/plugins/outputs/kafka/kafka.go:266 +0x254
github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc42016c640, 0xc4203c4630, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/internal/models/running_output.go:179 +0x104
github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc42016c640, 0x16248a0, 0xc4202561d0)
        /go/src/github.com/influxdata/telegraf/internal/models/running_output.go:161 +0x476
github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc4202561d0, 0xc42016c640)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:238 +0x59
created by github.com/influxdata/telegraf/agent.(*Agent).flush
        /go/src/github.com/influxdata/telegraf/agent/agent.go:236 +0xa2
```

**Comment by danielnelson** [comment]
Thanks for the bug report, I'm working on some performance enhancements for this plugin so I'll make sure to address this.

**Comment by sfrode** [comment]
Update: it seems like this is happening on some occasions when reload of the configuration too.

```
2018-08-09T12:12:46Z I! Reloading Telegraf config
2018-08-09T12:12:46Z I! Hang on, flushing any cached metrics before shutdown
panic: send on closed channel

goroutine 11834101 [running]:
github.com/Shopify/sarama.(*syncProducer).SendMessage(0xc420b6a8e0, 0xc421146120, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/Shopify/sarama/sync_producer.go:100 +0xf5
github.com/influxdata/telegraf/plugins/outputs/kafka.(*Kafka).Write(0xc4200ca000, 0xc42141e300, 0x4, 0x4, 0xc421410101, 0xc420d4ee68)
        /go/src/github.com/influxdata/telegraf/plugins/outputs/kafka/kafka.go:266 +0x254
github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc42009a780, 0xc42141e300, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/internal/models/running_output.go:179 +0x104
github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc42009a780, 0x16248a0, 0xc4201cdf70)
        /go/src/github.com/influxdata/telegraf/internal/models/running_output.go:161 +0x476
github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc4201cdf70, 0xc42009a780)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:238 +0x59
created by github.com/influxdata/telegraf/agent.(*Agent).flush
        /go/src/github.com/influxdata/telegraf/agent/agent.go:236 +0xa2
```
