### ISSUE TITLE
Telegraf panic with ipmi_sensor input

### ISSUE THREAD

**Issue by vazhem** [influxdata/telegraf#4922]
### Relevant telegraf.conf:

[[inputs.ipmi_sensor]]
  path = "/usr/bin/ipmitool"

### System info:
Telegraf 1.8.1
SLES 12 SP2
ipmitool-1.8.17-8.6.x86_64

Telegraf runs in privileged docker container.

### Steps to reproduce:
On some of the hw cluster ipmitool returns output with errors 'Unable to send command: Invalid argument'. See additional info for details.

### Expected behavior:
Parse available data from sensors.

### Actual behavior:
Panic which causes telegraf to crash.

```
panic: runtime error: index out of range

goroutine 32 [running]:
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.extractFieldsFromRegex(0xc42044c0a0, 0xc420343cc0, 0x3e, 0x1000)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:233 +0x225
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.parseV1(0x21499e0, 0xc4201dc3c0, 0x0, 0x0, 0xc420f7a000, 0x28a6, 0x3e00, 0xbeeb15e5b3958198, 0xbb5bf71b, 0x31bc820, ...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:131 +0x151
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).parse(0xc4204c0f50, 0x21499e0, 0xc4201dc3c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:123 +0x2c1
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather(0xc4204c0f50, 0x21499e0, 0xc4201dc3c0, 0x45d964b800, 0xc42009a180)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:93 +0x179
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc4200b23c0, 0xc4205393c0, 0x21499e0, 0xc4201dc3c0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:153 +0x47
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
        /go/src/github.com/influxdata/telegraf/agent/agent.go:152 +0xd4
```

### Additional info:

```
#ipmitool sdr

Temp             | 38 degrees C      | ok
Temp             | disabled          | ns
Inlet Temp       | 25 degrees C      | ok
DIMM PG          | 0x00              | ok
NDC PG           | 0x00              | ok
PS1 PG FAIL      | 0x00              | ok
PS2 PG FAIL      | 0x00              | ok
BP0 PG           | 0x00              | ok
BP1 PG           | 0x00              | ok
BP2 PG           | 0x00              | ok
1.8V SW PG       | 0x00              | ok
2.5V SW PG       | 0x00              | ok
5V SW PG         | 0x00              | ok
PVNN SW PG       | 0x00              | ok
VSB11 SW PG      | 0x00              | ok
VSBM SW PG       | 0x00              | ok
3.3V B PG        | 0x00              | ok
MEM012 VDDQ PG   | 0x00              | ok
MEM012 VPP PG    | 0x00              | ok
MEM012 VTT PG    | 0x00              | ok
MEM345 VDDQ PG   | 0x00              | ok
MEM345 VPP PG    | 0x00              | ok
MEM345 VTT PG    | 0x00              | ok
VCCIO PG         | 0x00              | ok
VCORE PG         | 0x00              | ok
FIVR PG          | 0x00              | ok
MEM012 VDDQ PG   | Not Readable      | ns
MEM012 VPP PG    | Not Readable      | ns
MEM012 VTT PG    | Not Readable      | ns
MEM345 VDDQ PG   | Not Readable      | ns
MEM345 VPP PG    | Not Readable      | ns
MEM345 VTT PG    | Not Readable      | ns
VCCIO PG         | Not Readable      | ns
VCORE PG         | Not Readable      | ns
FIVR PG          | Not Readable      | ns
Fan1             | disabled          | ns
Fan2             | disabled          | ns
Fan3             | 7440 RPM          | ok
Fan4             | 7320 RPM          | ok
Fan5             | 7560 RPM          | ok
Fan6             | 7440 RPM          | ok
Presence         | 0x00              | ok
Presence         | 0x00              | ok
Presence         | 0x00              | ok
Presence         | 0x00              | ok
Intrusion Cable  | 0x00              | ok
VGA Cable Pres   | 0x00              | ok
Presence         | 0x00              | ok
BP0 Presence     | 0x00              | ok
BP1 Presence     | 0x00              | ok
BP2 Presence     | 0x00              | ok
Power Cable      | Not Readable      | ns
Signal Cable     | Not Readable      | ns
Power Cable      | 0x00              | ok
Signal Cable     | 0x00              | ok
Power Cable      | Not Readable      | ns
Signal Cable     | Not Readable      | ns
Presence         | 0x00              | ok
Presence         | 0x00              | ok
Current 1        | 0.40 Amps         | ok
Current 2        | 0.40 Amps         | ok
Voltage 1        | 212 Volts         | ok
Voltage 2        | 210 Volts         | ok
Riser Config Err | 0x00              | ok
OS Watchdog      | 0x00              | ok
SEL              | Not Readable      | ns
Intrusion        | 0x00              | ok
Power Optimized  | 0x00              | ok
Pwr Consumption  | 154 Watts         | ok
PS Redundancy    | Not Readable      | ns
Fan Redundancy   | 0x00              | ok
Redundancy       | Not Readable      | ns
SD1              | Not Readable      | ns
SD2              | Not Readable      | ns
SD               | Not Readable      | ns
IO Usage         | 0 percent         | ok
MEM Usage        | 39 percent        | ok
SYS Usage        | 53 percent        | ok
CPU Usage        | 63 percent        | ok
Status           | 0x00              | ok
Status           | 0x00              | ok
Status           | 0x00              | ok
Status           | 0x00              | ok
CMOS Battery     | 0x00              | ok
ROMB Battery     | Not Readable      | ns
PCIe Slot1       | 0x00              | ok
PCIe Slot2       | Not Readable      | ns
PCIe Slot3       | Not Readable      | ns
PCIe Slot4       | Not Readable      | ns
PCIe Slot5       | Not Readable      | ns
PCIe Slot6       | Not Readable      | ns
PCIe Slot7       | Not Readable      | ns
PCIe Slot8       | Not Readable      | ns
Drive 0          | 0x00              | ok
Drive 15         | Not Readable      | ns
Drive 30         | Not Readable      | ns
Cable PCIe A0    | Not Readable      | ns
Cable PCIe B0    | Not Readable      | ns
Cable PCIe A1    | Not Readable      | ns
Cable PCIe B1    | Not Readable      | ns
Cable PCIe A2    | Not Readable      | ns
Cable PCIe B2    | Not Readable      | ns
Cable SAS A0     | 0x00              | ok
Cable SAS B0     | 0x00              | ok
Cable SAS A1     | 0x00              | ok
Cable SAS B1     | Not Readable      | ns
Cable SAS A2     | 0x00              | ok
Cable SAS B2     | Not Readable      | ns
Cable PCIe A0    | Not Readable      | ns
Cable PCIe B0    | Not Readable      | ns
A                | 0x00              | ok
B                | 0x00              | ok
Unable to send command: Invalid argument
ECC Corr Err     | Not Readable      | ns
Unable to send command: Invalid argument
ECC Uncorr Err   | Not Readable      | ns
Unable to send command: Invalid argument
PCI Parity Err   | Not Readable      | ns
Unable to send command: Invalid argument
PCI System Err   | Not Readable      | ns
Unable to send command: Invalid argument
SBE Log Disabled | Not Readable      | ns
Unable to send command: Invalid argument
Unknown          | Not Readable      | ns
Unable to send command: Invalid argument
CPU Protocol Err | Not Readable      | ns
Unable to send command: Invalid argument
CPU Machine Chk  | Not Readable      | ns
Unable to send command: Invalid argument
Memory Spared    | Not Readable      | ns
Unable to send command: Invalid argument
Memory Mirrored  | Not Readable      | ns
Unable to send command: Invalid argument
PCIE Fatal Err   | Not Readable      | ns
Unable to send command: Invalid argument
Chipset Err      | Not Readable      | ns
Unable to send command: Invalid argument
Err Reg Pointer  | Not Readable      | ns
Unable to send command: Invalid argument
Mem ECC Warning  | Not Readable      | ns
Unable to send command: Invalid argument
USB Over-current | Not Readable      | ns
Unable to send command: Invalid argument
POST Err         | Not Readable      | ns
Unable to send command: Invalid argument
Hdwr version err | Not Readable      | ns
Unable to send command: Invalid argument
Non Fatal PCI Er | Not Readable      | ns
Unable to send command: Invalid argument
Fatal IO Error   | Not Readable      | ns
Unable to send command: Invalid argument
MSR Info Log     | Not Readable      | ns
Unable to send command: Invalid argument
TXT Status       | Not Readable      | ns
Unable to send command: Invalid argument
iDPT Mem Fail    | Not Readable      | ns
Unable to send command: Invalid argument
Additional Info  | Not Readable      | ns
Unable to send command: Invalid argument
CPU TDP          | Not Readable      | ns
Unable to send command: Invalid argument
QPIRC Warning    | Not Readable      | ns
Unable to send command: Invalid argument
QPIRC Warning    | Not Readable      | ns
Unable to send command: Invalid argument
Link Warning     | Not Readable      | ns
Unable to send command: Invalid argument
Link Warning     | Not Readable      | ns
Unable to send command: Invalid argument
Link Error       | Not Readable      | ns
Unable to send command: Invalid argument
MRC Warning      | Not Readable      | ns
Unable to send command: Invalid argument
MRC Warning      | Not Readable      | ns
Unable to send command: Invalid argument
Chassis Mismatch | Not Readable      | ns
Unable to send command: Invalid argument
FatalPCIErrOnBus | Not Readable      | ns
Unable to send command: Invalid argument
NonFatalPCIErBus | Not Readable      | ns
Unable to send command: Invalid argument
Fatal PCI SSD Er | Not Readable      | ns
Unable to send command: Invalid argument
NonFatalSSDEr    | Not Readable      | ns
Unable to send command: Invalid argument
CPUMachineCheck  | Not Readable      | ns
Unable to send command: Invalid argument
FatalPCIErARI    | Not Readable      | ns
Unable to send command: Invalid argument
NonFatalPCIErARI | Not Readable      | ns
Unable to send command: Invalid argument
FatalPCIExpEr    | Not Readable      | ns
Unable to send command: Invalid argument
NonFatalPCIExpEr | Not Readable      | ns
CP Left Pres     | 0x00              | ok
CP Right Pres    | 0x00              | ok
Unable to send command: Invalid argument
CPU Link Info    | Not Readable      | ns
Unable to send command: Invalid argument
Chipset Info     | Not Readable      | ns
Unable to send command: Invalid argument
Memory Config    | Not Readable      | ns
Unable to send command: Invalid argument
QPI Link Err     | Not Readable      | ns
Unable to send command: Invalid argument
LT/Flex Addr     | Not Readable      | ns
Unable to send command: Invalid argument
OS Watchdog Time | Not Readable      | ns
Unable to send command: Invalid argument
TPM Presence     | Not Readable      | ns
VSA PG           | 0x00              | ok
VSA PG           | Not Readable      | ns
TPM Presence     | 0x00              | ok
Dedicated NIC    | 0x00              | ok
Status           | 0x00              | ok
Pfault Fail Safe | Not Readable      | ns
Unresp sensor    | 0x00              | ok
Presence         | 0x00              | ok
GPU1 Temp        | disabled          | ns
GPU2 Temp        | disabled          | ns
Riser 3 Presence | 0x00              | ok
Riser 2 Presence | 0x00              | ok
Riser 1 Presence | 0x00              | ok
GPU3 Temp        | disabled          | ns
GPU4 Temp        | disabled          | ns
GPU5 Temp        | disabled          | ns
GPU6 Temp        | disabled          | ns
GPU7 Temp        | disabled          | ns
GPU8 Temp        | disabled          | ns
Front LED Panel  | 0x00              | ok
NVDIMM Battery   | Not Readable      | ns
Unable to send command: Invalid argument
NVDIMM Warning   | Not Readable      | ns
Unable to send command: Invalid argument
NVDIMM Error     | Not Readable      | ns
Unable to send command: Invalid argument
NVDIMM Info      | Not Readable      | ns
Unable to send command: Invalid argument
POST Pkg Repair  | Not Readable      | ns
Fan1 Status      | Not Readable      | ns
Fan2 Status      | Not Readable      | ns
Fan3 Status      | 0x00              | ok
Fan4 Status      | 0x00              | ok
Fan5 Status      | 0x00              | ok
Fan6 Status      | 0x00              | ok
Exhaust Temp     | 31 degrees C      | ok
ROMB Battery     | Not Readable      | ns
Cable SAS A0     | Not Readable      | ns
Cable SAS A0     | Not Readable      | ns
```

**Comment by AquaRelliux** [comment]
This still happens for me when I run the unraid container. Should have been fixed long time ago?

**Comment by danielnelson** [comment]
@AquaRelliux Could you paste the panic stack trace on a new issue?

**Comment by AquaRelliux** [comment]
Thanks for the quick reply. It only happend when I tried to run over LAN ip:

goroutine 203 [running]:
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.NewConnection(0xc0001da091, 0x1c, 0x0, 0x0, 0x0)
/go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/connection.go:34 +0x3ae
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).parse(0xc0005a0870, 0x26a1800, 0xc00036d9c0, 0xc0001da091, 0x1c, 0xc0000b7bc0, 0xc0002306c0)
/go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:107 +0x5af
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather.func1(0xc000966000, 0xc0005a0870, 0x26a1800, 0xc00036d9c0, 0xc0001da091, 0x1c)
/go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:86 +0x7d
created by github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather
/go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:84 +0x116

**Comment by danielnelson** [comment]
Thanks, yeah this is another different bug, can you create a [new issue][] with that?

[new issue]: https://github.com/influxdata/telegraf/issues/new/choose

**Comment by deef0000dragon1** [comment]
I have also encountered what I think is this same stacktrace. 

``` goroutine 94 [running]:
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.NewConnection(0xc0001f21b1, 0x29, 0x0, 0x0, 0xc000111950)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/connection.go:34 +0x3bd
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).parse(0xc000110730, 0x2ebdee0, 0xc00017e460, 0xc0001f21b1, 0x29, 0xc00017ea00, 0xc00017ea40)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:113 +0x72f
github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather.func1(0xc0004a0af0, 0xc000110730, 0x2ebdee0, 0xc00017e460, 0xc0001f21b1, 0x29)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:92 +0x9d
created by github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor.(*Ipmi).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ipmi_sensor/ipmi.go:90 +0x116
```
