### ISSUE TITLE
Panic in http_listener gzip payloads

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4983]
### System info:

Unknown

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

No panic

### Actual behavior:

```
2018-11-12T20:54:54Z D! unexpected EOF
2018-11-12T20:54:54Z I! http: panic serving 127.0.0.1:1234: runtime error: invalid memory address or nil pointer dereference
goroutine 12013166 [running]:
net/http.(*conn).serve.func1(0xc42e4f4500)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x1ad5020, 0x31843b0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
compress/gzip.(*Reader).Close(0x0, 0x2125200, 0xc420044080)
	/usr/local/go/src/compress/gzip/gunzip.go:292 +0x22
github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).serveWrite(0xc420410000, 0x213c1e0, 0xc426c28ee0, 0xc4226c5700)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:261 +0xe5e
github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).(github.com/influxdata/telegraf/plugins/inputs/http_listener.serveWrite)-fm(0x213c1e0, 0xc426c28ee0, 0xc4226c5700)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:216 +0x48
github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).AuthenticateIfSet(0xc420410000, 0xc42006dd38, 0x213c1e0, 0xc426c28ee0, 0xc4226c5700)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:401 +0x7f
github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).ServeHTTP(0xc420410000, 0x213c1e0, 0xc426c28ee0, 0xc4226c5700)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:216 +0x234
net/http.serverHandler.ServeHTTP(0xc420dda410, 0x213c1e0, 0xc426c28ee0, 0xc4226c5700)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42e4f4500, 0x213f260, 0xc422700a00)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by ono760** [comment]
@danielnelson Running Telegraf 1.8.1-1
