### ISSUE TITLE
Syntax error when passing Telegram Bot token

### ISSUE THREAD

**Issue by maxthehacker** [influxdata/telegraf#5677]
I'm new too telegraf and was trying out the example in the website. After i got my token from BotFather, I put it in my code and in the console log it came up as a syntax error.

Code: const Telegraf = require('telegraf')
const token = xxxxxxx:Aabdpinwodwnidnwdwdsc //just an example token as i don't want to give away my actual one

const bot = new Telegraf(process.env.token)
bot.start((ctx) => ctx.reply('Welcome'))
bot.help((ctx) => ctx.reply('Send me a sticker'))
bot.on('sticker', (ctx) => ctx.reply('👍'))
bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.launch()

console log : C:\Users\srava\AppData\Roaming\Sublime Text 3\Packages\User\TeleBot.js:2
const token = xxxxxxxxxxx:AAGDe6DHSOIO5Ghj6kh
                                      ^ <- This is pointing at the colon.

SyntaxError: Unexpected token :
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
[Finished in 0.2s]

**Comment by danielnelson** [comment]
I think you are looking for the https://github.com/telegraf/telegraf project.
