### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by TheFlyingCorpse** [influxdata/telegraf#571]
Agent based on git commit from master branch: 7531e218c179d00554c0ed332f1f100bc68290e8 (0.10)

This error shows up after the telegraf has been running for 2-3 days and promptly kills it:
```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xc046710bd9 pc=0x412c63]

goroutine 120496 [running]:
runtime.throw(0x1145860, 0x2a)
        c:/go/src/runtime/panic.go:527 +0x97 fp=0xc08241faf0 sp=0xc08241fad8runtime.sigpanic()
        c:/go/src/runtime/signal_windows.go:155 +0x68 fp=0xc08241fb18 sp=0xc08241faf0runtime.mallocgc(0x10, 0xcab5c0, 0x0, 0xe17940)
        c:/go/src/runtime/malloc.go:617 +0x8c3 fp=0xc08241fbe8 sp=0xc08241fb18runtime.newobject(0xcab5c0, 0x3866a68)
        c:/go/src/runtime/malloc.go:760 +0x49 fp=0xc08241fc10 sp=0xc08241fbe8runtime.convT2E(0xcab5c0, 0xc08241fdb0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/iface.go:138 +0xd0 fp=0xc08241fc38 sp=0xc08241fc10net/http.(*Request).write(0xc08234c1c0, 0x3866a40, 0xc08220e580, 0x0, 0xc08227c4b0, 0x0, 0x0)
        c:/go/src/net/http/request.go:408 +0x4d5 fp=0xc08241fe30 sp=0xc08241fc38net/http.(*persistConn).writeLoop(0xc08234e160)
        c:/go/src/net/http/transport.go:1015 +0x283 fp=0xc08241ff98 sp=0xc08241fe30runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc08241ffa0 sp=0xc08241ff98created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xca4

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0823034bc)
        c:/go/src/runtime/sema.go:43 +0x2d
sync.(*WaitGroup).Wait(0xc0823034b0)
        c:/go/src/sync/waitgroup.go:126 +0xbb
github.com/influxdb/telegraf.(*Agent).gatherParallel(0xc08202e228, 0xc082013b60, 0x0, 0x0)
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:121 +0x139
github.com/influxdb/telegraf.(*Agent).Run(0xc08202e228, 0xc082013980, 0x0, 0x0)
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:386 +0x8a3
main.main()
        C:/temp/work/src/github.com/influxdb/telegraf/cmd/telegraf/telegraf.go:213 +0x1b4c

goroutine 5 [syscall, 1669 minutes]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        c:/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 13 [chan receive, 1669 minutes]:
main.main.func1(0xc0820139e0, 0xc082013980)
        C:/temp/work/src/github.com/influxdb/telegraf/cmd/telegraf/telegraf.go:193 +0x3d
created by main.main
        C:/temp/work/src/github.com/influxdb/telegraf/cmd/telegraf/telegraf.go:195 +0x1431

goroutine 17 [select]:
github.com/influxdb/telegraf.(*Agent).flusher(0xc08202e228, 0xc082013980, 0xc082013b60, 0x0, 0x0)
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:291 +0x456
github.com/influxdb/telegraf.(*Agent).Run.func1(0xc0821d21a0, 0xc08202e228, 0xc082013980, 0xc082013b60)
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:351 +0x86
created by github.com/influxdb/telegraf.(*Agent).Run
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:355 +0x470

goroutine 120493 [select]:
net/http.(*persistConn).roundTrip(0xc08234e160, 0xc08241aa50, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1164 +0xb14
net/http.(*Transport).RoundTrip(0xc08200eb40, 0xc08234c1c0, 0xa8, 0x0, 0x0)
        c:/go/src/net/http/transport.go:235 +0x537
net/http.send(0xc08234c1c0, 0x3864478, 0xc08200eb40, 0xc08239c050, 0x0, 0x0)
        c:/go/src/net/http/client.go:220 +0x533
net/http.(*Client).send(0xc0821512f0, 0xc08234c1c0, 0x43, 0x0, 0x0)
        c:/go/src/net/http/client.go:143 +0x161
net/http.(*Client).doFollowingRedirects(0xc0821512f0, 0xc08234c1c0, 0x11df368, 0x0, 0x0, 0x0)
        c:/go/src/net/http/client.go:380 +0xbc7
net/http.(*Client).Do(0xc0821512f0, 0xc08234c1c0, 0x28, 0x0, 0x0)
        c:/go/src/net/http/client.go:178 +0x18f
github.com/influxdb/influxdb/client/v2.(*client).Write(0xc0820fb640, 0x3fa0000, 0xc08259e000, 0x0, 0x0)
        C:/temp/work/src/github.com/influxdb/influxdb/client/v2/client.go:382 +0x8ec
github.com/influxdb/telegraf/plugins/outputs/influxdb.(*InfluxDB).Write(0xc082137900, 0xc08231f080, 0x9, 0x10, 0x0, 0x0)
        C:/temp/work/src/github.com/influxdb/telegraf/plugins/outputs/influxdb/influxdb.go:148 +0x3b1
github.com/influxdb/telegraf.(*Agent).writeOutput(0xc08202e228, 0xc08231f080, 0x9, 0x10, 0xc082150ed0, 0xc082013980, 0xc08241a860)
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:234 +0x16e
created by github.com/influxdb/telegraf.(*Agent).flush
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:274 +0x121

goroutine 120536 [syscall, locked to thread]:
syscall.Syscall9(0x7ffe89532410, 0x9, 0x401dff8, 0x1, 0x1562660, 0x414, 0x2, 0xc082377060, 0xc0821bec60, 0xc0823775f0, ...)
        c:/go/src/runtime/syscall_windows.go:150 +0x5c
github.com/go-ole/go-ole.invoke(0x401dff8, 0x200000001, 0x0, 0x0, 0x0, 0xc0821bec60, 0x0, 0x0)
        C:/temp/work/src/github.com/go-ole/go-ole/idispatch_windows.go:179 +0x4df
github.com/go-ole/go-ole.(*IDispatch).Invoke(0x401dff8, 0x200000001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/temp/work/src/github.com/go-ole/go-ole/idispatch.go:27 +0x6a
github.com/go-ole/go-ole.(*IDispatch).InvokeWithOptionalArgs(0x0, 0x401e068, 0x0, 0x0, 0xcaafc0, 0xc082111f60, 0xcaafc0, 0xc082111f60, 0xc604e0, 0xc082546380)
        C:/temp/work/src/github.com/go-ole/go-ole/idispatch.go:69 +0xc2
github.com/go-ole/go-ole/oleutil.GetProperty(0xc0823aef60, 0x4e4fd4, 0xc84f60, 0xc0821beba0, 0xc0823aef60, 0x100acb0, 0xc082377738, 0x1, 0x1)
        C:/temp/work/src/github.com/go-ole/go-ole/oleutil/oleutil.go:65 +0x7c
created by github.com/influxdb/telegraf.(*Agent).gatherParallel
        C:/temp/work/src/github.com/influxdb/telegraf/agent.go:114 +0x406

goroutine 120495 [IO wait]:
net.runtime_pollWait(0x3866908, 0x72, 0xc0821d27d0)
        c:/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc0825a5370, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc08202e238, 0xc0825a5260, 0xfde8f8, 0x7, 0x11df120, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc0825a5200, 0xc082586000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082558030, 0xc082586000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:172 +0xeb
net/http.noteEOFReader.Read(0x38669c8, 0xc082558030, 0xc08234e1b8, 0xc082586000, 0x1000, 0x1000, 0xc0821ea6c0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc0821bf000, 0xc082586000, 0x1000, 0x1000, 0xc082061141, 0x0, 0x0)
        <autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc08259e3c0)
        c:/go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Peek(0xc08259e3c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc08234e160)
        c:/go/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xc7f
```

config: 
```
# Telegraf configuration

# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs.

# Even if a plugin has no configuration, it must be declared in here
# to be active. Declaring a plugin means just specifying the name
# as a section with no variables. To deactivate a plugin, comment
# out the name and any variables.

# Use 'telegraf -config telegraf.toml -test' to see what metrics a config
# file would generate.

# One rule that plugins conform to is wherever a connection string
# can be passed, the values '' and 'localhost' are treated specially.
# They indicate to the plugin to use their own builtin configuration to
# connect to the local system.

# NOTE: The configuration has a few required parameters. They are marked
# with 'required'. Be sure to edit those to make this configuration work.

# Tags can also be specified via a normal map, but only one form at a time:
[tags]
  # dc = "us-east-1"

# Configuration for telegraf agent
[agent]
  # Default data collection interval for all inputs
  interval = "10s"
  # Rounds collection interval to 'interval'
  # ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  # Default data flushing interval for all outputs. You should not set this below
  # interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  # Jitter the flush interval by a random amount. This is primarily to avoid
  # large write spikes for users running a large number of telegraf instances.
  # ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  # Run telegraf in debug mode
  debug = false
  # Override default hostname, if empty use os.Hostname()
  hostname = ""


###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  # The full HTTP or UDP endpoint URL for your InfluxDB instance.
  # Multiple urls can be specified but it is assumed that they are part of the same
  # cluster, this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["http://influxdb:8086"] # required
  # The target database for metrics (telegraf will create it if not exists)
  database = "telegraf" # required
  # Precision of writes, valid values are n, u, ms, s, m, and h
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"

  # Connection timeout (for the connection with InfluxDB), formatted as a string.
  # If not provided, will default to 0 (no timeout)
  # timeout = "5s"
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"
  # Set the user agent for HTTP POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"
  # Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512



###############################################################################
#                                  INPUTS                                     #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  # Whether to report per-cpu stats or not
  percpu = true
  # Whether to report total system cpu stats or not
  totalcpu = true
  # Comment this line if you want the raw CPU time metrics
  #drop = ["time_*"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  # By default, telegraf gather stats for all mountpoints.
  # Setting mountpoints will restrict the stats to the specified mountpoints.
  # Mountpoints=["/"]

# Read metrics about disk IO by device
[[inputs.diskio]]
  # By default, telegraf will gather stats for all devices including
  # disk partitions.
  # Setting devices will restrict the stats to the specified devcies.
  # devices = ["sda","sdb"]
  # Uncomment the following line if you do not need disk serial numbers.
  # skip_serial_number = true

# Read metrics about memory usage
[[inputs.mem]]
  # no configuration

# Read metrics about network interface usage
[[inputs.net]]
  # By default, telegraf gathers stats from any up interface (excluding loopback)
  # Setting interfaces will tell it to gather these explicit interfaces,
  # regardless of status.
  #
  # interfaces = ["eth0", ... ]

# Read metrics about TCP status such as established, time wait etc and UDP sockets counts.
[[inputs.netstat]]
  # no configuration

# Ping given url(s) and return statistics
[[inputs.ping]]
  # urls to ping
  urls = ["www.google.com"] # required
  # number of pings to send (ping -c <COUNT>)
  count = 1 # required
  # interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
  ping_interval = 0.0
  # ping timeout, in s. 0 == no timeout (ping -t <TIMEOUT>)
  timeout = 0.0
  # interface to send ping from (ping -I <INTERFACE>)
  interface = ""

# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration


###############################################################################
#                              SERVICE INPUTS                                 #
###############################################################################
```

**Comment by sparrc** [comment]
@TheFlyingCorpse What is your OS?

**Comment by TheFlyingCorpse** [comment]
My OS is Windows 10, build 1511. Using Go 1.5.1 atm.

**Comment by sparrc** [comment]
I'm closing as a Golang issue, I would try building with Go 1.5.3 first (might even be worth trying a 1.6 beta build)

see [this comment](https://github.com/golang/go/issues/11783#issuecomment-122590180) for more details on getting more complete traceback info

**Comment by danesparza** [comment]
FYI -- I had this issue on Windows with a version compiled with 1.5.3.  I'm trying again now with a version compiled with Go 1.6 (now that the official version has been released).
