### ISSUE TITLE
Segmentation violation on connection failed

### ISSUE THREAD

**Issue by essobedo** [influxdata/telegraf#7592]
### Relevant telegraf.conf:

```toml
[[inputs.http_response]]
urls = ["https:/nonexistent.nonexistent"]
http_header_tags = {"Date" = "date", "Content-Type" = "content_type"}
```

### System info:

With the nightly build of Telegraf on Mac OS Mojave

### Steps to reproduce:

1. Configure the input plugin `http_response` with `http_header_tags` and an unreachable url
2. Start telegraf

### Expected behavior:

Telegraf doesn't crash

### Actual behavior:

Telegraf crashes with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1107012]

goroutine 14 [running]:
github.com/influxdata/telegraf/plugins/inputs/http_response.(*HTTPResponse).httpGather(0xc0000eeb00, 0xc0002384c1, 0x2c, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/http_response/http_response.go:276 +0x602
github.com/influxdata/telegraf/plugins/inputs/http_response.(*HTTPResponse).Gather(0xc0000eeb00, 0x2e78fe0, 0xc0000c2c80, 0x34, 0x0)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/http_response/http_response.go:396 +0x23d
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc00004e550, 0x2e78fe0, 0xc0000c2c80, 0x5153000, 0x3ffff000)
	/go/src/github.com/influxdata/telegraf/models/running_input.go:115 +0x6d
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1(0xc0001ccd20, 0xc00004e550, 0x2e78fe0, 0xc0000c2c80)
	/go/src/github.com/influxdata/telegraf/agent/agent.go:322 +0x3f
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
	/go/src/github.com/influxdata/telegraf/agent/agent.go:321 +0x91
```

### Additional info:

The bug is caused by the fix for https://github.com/influxdata/telegraf/issues/7403

**Comment by essobedo** [comment]
Corresponding PR #7593
