### ISSUE TITLE
sflow: invalid memory address or nil pointer dereference on Ubiquiti Security Gateway

### ISSUE THREAD

**Issue by midzelis** [influxdata/telegraf#7937]
Getting this stack trace when connecting Ubility Security Gateway flow accounting to this sflow input plugin. 

```
telegraf      | panic: runtime error: invalid memory address or nil pointer dereference
telegraf      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19517d0]
telegraf      |
telegraf      | goroutine 21 [running]:
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.RawPacketHeaderFlowData.GetTags(...)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:121
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.makeMetrics(0xc0007233e0, 0x194ab2f, 0xc000245520, 0x2ed53e0, 0xc000741a40, 0xc0001abb80)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/metricencoder.go:29 +0x6fc
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func1(0xc0007233e0)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:66 +0x4d
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.(*PacketDecoder).Decode(0xc000245520, 0x2ed53e0, 0xc000741a40, 0x0, 0x0)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/packetdecoder.go:40 +0x42
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).process(0xc000522000, 0x2f495c0, 0xc0002455a0, 0xc00065e000, 0x4c4, 0x10000)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:135 +0x83
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).read(0xc000522000, 0x2f495c0, 0xc0002455a0, 0x2f426c0, 0xc000010528)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:129 +0x8c
telegraf      | github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func2(0xc000522000, 0x2f495c0, 0xc0002455a0, 0xc000010528)
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:97 +0x82
telegraf      | created by github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start
telegraf      | 	/go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:95 +0x305
```
Please feel free to contact me for more info.

**Comment by dimdin** [comment]
On Ubiquiti edgerouter, I am getting the same panic, using `Telegraf 1.17.2 (git: HEAD 74011e22)`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x1583410]
goroutine 36 [running]:
github.com/influxdata/telegraf/plugins/inputs/sflow.RawPacketHeaderFlowData.GetTags(...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:121
github.com/influxdata/telegraf/plugins/inputs/sflow.makeMetrics(0x58413e0, 0x157da40, 0x5999290, 0x2773fb8, 0x5b0e040, 0x59f3a00)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/metricencodhub.com/influxdata/telegraf/plugins/inputs/sflow/metricencod er.go:29 +0x4d8
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func1(0x58413e0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:66 +0x34
github.com/influxdata/telegraf/plugins/inputs/sflow.(*PacketDecoder).Decode(0x5999290, 0x2773fb8, 0x5b0e040, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/packetdecoder.go:40 +0x38
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).process(0x5de0180, 0x27a48b0, 0x5d6b900, 0x58d0000, 0x528, 0x10000)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:135 +0x64
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).read(0x5de0180, 0x27a48b0, 0x5d6b900, 0x27a22b8, 0x5983170)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:129 +0x64
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func2(0x5de0180, 0x27a48b0, 0x5d6b900, 0x5983170)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:97 +0x6c
created by github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:95 +0x2c4
```
The router sends sflow v5.
Part of tcpdump captured packet:
```
IP (tos 0x0, ttl 64, id 53520, offset 0, flags [DF], proto UDP (17), length 1264)
    1.1.1.1.33590 > 2.2.2.2.6343: [udp sum ok] sFlowv5, IPv4 agent 1.1.1.1, agent-id 0, seqnum 3162, uptime 2040000, samples 7, length 1236
        flow sample (1), length 160, seqnum 21348, type 0, idx 1, rate 1, pool 21348, drops 0, input 1073741823 output 11 records 3
            enterprise 0 Extended Switch data (1001) length 16
              src vlan 0, src pri 0, dst vlan 0, dst pri 0
            enterprise 8800 Unknown (2) length 8
            enterprise 0 Raw packet (1) length 80
              protocol IPv4 (11), length 68, stripped bytes 4, header_size 64
        flow sample (1), length 160, seqnum 21349, type 0, idx 1, rate 1, pool 21349, drops 0, input 18 output 11 records 3
```

**Comment by fmoessbauer** [comment]
The same error happens on sFlow v5 data from OVS (2.15):

```
telegraf --test --input-filter sflow --config /etc/telegraf/telegraf.d/sflow.conf  --test-wait 60
2021-03-11T14:22:27Z I! Starting Telegraf 1.17.3
2021-03-11T14:22:27Z I! [inputs.sflow] Listening on udp://[::]:6343
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1e2984e]

goroutine 16 [running]:
github.com/influxdata/telegraf/plugins/inputs/sflow.EthHeader.GetTags(0xcc00000002000000, 0x8000000, 0x26, 0x0, 0x0, 0x0, 0x0, 0x1)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:146 +0x2e
github.com/influxdata/telegraf/plugins/inputs/sflow.RawPacketHeaderFlowData.GetTags(...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:121
github.com/influxdata/telegraf/plugins/inputs/sflow.makeMetrics(0xc00018e660, 0x1e2407d, 0xc0004a6e60, 0x34e5c40, 0xc00001cf60, 0xc000028b00)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/metricencoder.go:29 +0x727
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func1(0xc00018e660)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:66 +0x4d
github.com/influxdata/telegraf/plugins/inputs/sflow.(*PacketDecoder).Decode(0xc0004a6e60, 0x34e5c40, 0xc00001cf60, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/packetdecoder.go:40 +0x45
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).process(0xc00010a070, 0x3560ac0, 0xc0004a6ec0, 0xc00055e000, 0x148, 0x10000)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:135 +0x85
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).read(0xc00010a070, 0x3560ac0, 0xc0004a6ec0, 0x355a7c0, 0xc000196088)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:129 +0x8e
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func2(0xc00010a070, 0x3560ac0, 0xc0004a6ec0, 0xc000196088)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:97 +0x85
created by github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:95 +0x318
```

Sflowtool can correctly read and decode the data.

**Comment by ADeeeee** [comment]
Having the same issue when collecting sFlowv5 from FortiGate with Docker (version 20.10.5, build 55c4c88) on Ubuntu 20.04.2 LTS and the loading of the host is very low (2 cores, 8g ram).

Everything goes well at first everytime it starts and randomly it stops itself. The raw data is confirmed correct via file output and the usage of volume of influxdb is increasing, which means it does write the data into DB. Also tried recent images of telegraf from DockerHub and all having this issue. I've tried to increase the `flush_interval` and the `read_buffer_size` which might make it running longer, but still failed at the end.

It looks like an old issue last year and I haven't found any clues about it. Any workarounds or solutions for this?

**docker-compose.yml**:
```
version: '3'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    volumes:
      - ./influxdb/data:/root/.influxdbv2
    ports:
      - "8086:8086"
  influxdb_cli:
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.4
    entrypoint: influx setup --bucket BUCKET -t TOKEN -o ORG --username=USER --password=PASS --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf:1.17.3
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb_cli
    ports:
      - "6343:6343/udp"

```
**telegraf.conf**:
```
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "1s"
  flush_interval = "1s"
  flush_jitter = "1s"
  precision = ""
  quiet = true
  debug = false

[[inputs.sflow]]
  service_address = "udp://:6343"
  read_buffer_size = "4096MiB"

[[outputs.influxdb_v2]]
 urls = ["http://influxdb:8086"]
 token = "TOKEN"
 organization = "ORG"
 bucket = "BUCKET"

```

**Images**:
```
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
telegraf                    1.16.3    0e73f0d76da4   2 days ago    279MB
telegraf                    1.15.4    202ef3ff2fc6   2 days ago    276MB
telegraf                    1.17.3    f13d3af8fedb   2 weeks ago   281MB
quay.io/influxdb/influxdb   v2.0.4    4be70a587e97   4 weeks ago   227MB
```

**Debug Logs**:

```
......
2021-03-15T06:17:11Z D! [outputs.influxdb_v2] Wrote batch of 1000 metrics in 112.648606ms
2021-03-15T06:17:11Z D! [outputs.influxdb_v2] Buffer fullness: 23 / 10000 metrics
2021-03-15T06:17:13Z D! [inputs.sflow] Unknown IP protocol: 1
2021-03-15T06:17:14Z D! [inputs.sflow] Unknown IP protocol: 50
2021-03-15T06:17:14Z D! [inputs.sflow] Unknown IP protocol: 50
2021-03-15T06:17:15Z D! [inputs.sflow] Unknown IP protocol: 50
2021-03-15T06:17:16Z D! [inputs.sflow] Unknown sample type: 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19515ee]

goroutine 24 [running]:
github.com/influxdata/telegraf/plugins/inputs/sflow.EthHeader.GetTags(0x9bec000000c28001, 0xedb6588b, 0x69, 0x0, 0x0, 0x0, 0x0, 0x203000)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:146 +0x2e
github.com/influxdata/telegraf/plugins/inputs/sflow.RawPacketHeaderFlowData.GetTags(...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:121
github.com/influxdata/telegraf/plugins/inputs/sflow.makeMetrics(0xc0005c6420, 0x194c07f, 0xc00000ec40, 0x2ed7d00, 0xc0005d02d0, 0xc0005c64e0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/metricencoder.go:29 +0x6fc
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func1(0xc0005c6420)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:66 +0x4d
github.com/influxdata/telegraf/plugins/inputs/sflow.(*PacketDecoder).Decode(0xc00000ec40, 0x2ed7d00, 0xc0005d02d0, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/packetdecoder.go:40 +0x42
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).process(0xc00060e000, 0x2f4bf80, 0xc00000eca0, 0xc0001fa000, 0xd4, 0x10000)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:135 +0x83
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).read(0xc00060e000, 0x2f4bf80, 0xc00000eca0, 0x2f45080, 0xc00012e090)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:129 +0x8c
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func2(0xc00060e000, 0x2f4bf80, 0xc00000eca0, 0xc00012e090)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:97 +0x82
created by github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:95 +0x305
```

**Comment by johnp789** [comment]
I'm also having a panic with Telegraf 1.17.2 (git: HEAD 74011e22).  My source of packets is [hsflowd](https://github.com/sflow/host-sflow) on aarch64.  
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1e03ece]

goroutine 36 [running]:
github.com/influxdata/telegraf/plugins/inputs/sflow.EthHeader.GetTags(0xb1f8000000c28001, 0x3130b56, 0x27, 0x0, 0x0, 0x0, 0x0, 0x7f1ef29a7218)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:146 +0x2e
github.com/influxdata/telegraf/plugins/inputs/sflow.RawPacketHeaderFlowData.GetTags(...)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/types.go:121
github.com/influxdata/telegraf/plugins/inputs/sflow.makeMetrics(0xc000600540, 0x1dfe75d, 0xc0003b6e80, 0x34345e0, 0xc00042ea80, 0xc000600600)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/metricencoder.go:29 +0x727
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func1(0xc000600540)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:66 +0x4d
github.com/influxdata/telegraf/plugins/inputs/sflow.(*PacketDecoder).Decode(0xc0003b6e80, 0x34345e0, 0xc00042ea80, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/packetdecoder.go:40 +0x45
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).process(0xc0001a4e70, 0x34af220, 0xc0003b6fa0, 0xc00076a000, 0x98, 0x10000)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:135 +0x85
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).read(0xc0001a4e70, 0x34af220, 0xc0003b6fa0, 0x34a8fe0, 0xc000118070)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:129 +0x8e
github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start.func2(0xc0001a4e70, 0x34af220, 0xc0003b6fa0, 0xc000118070)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:97 +0x85
created by github.com/influxdata/telegraf/plugins/inputs/sflow.(*SFlow).Start
        /go/src/github.com/influxdata/telegraf/plugins/inputs/sflow/sflow.go:95 +0x318
$ ~/Downloads/telegraf-1.17.2/usr/bin/telegraf --version
Telegraf 1.17.2 (git: HEAD 74011e22)
```

**Comment by ADeeeee** [comment]
Hi guys,

I've been using the v1.18.0 for 7 days just after it released and there's no more crashes. This issue could be closed if everyone is doing well with the latest version. Thanks to @fmoessbauer

**Comment by dimdin** [comment]
I confirm that using telegraf 1.18.0 and sflow from Ubiquiti USG works perfect.
