### ISSUE TITLE
Panic on gathering docker stats

### ISSUE THREAD

**Issue by goller** [influxdata/telegraf#822]
I got this panic.

```
2016/03/09 20:50:46 Starting Telegraf (version 0.10.4.1-57-g2f45b8b)
2016/03/09 20:50:46 Loaded outputs: influxdb
2016/03/09 20:50:46 Loaded inputs: trig disk diskio mem processes swap system cpu docker influxdb net
2016/03/09 20:50:46 Tags enabled: host=ip-172-31-16-170.ec2.internal
2016/03/09 20:50:46 Agent Config: Interval:10s, Debug:false, Quiet:true, Hostname:"ip-172-31-16-170.ec2.internal", Flush Interval:10s 
2016/03/09 21:03:42 Error getting docker stats: io: read/write on closed pipe
2016/03/09 21:07:09 FATAL: Input [processes] panicked: interface conversion: interface is nil, not int64, Stack:
goroutine 2879 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc8205a6450)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:94 +0xa9
github.com/influxdata/telegraf/plugins/inputs/system.(*Processes).gatherFromProc(0xc8205a8aa0, 0xc820101170, 0x0, 0x0)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/system/processes.go:159 +0x11c6
github.com/influxdata/telegraf/plugins/inputs/system.(*Processes).Gather(0xc8205a8aa0, 0x7f808fec3458, 0xc820171880, 0x0, 0x0)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/system/processes.go:55 +0x111
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc820564a30, 0xc820014660, 0xc8200223f0, 0x0, 0xc8205a6450)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:137 +0x432
created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:141 +0x442

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc820564a3c)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc820564a30)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel(0xc8200223f0, 0xc820014660, 0x0, 0x0)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:148 +0x145
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc8200223f0, 0xc820014420, 0x0, 0x0)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/agent/agent.go:376 +0xa84
main.main()
	/Users/goller/src/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:256 +0x2246

goroutine 5 [syscall, 16 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 17 [select, 16 minutes, locked to thread]:
runtime.gopark(0x127baf8, 0xc82001af28, 0x106ddc0, 0x6, 0x7f808fec2c18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82001af28, 0x0, 0x1
2016/03/09 21:07:09 PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
2016/03/09 21:19:51 Error getting docker stats: io: read/write on closed pipe
2016/03/09 21:33:31 Error getting docker stats: io: read/write on closed pipe
```

Here is my configuration:

```
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"

[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = true
  hostname = ""

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  urls = ["***REMOVED***"]
  database = "telegraf" # required
  retention_policy = "default"
  precision = "s"
  timeout = "5s"

# Read metrics about cpu usage
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default, telegraf gather stats for all mountpoints.
  ## Setting mountpoints will restrict the stats to the specified mountpoints.
  # mount_points = ["/"]

  ## Ignore some mountpoints by filesystem type. For example (dev)tmpfs (usually
  ## present on /run, /var/run, /dev/shm or /dev).
  ignore_fs = ["tmpfs", "devtmpfs"]

# Read metrics about disk IO by device
[[inputs.diskio]]
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  ## Uncomment the following line if you do not need disk serial numbers.
  # skip_serial_number = true

# Read metrics about docker containers
[[inputs.docker]]
  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
  ## Only collect metrics for these containers, collect all if empty
  container_names = []

# Read InfluxDB-formatted JSON metrics from one or more HTTP endpoints
[[inputs.influxdb]]
  urls = [
    "http://localhost:8086/debug/vars"
  ]

# Read metrics about memory usage
[[inputs.mem]]
  # no configuration

# Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  # interfaces = ["eth0"]

# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration

# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration

# Inserts sine and cosine waves for demonstration purposes
[[inputs.trig]]
  ## Set the amplitude
  amplitude = 10.0


```

**Comment by sparrc** [comment]
looks like that's actually the `processes` plugin that panicked, I just merged that to master a few hours ago....that was quick,

what is your OS?

**Comment by goller** [comment]
I'm using CoreOS  835.13.0 and a scratch Docker container:

```
FROM scratch
MAINTAINER Chris Goller <goller@gmail.com>
ADD telegraf /telegraf
ADD telegraf.conf /telegraf.conf
CMD ["/telegraf", "-config", "/telegraf.conf"]
```

... with these run options:

```
/usr/bin/docker run --name telegraf -e HOST_PROC=/rootfs/proc -e HOST_SYS=/rootfs/sys --net=host  -v /sys:/rootfs/sys:ro  -v /proc:/rootfs/proc:ro -v /var/run/docker.sock:/var/run/docker.sock:ro telegraf
```

**Comment by sparrc** [comment]
I forgot an "s" on zombies....and didn't cover that case in the unit test either, should be fixed now
