### ISSUE TITLE
Github Webhooks panic

### ISSUE THREAD

**Issue by jasonjclifford** [influxdata/telegraf#837]
The github_webhooks service plugin seems to collect data without issue for a while and then starts triggering the below error. 

Logs:

```
2016/03/11 13:33:10 FATAL: Input [github_webhooks] panicked: runtime error: invalid memory address or nil pointer dereference, Stack:
goroutine 3789 [running]:
github.com/influxdata/telegraf/agent.panicRecover(0xc82018ac60)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:94 +0xa9
github.com/influxdata/telegraf/plugins/inputs/github_webhooks.(*GithubWebhooks).Gather(0xc82018aba0, 0x7f134862b528, 0xc820190d40, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/github_webhooks/github_webhooks.go:48 +0x11c
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1(0xc82044fe40, 0xc82001c360, 0xc820082150, 0x0, 0xc82018ac60)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:137 +0x432
created by github.com/influxdata/telegraf/agent.(*Agent).gatherParallel
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:141 +0x442

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82044fe4c)
        /usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82044fe40)
        /usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/influxdata/telegraf/agent.(*Agent).gatherParallel(0xc820082150, 0xc82001c360, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:148 +0x145
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc820082150, 0xc82001c120, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:376 +0xa84
main.main()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:234 +0x1cbc

goroutine 17 [syscall, 36 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [syscall, 36 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 50 [select, 36 minutes, locked to thread]:
runtime.gopark(0x1253938, 0xc82002b728, 0x104bd90, 0x6, 0x7f134862b018, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002b728, 0x0, 0x18)
        /usr/local/go/src/r
2016/03/11 13:33:10 PLEASE REPORT THIS PANIC ON GITHUB with stack trace, configuration, and OS information: https://github.com/influxdata/telegraf/issues/new
```
Configuration:

Telegraf version: Telegraf - Version 0.10.4.1
InfluxDB version: InfluxDB shell 0.10.2
```
# A Github Webhook Event collector
[[inputs.github_webhooks]]
  # Address and port to host Webhook listener on
  service_address = ":1618"
```
OS Info: Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Comment by sparrc** [comment]
Cc @jackzampolin
