### ISSUE TITLE
CI AppVeyor build fails intermittently on test-windows

### ISSUE THREAD

**Issue by helenosheaa** [influxdata/telegraf#8623]
AppVeyor builds keep failing on this line intermittently 

```
FAIL
511
make: *** [Makefile:117: test-windows] Error 1
```

Line 117 -

`go test -short ./...`

**Comment by zak-pawel** [comment]
@helenosheaa 

Can you provide more output for this problem? And/or link to particular CI AppVeyor build?

**Comment by helenosheaa** [comment]
@zak-pawel 

Yes, three examples of the failing builds: [here](https://ci.appveyor.com/project/influx/telegraf/builds/36995097), [here](https://ci.appveyor.com/project/influx/telegraf/builds/36872002) and [here](https://ci.appveyor.com/project/influx/telegraf/builds/36764798)

**Comment by sspaink** [comment]
Just had another failure: https://ci.appveyor.com/project/influx/telegraf/builds/37050472

For the above failure, looks like the test for the tail input plugin is failing randomly: `FAIL	github.com/influxdata/telegraf/plugins/inputs/tail	600.062s`

Full error message:
```
panic: test timed out after 10m0s
goroutine 44 [running]:
testing.(*M).startAlarm.func1()
	C:/go/src/testing/testing.go:1618 +0xe6
created by time.goFunc
	C:/go/src/time/sleep.go:167 +0x4b
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000084480, 0x14d2043, 0x22, 0x14e2348, 0x110d001)
	C:/go/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc00002cf00)
	C:/go/src/testing/testing.go:1439 +0x7f
testing.tRunner(0xc00002cf00, 0xc000071de0)
	C:/go/src/testing/testing.go:1123 +0xef
testing.runTests(0xc000004c80, 0x174bb20, 0x16, 0x16, 0xbff350bff14cff00, 0x8bb324e675, 0x17514c0, 0x107e470)
	C:/go/src/testing/testing.go:1437 +0x310
testing.(*M).Run(0xc000138400, 0x0)
	C:/go/src/testing/testing.go:1345 +0x1f5
main.main()
	_testmain.go:85 +0x145
goroutine 40 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	C:/go/src/runtime/proc.go:312
sync.runtime_notifyListWait(0xc0000913d0, 0x0)
	C:/go/src/runtime/sema.go:513 +0x117
sync.(*Cond).Wait(0xc0000913c0)
	C:/go/src/sync/cond.go:56 +0xa5
github.com/influxdata/telegraf/testutil.(*Accumulator).Wait(0xc000096230, 0x3)
	C:/gopath/src/github.com/influxdata/telegraf/testutil/accumulator.go:335 +0x7c
github.com/influxdata/telegraf/plugins/inputs/tail.TestGrokParseLogFilesWithMultiline(0xc000084480)
	C:/gopath/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail_test.go:121 +0x34e
testing.tRunner(0xc000084480, 0x14e2348)
	C:/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/go/src/testing/testing.go:1168 +0x2b3
goroutine 43 [select]:
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).receiver(0xc0000ba0f0, 0x153b760, 0xc0000ca000, 0xc0000bc0b0)
	C:/gopath/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:338 +0x2e5
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles.func2(0xc0000ba0f0, 0x153b760, 0xc0000ca000, 0xc0000bc0b0)
	C:/gopath/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:269 +0x86
created by github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles
	C:/gopath/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:267 +0x67b
goroutine 41 [select]:
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).Start.func1(0xc0000ba0f0)
	C:/gopath/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:172 +0x15a
created by github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).Start
	C:/gopath/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:169 +0xfe
goroutine 42 [chan receive]:
github.com/influxdata/tail/watch.watch(0xc00033c640, 0xc00033c640, 0x0)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/watch/inotify_tracker.go:82 +0xc5
github.com/influxdata/tail/watch.Watch(...)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/watch/inotify_tracker.go:62
github.com/influxdata/tail/watch.(*InotifyFileWatcher).ChangeEvents(0xc00008c3c0, 0xc0000bc130, 0x19a, 0x19a, 0x0, 0x0)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/watch/inotify.go:69 +0x7b
github.com/influxdata/tail.(*Tail).watchChanges(0xc0000bc0b0, 0x10bcef3, 0xc0000922f8)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/tail.go:353 +0x63
github.com/influxdata/tail.(*Tail).tailFileSync(0xc0000bc0b0)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/tail.go:254 +0x116
created by github.com/influxdata/tail.TailFile
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/tail.go:134 +0x17a
goroutine 24 [chan receive]:
gopkg.in/fsnotify%2ev1.(*Watcher).Add(0xc000043240, 0xc000092660, 0x5c, 0x5c, 0x1790800)
	C:/gopath/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/windows.go:81 +0x158
github.com/influxdata/tail/watch.(*InotifyTracker).addWatch(0xc000043200, 0xc00033c640, 0x0, 0x0)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/watch/inotify_tracker.go:154 +0x218
github.com/influxdata/tail/watch.(*InotifyTracker).run(0xc000043200)
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/watch/inotify_tracker.go:226 +0x3e6
created by github.com/influxdata/tail/watch.glob..func1
	C:/gopath/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20200707181643-03a791b270e4/watch/inotify_tracker.go:54 +0x133
goroutine 25 [chan send, locked to thread]:
gopkg.in/fsnotify%2ev1.(*Watcher).startRead(0xc000043240, 0xc000144600, 0x30, 0x0)
	C:/gopath/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/windows.go:334 +0x613
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc000043240)
	C:/gopath/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/windows.go:511 +0x433
created by gopkg.in/fsnotify%2ev1.NewWatcher
	C:/gopath/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/windows.go:46 +0x1f2
FAIL	github.com/influxdata/telegraf/plugins/inputs/tail	600.062s
```

**Comment by helenosheaa** [comment]
Yeah so two of the ones i'd referenced it was the same inputs/tail test and for the other one it was: 

```
--- FAIL: TestPowerdnsGeneratesMetrics (5.00s)
    powerdns_test.go:94: 
        	Error Trace:	powerdns_test.go:94
        	Error:      	Received unexpected error:
        	            	read unix @->C:\Users\appveyor\AppData\Local\Temp\1\pdns5239846799706671610.controlsocket: i/o timeout
        	Test:       	TestPowerdnsGeneratesMetrics
2020/12/16 19:09:18 E! [inputs.powerdns] error parsing integer for metric "corrupt-packets=18446744073709550195": strconv.ParseInt: parsing "18446744073709550195": value out of range
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/powerdns	5.081s
ok  	github.com/influxdata/telegraf/plugins/inputs/powerdns_recursor	0.058s
?   	github.com/influxdata/telegraf/plugins/inputs/processes	[no test files]
```

**Comment by ssoroka** [comment]
can use the following to try to replicate it on windows.

something like: 
```sh
go.exe test -count=1000 -run ^TestGrokParseLogFilesWithMultiline$ ./plugins/inputs/tail/...
```

**Comment by ssoroka** [comment]
ok so this is basically an issue with the inotify mode in fsnotify not working on windows.
