### ISSUE TITLE
kube_inventory: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomklapka** [influxdata/telegraf#9537]
### Relevant telegraf.conf:

```toml
[agent]
      interval = "1m"
      flush_interval = "10s"
      metric_buffer_limit = 100000
      metric_batch_size = 10000
      debug = false
    [[outputs.influxdb_v2]]
      urls = ["https://us-central1-1.gcp.cloud2.influxdata.com"]
      organization = ""
      bucket = ""
      token = ""
    [[inputs.kube_inventory]]
      url = "https://kubernetes.default"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      namespace = ""
      insecure_skip_verify = true
      resource_exclude = []
      resource_include = []
```

### System info:

bare-metal ARM64 K8s Cluster v1.19.0, Ubuntu 20.04.1 LTS, Kernel: 5.4.0-1022-raspi, docker://19.3.13
Telegraf 1.19.0, Telegraf 1.19.1

### Actual behavior:

```
2021-07-23T14:00:27Z I! Starting Telegraf 1.19.0
2021-07-23T14:00:27Z I! Using config file: /etc/telegraf/telegraf.conf
2021-07-23T14:00:27Z I! Loaded inputs: kube_inventory prometheus
2021-07-23T14:00:27Z I! Loaded aggregators: 
2021-07-23T14:00:27Z I! Loaded processors: 
2021-07-23T14:00:27Z I! Loaded outputs: influxdb_v2
2021-07-23T14:00:27Z I! Tags enabled: host=telegraf-demo-789cf4499f-vflm7
2021-07-23T14:00:27Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"telegraf-demo-789cf4499f-vflm7", Flush Interval:30s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a5e9bc]

goroutine 79 [running]:
github.com/influxdata/telegraf/plugins/inputs/kube_inventory.(*KubernetesInventory).gatherEndpoint(0x4000b8e000, 0x0, 0x0, 0x0, 0x0, 0x40003fe2f0, 0xa, 0x0, 0x0, 0x40003fe309, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/kube_inventory/endpoint.go:42 +0x82c
github.com/influxdata/telegraf/plugins/inputs/kube_inventory.collectEndpoints(0x48c0f40, 0x400018e000, 0x48efb78, 0x40002f14e0, 0x4000b8e000)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/kube_inventory/endpoint.go:18 +0xe0
github.com/influxdata/telegraf/plugins/inputs/kube_inventory.(*KubernetesInventory).Gather.func1(0x4000ab8144, 0x48c0f40, 0x400018e000, 0x48efb78, 0x40002f14e0, 0x4000b8e000, 0x41c37d8)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/kube_inventory/kube_state.go:141 +0x78
created by github.com/influxdata/telegraf/plugins/inputs/kube_inventory.(*KubernetesInventory).Gather
	/go/src/github.com/influxdata/telegraf/plugins/inputs/kube_inventory/kube_state.go:139 +0x21c
```

**Comment by corklu** [comment]
I see this behavior too, but instead of endpoints, it's persistentclaimvolumes that throw the errors.

**Comment by akrantz01** [comment]
@tomklapka Please update to 1.19.1; it should be fixed there.

**Comment by akrantz01** [comment]
@corklu could you test #9549, it should fix your issue. The built artifacts can be found [here](https://github.com/influxdata/telegraf/pull/9549#issuecomment-887742603).

**Comment by sjwang90** [comment]
Closed in #9549

**Comment by tomklapka** [comment]
> @tomklapka Please update to 1.19.1; it should be fixed there.

Same issue persists in 1.19.1 as I wrote in description.

**Comment by akrantz01** [comment]
Could you send the error you get on 1.19.1?
