### ISSUE TITLE
[0.11.1] data_format="json" is broken for output plugins

### ISSUE THREAD

**Issue by wgrcunha** [influxdata/telegraf#971]
Using amqp or kafka or mqtt got the same result.

```
Apr  5 10:38:11 sam0004 telegraf[31726]: panic: runtime error: invalid memory address or nil pointer dereference
Apr  5 10:38:11 sam0004 telegraf[31726]: [signal 0xb code=0x1 addr=0x20 pc=0x5ec91a]
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 104 [running]:
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/plugins/outputs/mqtt.(*MQTT).Write(0xc8200d85b0, 0xc8207dc000, 0x88, 0x100, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/outputs/mqtt/mqtt.go:131 +0x43a
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc82000c500, 0xc8207dc000, 0x88, 0x100, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:125 +0xa9
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc82000c500, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:103 +0xcc
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc82026dbf0, 0xc82000c500)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:255 +0x7a
Apr  5 10:38:11 sam0004 telegraf[31726]: created by github.com/influxdata/telegraf/agent.(*Agent).flush
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:260 +0xc0
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 1 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).Run(0xc820036060, 0xc8206b4300, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:380 +0xbc3
Apr  5 10:38:11 sam0004 telegraf[31726]: main.main()
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:269 +0x25f2
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 17 [syscall, locked to thread]:
Apr  5 10:38:11 sam0004 telegraf[31726]: runtime.goexit()
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 5 [syscall]:
Apr  5 10:38:11 sam0004 telegraf[31726]: os/signal.loop()
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
Apr  5 10:38:11 sam0004 telegraf[31726]: created by os/signal.init.1
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 89 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).gatherSeparate(0xc820036060, 0xc8206b4300, 0xc82006fce0, 0xc8206b47e0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:191 +0x6a4
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).Run.func2(0xc820692390, 0xc820036060, 0xc8206b4300, 0xc8206b47e0, 0xc82006fce0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:366 +0x6e
Apr  5 10:38:11 sam0004 telegraf[31726]: created by github.com/influxdata/telegraf/agent.(*Agent).Run
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:369 +0xa19
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 88 [semacquire]:
Apr  5 10:38:11 sam0004 telegraf[31726]: sync.runtime_Semacquire(0xc82026dbfc)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/sema.go:43 +0x26
Apr  5 10:38:11 sam0004 telegraf[31726]: sync.(*WaitGroup).Wait(0xc82026dbf0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/sync/waitgroup.go:126 +0xb4
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).flush(0xc820036060)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:263 +0xe9
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).flusher(0xc820036060, 0xc8206b4300, 0xc8206b47e0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:281 +0x248
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).Run.func1(0xc820692390, 0xc820036060, 0xc8206b4300, 0xc8206b47e0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:353 +0x7f
Apr  5 10:38:11 sam0004 telegraf[31726]: created by github.com/influxdata/telegraf/agent.(*Agent).Run
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:357 +0x938
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 24 [select, locked to thread]:
Apr  5 10:38:11 sam0004 telegraf[31726]: runtime.gopark(0x128b490, 0xc820535f28, 0x107b3d8, 0x6, 0x430818, 0x2)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/proc.go:185 +0x163
Apr  5 10:38:11 sam0004 telegraf[31726]: runtime.selectgoImpl(0xc820535f28, 0x0, 0x18)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/select.go:392 +0xa64
Apr  5 10:38:11 sam0004 telegraf[31726]: runtime.selectgo(0xc820535f28)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/select.go:212 +0x12
Apr  5 10:38:11 sam0004 telegraf[31726]: runtime.ensureSigM.func1()
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
Apr  5 10:38:11 sam0004 telegraf[31726]: runtime.goexit()
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 19 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*router).matchAndDispatch.func1(0xc8206b42a0, 0xc820588300, 0xd18801, 0xc8205c2000)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/router.go:132 +0x6fd
Apr  5 10:38:11 sam0004 telegraf[31726]: created by git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*router).matchAndDispatch
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/router.go:162 +0x52
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 20 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.outgoing(0xc8205c2000)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/net.go:106 +0x195a
Apr  5 10:38:11 sam0004 telegraf[31726]: created by git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*Client).Connect.func1
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/client.go:230 +0x11f2
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 21 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.alllogic(0xc8205c2000)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/net.go:174 +0x3fd8
Apr  5 10:38:11 sam0004 telegraf[31726]: created by git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*Client).Connect.func1
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/client.go:231 +0x1217
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 22 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.keepalive(0xc8205c2000)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/ping.go:27 +0xa38
Apr  5 10:38:11 sam0004 telegraf[31726]: created by git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*Client).Connect.func1
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/client.go:241 +0x1440
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 23 [IO wait]:
Apr  5 10:38:11 sam0004 telegraf[31726]: net.runtime_pollWait(0x7f5442272f98, 0x72, 0xc82000e160)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*pollDesc).Wait(0xc820466990, 0x72, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*pollDesc).WaitRead(0xc820466990, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*netFD).Read(0xc820466930, 0xc82026db80, 0x1, 0x1, 0x0, 0x7f5442268050, 0xc82000e160)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/fd_unix.go:232 +0x23a
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*conn).Read(0xc820036000, 0xc82026db80, 0x1, 0x1, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/net.go:172 +0xe4
Apr  5 10:38:11 sam0004 telegraf[31726]: io.ReadAtLeast(0x7f54403b8258, 0xc820036000, 0xc82026db80, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/io/io.go:298 +0xe6
Apr  5 10:38:11 sam0004 telegraf[31726]: io.ReadFull(0x7f54403b8258, 0xc820036000, 0xc82026db80, 0x1, 0x1, 0x1, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/io/io.go:316 +0x62
Apr  5 10:38:11 sam0004 telegraf[31726]: git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets.ReadPacket(0x7f54403b8258, 0xc820036000, 0x0, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets/packets.go:105 +0xd4
Apr  5 10:38:11 sam0004 telegraf[31726]: git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.incoming(0xc8205c2000)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/net.go:78 +0x263
Apr  5 10:38:11 sam0004 telegraf[31726]: created by git.eclipse.org/gitroot/paho/org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*Client).Connect.func1
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/client.go:254 +0x14a4
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 25 [chan receive]:
Apr  5 10:38:11 sam0004 telegraf[31726]: main.main.func2(0xc8206b43c0, 0xc8206b4300, 0xc82041d960)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:241 +0x47
Apr  5 10:38:11 sam0004 telegraf[31726]: created by main.main
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:251 +0x1ebf
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 103 [runnable]:
Apr  5 10:38:11 sam0004 telegraf[31726]: math/rand.(*Rand).Intn(0xc82000e2f0, 0x1, 0x1)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/math/rand/rand.go:96
Apr  5 10:38:11 sam0004 telegraf[31726]: math/rand.(*Rand).Perm(0xc82000e2f0, 0x1, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/math/rand/rand.go:152 +0x8f
Apr  5 10:38:11 sam0004 telegraf[31726]: math/rand.Perm(0x1, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/math/rand/rand.go:210 +0x3e
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/plugins/outputs/influxdb.(*InfluxDB).Write(0xc8200b2000, 0xc820791000, 0x88, 0x100, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/outputs/influxdb/influxdb.go:185 +0x3a4
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc820298000, 0xc820791000, 0x88, 0x100, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:125 +0xa9
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc820298000, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:103 +0xcc
Apr  5 10:38:11 sam0004 telegraf[31726]: github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc82026dbf0, 0xc820298000)
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:255 +0x7a
Apr  5 10:38:11 sam0004 telegraf[31726]: created by github.com/influxdata/telegraf/agent.(*Agent).flush
Apr  5 10:38:11 sam0004 telegraf[31726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:260 +0xc0
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 130 [IO wait]:
Apr  5 10:38:11 sam0004 telegraf[31726]: net.runtime_pollWait(0x7f5442272ed8, 0x72, 0xc82000e160)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*pollDesc).Wait(0xc8201d6d10, 0x72, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*pollDesc).WaitRead(0xc8201d6d10, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*netFD).Read(0xc8201d6cb0, 0xc82036e000, 0x1000, 0x1000, 0x0, 0x7f5442268050, 0xc82000e160)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/fd_unix.go:232 +0x23a
Apr  5 10:38:11 sam0004 telegraf[31726]: net.(*conn).Read(0xc820372000, 0xc82036e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/net.go:172 +0xe4
Apr  5 10:38:11 sam0004 telegraf[31726]: net/http.noteEOFReader.Read(0x7f54403b8258, 0xc820372000, 0xc8200c9448, 0xc82036e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/http/transport.go:1370 +0x67
Apr  5 10:38:11 sam0004 telegraf[31726]: net/http.(*noteEOFReader).Read(0xc82067a040, 0xc82036e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: <autogenerated>:126 +0xd0
Apr  5 10:38:11 sam0004 telegraf[31726]: bufio.(*Reader).fill(0xc820158180)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Apr  5 10:38:11 sam0004 telegraf[31726]: bufio.(*Reader).Peek(0xc820158180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/bufio/bufio.go:132 +0xcc
Apr  5 10:38:11 sam0004 telegraf[31726]: net/http.(*persistConn).readLoop(0xc8200c93f0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/http/transport.go:876 +0xf7
Apr  5 10:38:11 sam0004 telegraf[31726]: created by net/http.(*Transport).dialConn
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/http/transport.go:685 +0xc78
Apr  5 10:38:11 sam0004 telegraf[31726]: goroutine 131 [select]:
Apr  5 10:38:11 sam0004 telegraf[31726]: net/http.(*persistConn).writeLoop(0xc8200c93f0)
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/http/transport.go:1009 +0x40c
Apr  5 10:38:11 sam0004 telegraf[31726]: created by net/http.(*Transport).dialConn
Apr  5 10:38:11 sam0004 telegraf[31726]: /usr/local/go/src/net/http/transport.go:686 +0xc9d
```

graphite output is fine:

```
Apr  5 10:37:00 sam0004 telegraf[30427]: 2016/04/05 10:37:00 Wrote 134 metrics to output mqtt in 40.712994ms
```

**Comment by wgrcunha** [comment]
Plugins enabled inputs/outputs
```
Apr  5 10:39:17 sam0004 telegraf[32425]: 2016/04/05 10:39:17 Starting Telegraf (version 0.11.1)
Apr  5 10:39:17 sam0004 telegraf[32425]: 2016/04/05 10:39:17 Loaded outputs: influxdb mqtt
Apr  5 10:39:17 sam0004 telegraf[32425]: 2016/04/05 10:39:17 Loaded inputs: swap system net cpu disk diskio mem exec influxdb
```

**Comment by wgrcunha** [comment]
Working on 0.12.0

closing
